### ISSUE TITLE
Problem indexing multiple subdirectories

### ISSUE THREAD

**Issue by fjr29** [dadoonet/fscrawler#1011]
We have mutilple subdirectories (under the defined url dir) where our files are located to be indexed/processed.  fscrawler indexes the first 'path' and then stops.  No other paths/files are processed after the first one.  Looking at example below: the files in subdirectory1 are indexed.   Nothing else processed after that.  As a further test, I removed subdirectory1 and restarted fscrawler.  The files in subdirectory2/sbdira were processed but again nothing else.  I'm sure it has something to do with our configuration.  It is running in its own docker container, we based it on doc listed on the site.   

We do see an fscrawler error at the end of processing the dir.  Has something to do with file.filename not set to true.  But we do see it set properly in _settings.json in the _default/7 dir.  Also there is no _status.json file in our config/job dir.

Listed below are the config data and error.

Any insight or help would be greatly appreciated.  We really like fscrawler and want to incorporate it into our process.

The file structure is something like this:

rootdir 
  subdirectory1
        files
  subdirectory2
        subdira
            files
        subdirb
            files
  subdiretory3
        files
......

_settings.yml (found in config/jobname)
![image](https://user-images.githubusercontent.com/26879140/93258826-e9d80b00-f76c-11ea-958e-0428f975b181.png)

error
![image](https://user-images.githubusercontent.com/26879140/93259184-72ef4200-f76d-11ea-9044-96d80795c5c4.png)

fscrawler config file structure
![image](https://user-images.githubusercontent.com/26879140/93259356-bd70be80-f76d-11ea-8e0c-29f20ab601fa.png)

_setting.json
![image](https://user-images.githubusercontent.com/26879140/93259744-4ee03080-f76e-11ea-84f4-05e0ea017ef6.png)

**Comment by dadoonet** [comment]
The error message is important. 
Please share the full logs but not as images please. As text and use the format button. Thanks.

**Comment by fjr29** [comment]
Hi, Thanks for the quick response.  Attached is the log file

[logfile.txt](https://github.com/dadoonet/fscrawler/files/5232489/logfile.txt)

**Comment by dadoonet** [comment]
The important part:

```
13:18:38,566 [33mWARN [m [f.p.e.c.f.FsParserAbstract] Error while crawling /usr/share/fscrawler/data: Mapping is incorrect: please set stored: true on field [file.filename].
13:18:38,566 [33mWARN [m [f.p.e.c.f.FsParserAbstract] Full stacktrace
java.lang.RuntimeException: Mapping is incorrect: please set stored: true on field [file.filename].
	at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.getFileDirectory(FsParserAbstract.java:374) ~[fscrawler-core-2.7-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.addFilesRecursively(FsParserAbstract.java:309) ~[fscrawler-core-2.7-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.addFilesRecursively(FsParserAbstract.java:291) ~[fscrawler-core-2.7-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.addFilesRecursively(FsParserAbstract.java:291) ~[fscrawler-core-2.7-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.run(FsParserAbstract.java:149) [fscrawler-core-2.7-SNAPSHOT.jar:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

It means that your mapping is incorrect.

I'd remove `linquest_job*` indices by running this in Kibana:

```
DELETE linquest_job*
```

And start again.

If it still does not work, it would probably indicate that you changed the default mapping. In which case, you'll need to share it here.

**Comment by fjr29** [comment]
Thx again for the feedback.  We removed the indices from elastic search but still see the same issue.  I not aware of changing the mappings in _default.  But they are attached.  Under _default, we two dirs: 6 and 7.  Attached are the json files from 7.  Should the 6 dir be there?  

Please note that the extension for these file is txt.  I only did that so that they would be copied into the issue.  These are copies of the files.  The real mappings were not touched and have .json extension.

[_settings.txt](https://github.com/dadoonet/fscrawler/files/5239484/_settings.txt)
[_settings_folder.txt](https://github.com/dadoonet/fscrawler/files/5239488/_settings_folder.txt)

**Comment by dadoonet** [comment]
Instead. Could you provide here the output of:

    GET linquest_job*/_mapping

Please copy/paste the result here instead of attaching a file. 

Thanks

**Comment by fjr29** [comment]
Here you go:  I did both a _cat and _mapping


[root@LA-BIPSVC1 rhel_user]# curl -XGET localhost:9200/_cat/indices
yellow open linquest_job        rHTlS-eMTWyVDagIKcvhfg 1 1 55 16840 129.5mb 129.5mb
yellow open linquest_job_folder 4ExvBmRETRy-1XY4pDnykg 1 1  2     0   5.7kb   5.7kb
yellow open test-docs           SH-XUUt0S7mOBbVkJGTl8Q 1 1  0     0    283b    283b
yellow open test-docs_folder    zqxsdt_KQ1K7mWY1pNe_Ig 1 1  0     0    283b    283b
green  open .kibana_1           ralUM--eTUSXxEFkE9qHKw 1 0 12     1  18.7kb  18.7kb
[root@LA-BIPSVC1 rhel_user]# curl -XGET localhost:9200/linquest_job*/_mapping
{"linquest_job":{"mappings":{"properties":{"content":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"file":{"properties":{"content_type":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"created":{"type":"date"},"extension":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"filename":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"filesize":{"type":"long"},"indexing_date":{"type":"date"},"last_accessed":{"type":"date"},"last_modified":{"type":"date"},"url":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}}}},"meta":{"properties":{"author":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"created":{"type":"date"},"creator_tool":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"date":{"type":"date"},"format":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"language":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"modifier":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"print_date":{"type":"date"},"publisher":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"title":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}}}},"path":{"properties":{"real":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"root":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"virtual":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}}}}}}},"linquest_job_folder":{"mappings":{"properties":{"real":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"root":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"virtual":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}}}}}}[root@LA-BIPSVC1 rhel_user]#

**Comment by dadoonet** [comment]
Is that the full output? I'm missing `linquest_job_folder` mapping. 

Could you also please run the commands from Kibana or append `?pretty`? And use markdown or the `<>` icon to format your code?

**Comment by fjr29** [comment]
here are both mappings: linquest_job and linquest_job_folder

--------------linquest_job --------------------------
{
	"linquest_job": {
		"mappings": {
			"properties": {
				"content": {
					"type": "text",
					"fields": {
						"keyword": {
							"type": "keyword",
							"ignore_above": 256
						}
					}
				},
				"file": {
					"properties": {
						"content_type": {
							"type": "text",
							"fields": {
								"keyword": {
									"type": "keyword",
									"ignore_above": 256
								}
							}
						},
						"created": {
							"type": "date"
						},
						"extension": {
							"type": "text",
							"fields": {
								"keyword": {
									"type": "keyword",
									"ignore_above": 256
								}
							}
						},
						"filename": {
							"type": "text",
							"fields": {
								"keyword": {
									"type": "keyword",
									"ignore_above": 256
								}
							}
						},
						"filesize": {
							"type": "long"
						},
						"indexing_date": {
							"type": "date"
						},
						"last_accessed": {
							"type": "date"
						},
						"last_modified": {
							"type": "date"
						},
						"url": {
							"type": "text",
							"fields": {
								"keyword": {
									"type": "keyword",
									"ignore_above": 256
								}
							}
						}
					}
				},
				"meta": {
					"properties": {
						"author": {
							"type": "text",
							"fields": {
								"keyword": {
									"type": "keyword",
									"ignore_above": 256
								}
							}
						},
						"created": {
							"type": "date"
						},
						"creator_tool": {
							"type": "text",
							"fields": {
								"keyword": {
									"type": "keyword",
									"ignore_above": 256
								}
							}
						},
						"date": {
							"type": "date"
						},
						"format": {
							"type": "text",
							"fields": {
								"keyword": {
									"type": "keyword",
									"ignore_above": 256
								}
							}
						},
						"language": {
							"type": "text",
							"fields": {
								"keyword": {
									"type": "keyword",
									"ignore_above": 256
								}
							}
						},
						"modifier": {
							"type": "text",
							"fields": {
								"keyword": {
									"type": "keyword",
									"ignore_above": 256
								}
							}
						},
						"print_date": {
							"type": "date"
						},
						"publisher": {
							"type": "text",
							"fields": {
								"keyword": {
									"type": "keyword",
									"ignore_above": 256
								}
							}
						},
						"title": {
							"type": "text",
							"fields": {
								"keyword": {
									"type": "keyword",
									"ignore_above": 256
								}
							}
						}
					}
				},
				"path": {
					"properties": {
						"real": {
							"type": "text",
							"fields": {
								"keyword": {
									"type": "keyword",
									"ignore_above": 256
								}
							}
						},
						"root": {
							"type": "text",
							"fields": {
								"keyword": {
									"type": "keyword",
									"ignore_above": 256
								}
							}
						},
						"virtual": {
							"type": "text",
							"fields": {
								"keyword": {
									"type": "keyword",
									"ignore_above": 256
								}
							}
						}
					}
				}
			}
		}
	}
}
-----------------------------------------------------


-------------linquest_job_folder -------------------
{
	"linquest_job_folder": {
		"mappings": {
			"properties": {
				"real": {
					"type": "text",
					"fields": {
						"keyword": {
							"type": "keyword",
							"ignore_above": 256
						}
					}
				},
				"root": {
					"type": "text",
					"fields": {
						"keyword": {
							"type": "keyword",
							"ignore_above": 256
						}
					}
				},
				"virtual": {
					"type": "text",
					"fields": {
						"keyword": {
							"type": "keyword",
							"ignore_above": 256
						}
					}
				}
			}
		}
	}
}
----------------------------------------------------

**Comment by dadoonet** [comment]
Please, format the code so it's easier to read. We are missing the indentation here.

**Comment by fjr29** [comment]
--------------linquest_job --------------------------
```
{
  "linquest_job": {
    "mappings": {
      "properties": {
        "content": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "file": {
          "properties": {
            "content_type": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            },
            "created": {
              "type": "date"
            },
            "extension": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            },
            "filename": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            },
            "filesize": {
              "type": "long"
            },
            "indexing_date": {
              "type": "date"
            },
            "last_accessed": {
              "type": "date"
            },
            "last_modified": {
              "type": "date"
            },
            "url": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            }
          }
        },
        "meta": {
          "properties": {
            "author": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            },
            "created": {
              "type": "date"
            },
            "creator_tool": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            },
            "date": {
              "type": "date"
            },
            "format": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            },
            "language": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            },
            "modifier": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            },
            "print_date": {
              "type": "date"
            },
            "publisher": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            },
            "title": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            }
          }
        },
        "path": {
          "properties": {
            "real": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            },
            "root": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            },
            "virtual": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            }
          }
        }
      }
    }
  }
}
```


-------------linquest_job_folder -------------------

```
{
  "linquest_job_folder": {
    "mappings": {
      "properties": {
        "real": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "root": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "virtual": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        }
      }
    }
  }
}
```

**Comment by dadoonet** [comment]
It looks like a generated mapping by elasticsearch and not the one which is available in the FSCrawler default configuration dir.

Again, remove all the indices and start from scratch.

**Comment by dadoonet** [comment]
Could you share your job settings but not as an image?

**Comment by fjr29** [comment]
Will try again.  Listed is the job settings

```
---
name: "linquest_job"
fs:
  url: "/usr/share/fscrawler/data"
  update_rate: "180s"
  excludes:
  - "*/~*"
  json_support: false
  filename_as_id: false
  add_filesize: true
  remove_deleted: true
  add_as_inner_object: false
  store_source: false
  index_content: true
  attributes_support: false
  raw_metadata: false
  xml_support: false
  index_folders: true
  lang_detect: false
  continue_on_error: false
  ocr:
    language: "eng"
    enabled: true
    pdf_strategy: "ocr_and_text"
  follow_symlinks: false
elasticsearch:
  nodes:
  - url: 10.1.150.50:9080
  bulk_size: 100
  flush_interval: "5s"
  byte_size: "10mb"

```

**Comment by dadoonet** [comment]
Thanks.

Just to be sure. Are you using the latest SNAPSHOT? Should be a 2.7 version.

**Comment by dadoonet** [comment]
Feel free to open a new [discussion](https://github.com/dadoonet/fscrawler/discussions) about it if needed. I'm closing for now.
