### ISSUE TITLE
FScrawler REST Vs Ingest Attachment

### ISSUE THREAD

**Issue by yapnel** [dadoonet/fscrawler#1026]
What're the pros and cons between FScrawler REST gateway and ES ingest attachment plugin? Trying to determine which is better for ingesting binary content into ES. Thanks

**Comment by dadoonet** [comment]
FSCrawler has no limitations in supported documents, OCR...
Ingest attachment plugin does not need another service to run as it runs inside elasticsearch and is de facto scalable.

**Comment by yapnel** [comment]
Thanks for the quick reply. Is OCR supported in ingest attachment?

**Comment by dadoonet** [comment]
No. It's not.
