### ISSUE TITLE
Can I connect to both Samba and Workplace Search?

### ISSUE THREAD

**Issue by lakemike** [dadoonet/fscrawler#1029]
First of all, thanks to all the excellent work! I think this is excellent software and will be a great asset for the community!

So far, I've been able to successfully use fscrawler to create an index and have it accessible via Samba / MacOS Spotlight. Afterwards I also got the workplace search to work using the fscrawler version provided as part of the ongoing WIP. Now I realize that it's populating a different index structure and it seems to break the connectivity to samba.

Q: Not sure if bug or feature, but shall there be a way to send queries both via Samba/Spotlight and also via Workplace search?

All the best!

**Comment by dadoonet** [comment]
This should work. The input part (samba) should not have any impact on the output part (elasticsearch or workplace search).

> Now I realize that it's populating a different index structure and it seems to break the connectivity to samba.

Could you clarify what you are meaning by this?

**Comment by lakemike** [comment]
My first setup was to connect fscrawler to elasticsearch without workplace search. It created an index "idx" and "idx_folder" in elasticsearch. I could then specify the elasticsearch backend in smb.conf and MacOS/ Spotlight would be able to query the full-text index. So far so good.

When I moved to the WIP version, I was then able to connect fscrawler to workplace and I can also successfully search via that web interface. But I just noticed there is no index "idx" anymore. Instead, there are plenty of indices beginning with ".ent..." And indeed, in the absence of the "idx" index, Samba/ Spotlight does not seem to pull any results.

**Comment by dadoonet** [comment]
Oh... I think I forgot about this: https://wiki.samba.org/index.php/Spotlight_with_Elasticsearch_Backend

Never looked at the code. w00t. That's amazing:

https://github.com/samba-team/samba/blob/master/source3/rpc_server/mdssvc/elasticsearch_mappings.json

I think that Samba project should add the support for Workplace Search Search API probably.

When you send data to WPSearch, you need to use WPSearch APIs then. Elasticsearch is actually hidden and is an implementation detail then.

You can may be hack around but I think it's hard to solve.... 😞

**Comment by lakemike** [comment]
Ouch.

I was hoping that elasticsearch is the way to have just one full-text index for both Samba/Spotlight and Web searches. It takes a while to index and each of these indices is a memory hog for obvious reasons.

Do let me know if you see a way around.. Am wondering if it would be possible to transform the index created by WPSearch into a structure that would recreate the original "idx", so that both query types could work. Or possibly WPSearch can populate the database in a way like the original elasticsearch interface did.

**Comment by dadoonet** [comment]
If I understand your use case correctly, you want to be able to search both from the Workplace Search UI and from Spotlight. Is that correct?

In case it helps, you can search using your browser. Have a look at: https://www.elastic.co/guide/en/workplace-search/current/searching-workplace-search-from-your-web-browsers-address-bar.html

I believe that it would be great to be able to connect Spotlight with Workplace Search but that's another story and outside the scope of FSCrawler project 😄 

@omegahm from the enterprise search team wrote me internally:

> There’s no way to hook into Spotlight directly, but we could probably write a plugin for Flashlight (https://www.macenhance.com/flashlight) that will do the search. 
> Do note that we’ll need to come up with a way to inject the custom URL along with an access token in order for us to use that to search directly.


Back to your question:

> Am wondering if it would be possible to transform the index created by WPSearch into a structure that would recreate the original "idx", so that both query types could work.

That'd mean indexing the content twice.
In which case that could be supported by FSCrawler (having both outputs) but I highly doubt that would be a good thing to do.

I'm wondering if you could use some kind of [field aliases](https://www.elastic.co/fr/blog/introducing-field-aliases-in-elasticsearch) on the index created by Workplace Search...

The index name is `.ent-search-engine-[ID]`.

If you run something like:

```
GET .ent-search-engine-*/_search
```

You will some sample documents, like the following (I removed the non needed parts):

```json
      {
          "extension$string" : "txt",
          "comments$string" : null,
          "keywords$string" : null,
          "author$string" : null,
          "created_at$date" : "2018-01-12T13:31:31+00:00",
          "language$string" : "de",
          "body$string" : """Diese Datei enthält ein paar Worte.

""",
          "title$string" : "test-de.txt",
          "url$string" : "http://127.0.0.1/test-de.txt",
          "path$string" : "../docs/full/test-de.txt",
          "size$float" : 37.0,
          "text_size$float" : null,
          "mime_type$string" : "text/plain; charset=UTF-8",
          "name$string" : "test-de.txt",
          "last_modified$date" : "2018-01-12T13:31:31+00:00",
          "source$enum" : "custom",
          "content_source_id$enum" : "5f632f732c1b447417810809",
          "last_updated$date" : "2020-09-18T09:20:48+00:00",
          "id" : "5f63302c2c1b44b3bd810820",
          "external_id" : "903799df83f776acdfd41d51a55547",
        }
```

So you can may be map those fields with the expected structure described in both:
* https://github.com/samba-team/samba/blob/master/source3/rpc_server/mdssvc/elasticsearch_mappings.json
* https://fscrawler.readthedocs.io/en/latest/admin/fs/elasticsearch.html#generated-fields

**Comment by lakemike** [comment]
Thank you for sharing this background! Very helpful and I will look into it. (Most likely year-end though ;)

Please let me ask about your long(er) term plans for the FSCrawler-Elasticsearch interaction: Will you keep that part of the code that loads from FSCrawler into Elasticsearch directly? As said, I did get it work with Samba/ Spotlight and it would be great to be able to use it for a while. Hoping for a yes, since it's now also in the Samba code :)

**Comment by dadoonet** [comment]
Elasticsearch will be kept indeed as the main output for FSCrawler. I have no plan to remove it.

When the Workplace Search output is used by the user, for now you need as well to have access to elasticsearch. This is the thing I want to remove.

So at the end, the user will choose between:

* Elasticsearch
* Workplace Search
* A generic HTTP output (which can be used by Logstash or filebeat for example).

**Comment by dadoonet** [comment]
Feel free to open a new [discussion](https://github.com/dadoonet/fscrawler/discussions) about it if needed. I'm closing for now.
