### ISSUE TITLE
Store only metadata of files in a directory tree

### ISSUE THREAD

**Issue by jbwl** [dadoonet/fscrawler#103]
Hello,

I have a hard time figuring out how to not store or index any file content but only some metadata of the files, such as the content-type, the filename, the modification time, and the path - but nothing more.

The use case is to store a directory tree with a huge number of files, and use fsriver to automatically add new files in the tree to the ES index.

I think the indexing of just the metadata should be very quick if I can somehow create a river / mapping that does not even look at the file content. But how?

Thanks for any help.

**Comment by dadoonet** [comment]
I think this is an option we could support. Adding this to the todo list :)

**Comment by jbwl** [comment]
Thank you! I will try asap and report back.

**Comment by dadoonet** [comment]
Don't be confused. This one is not fixed yet. Currently working on it ATM.

**Comment by dadoonet** [comment]
BTW when writing the code and reading again your needs, you wrote that you need:

* to be fast
* to extract the content-type

Well. If you want the content-type, it means that I have to call Tika which won't accelerate really the code.
And I think that for now you can simply set `fs.indexed_chars` to `0` and no content will be extracted (only meta data).

So I wonder if in the case the user set a new property `index_content` to `false` we should simply ignore any Tika call so we just index filesystem metadata (filename, path, size, date) and ignore all the rest. What do you think?

**Comment by jbwl** [comment]
I think the content-type would just be "nice to have" but not necessary if it adds a lot of overhead. Please go ahead with your idea!

**Comment by dadoonet** [comment]
Yeah. That's what I implemented. Simple things. :)
