### ISSUE TITLE
Index unparsable files

### ISSUE THREAD

**Issue by subutux** [dadoonet/fscrawler#105]
Would it be possible to index unparsable files? For ex. I have a directory containing multiple ISO images and would like to use fsriver to be able to search on filename. Could this be possible?

**Comment by dadoonet** [comment]
It sounds like a good idea to me. Will try to add it.

**Comment by subutux** [comment]
Thanks!



—
Verzonden via Mailbox

**Comment by dadoonet** [comment]
I started some work about this but was actually unable to fail the process with a bad document. Any chance you could provide me a small binary document which is not readable so I can add a test and fix if needed?

**Comment by subutux** [comment]
Do you mean a corrupt word doc of somesort? Or a corrupt inparsable file (like for ex. An currupt iso file)

**Comment by dadoonet** [comment]
The one you mentioned when you opened the issue.

**Comment by subutux** [comment]
Smallest iso I could find. 1MB in size.
[ipxe.iso](https://www.dropbox.com/s/ved0uqy0fne2jns/ipxe.iso?dl=1)

**Comment by subutux** [comment]
Any news on this?

**Comment by dadoonet** [comment]
@subutux Sorry. I did not manage to find time to work on this. Still on my list though.

**Comment by dadoonet** [comment]
Forgot to say that this has been fixed with fscrawler 2.0.0. Thanks for suggesting this idea!
