### ISSUE TITLE
How to Turn off update rate?

### ISSUE THREAD

**Issue by jaganreddy** [dadoonet/fscrawler#106]
I think this is not an issue, I am unable to configure the following requirement.

As per document update rate by default is 15min. But I want to turn off the update rate and update index will execute only I placed new document or delete an old document. 

On my web application when user uploads a document then only the index call should execute.

**Comment by dadoonet** [comment]
So you want to run manually the river? Is that what you are looking for?

**Comment by jaganreddy** [comment]
Yes

**Comment by dadoonet** [comment]
The only workaround I see is:

Suspend or restart a file river

If you need to stop a river, you can call the `_stop' endpoint:

GET _river/mydocs/_stop

To restart the river from the previous point, just call _start end point:

GET _river/mydocs/_start

**Comment by jaganreddy** [comment]
Thanks David, I will try this out.
