### ISSUE TITLE
more mp3 tags

### ISSUE THREAD

**Issue by ralfebs** [dadoonet/fscrawler#1062]
in TikaDocParserTest.java i see many mp3 tags like artist, album etc.
But in FsCrawlerImplAllDocumentsIT.java i see only Meta.FIELD_NAMES.TITLE and Meta.FIELD_NAMES.AUTHOR.
I would like to have many of the mp3 tags in elasticsearch. 
First of all the album tag to make my kibana dashboard more valuable.

**Comment by dadoonet** [comment]
Did you try this option? https://fscrawler.readthedocs.io/en/latest/admin/fs/local-fs.html#disabling-raw-metadata

**Comment by ralfebs** [comment]
i stopped fscrawler

change the setting
diff _settings.yaml.20201221.001 _settings.yaml.20201221.002
15c15
<   attributes_support: false
---
>   attributes_support: true

delete the index
delete the job status

restart fscrawler

refresh the kibana index pattern

but it seems doesnt help :-(

thanks for you quick response

**Comment by dadoonet** [comment]
Could you start with `--trace` option and share the logs here? Formatted with `<>` please.

**Comment by ralfebs** [comment]
sorry. I changed attribute above raw_metadata.
Now i changed raw_metadata: from false to true and it works.

Thanks a lot for your quick response.

![grafik](https://user-images.githubusercontent.com/76400202/102802795-7d962480-43b7-11eb-9581-4d9fb4e4ef26.png)

But most of the mp3 tags could be useful for all MP3 elasticsearch users.

A default activation without the raw part would be nice.

:-)

**Comment by dadoonet** [comment]
The problem with that is that it creates too much noise. It extracts the raw metadata. 
If the raw metadata is known as "standard" by Tika, it's then generated as a "standard" metadata in Tika, and then FSCrawler.

This page describes what is "standard": https://fscrawler.readthedocs.io/en/latest/admin/fs/elasticsearch.html#generated-fields

Everything in `meta.` is coming as standard by Tika.

Of course we could change that if needed in FSCrawler and check if one of the metadata you mentioned is in the list and then copy it to a `meta.music.xxx` meta name for example.
May be we could come also with a default ingest pipeline to use with FSCrawler?

Is it something you would like to work on and contribute to the project?

**Comment by ralfebs** [comment]
I like fscrawler, elasticsearch and java.
But it is a question of time.
I wrote only smaller java programs at beginners level.
First i will enhance my mp3 dashboardand  then i will use fscrawler for other types documents odt pdf etc.
Maybe jpeq's exif tags has the same challenge.
Nearby i will read your documentation and take a closer look at the sources.
