### ISSUE TITLE
es7-2.7 Snapshot Failure ERROR StatusLogger Reconfiguration failed

### ISSUE THREAD

**Issue by CircuitGuy** [dadoonet/fscrawler#1080]
**Describe the bug**

Trying to go through the first-time setup and hitting an error I can't resolve.

The ERROR line is returned, but nothing else seems to happen. Ctrl+C shows the rest of the exception.

```
ERROR StatusLogger Reconfiguration failed: No configuration found for '4e0e2f2a' at 'null' in 'null'
Exception in thread "main" java.util.NoSuchElementException
        at java.base/java.util.Scanner.throwFor(Scanner.java:937)
        at java.base/java.util.Scanner.next(Scanner.java:1478)
        at fr.pilato.elasticsearch.crawler.fs.cli.FsCrawlerCli.main(FsCrawlerCli.java:239)
Terminate batch job (Y/N)? y

```
**Job Settings**

To get this error message, I simply extracted the versions listed below into their directories and ran this batch file. This file sets the Java version and launches all utilities.

```
set JAVA_HOME="%cd%\jdk-14.0.2"
set FS_JAVA_OPTS=-Xmx2g -Xms2g

start "Elastic Search" cmd /k .\elasticsearch-7.10.2\bin\elasticsearch.bat
start "Kibana" cmd /k .\kibana-7.10.2-windows-x86_64\bin\kibana.bat
timeout /t 60
start "FS Crawler" cmd /k .\fscrawler-es7-2.7-SNAPSHOT\bin\fscrawler.bat test
pause
```

**Logs**
 - N/A - No logs generated. Crash occurs before the app gets to generate it's config file. It does seem to build the _default config though.

**Versions:**
 - Windows 10
 - Fscrawler ES7 Snapshot 
    - fscrawler-es7-2.7-20201223.112706-152
    - fscrawler-es7-2.7-20210104.212634-153
    - fscrawler-es7-2.7-20210121.084108-154
 - Java jdk-14.0.2 (tried several others as well)
 - elasticsearch-7.10.2

See also #780 where this discussion started. However, this seems like a different issue.

**Comment by CircuitGuy** [comment]
FYI - verified I get this same response when built from the latest source using jdk-14.0.2.  I had to build with the -DskipTests option.

**Comment by CircuitGuy** [comment]
Solved! I had to create a new file manually that I don't see anywhere in the docs. ./config/log4j2.xml

I filled it with a random default I found on the internet.
[
[log4j2_DOT_xml.txt](https://github.com/dadoonet/fscrawler/files/5871140/log4j2_DOT_xml.txt)
](url)

**Comment by dadoonet** [comment]
That's great. Does it mean that the default distribution does not contain the default `config` dir?

**Comment by CircuitGuy** [comment]
It turns out the problem was me (sort of). The .bat is a little touchy and expects to have pwd one directory up from the \bin.

I put in PR #1085 to 'solve' this issue if you see it as an improvement.

Thanks!
