### ISSUE TITLE
only indexed 100KB content

### ISSUE THREAD

**Issue by momocg** [dadoonet/fscrawler#1082]
**Describe the bug**

when the file exceed 100KB,  the elasticsearch only indexed 100KB. 

**Job Settings**

default settings. only change the elasticsearch url.

**Logs**

no error log

**Versions:**
 - Elasticsearch: [7.10.2]
 - Fscrawler [7.2.7]

**Comment by dadoonet** [comment]
Did you try to change this? https://fscrawler.readthedocs.io/en/latest/admin/fs/local-fs.html#extracted-characters
