### ISSUE TITLE
fscrawler report a error

### ISSUE THREAD

**Issue by lionliujia** [dadoonet/fscrawler#1092]
windows10 vm ,  elasticsearch 7.10.2 and kibana 7.10.2 works fine .  when I run this bat file:
"set JAVA_HOME=C:\Program Files\Java\jdk-15.0.1

set FS_JAVA_OPTS=-Xmx2g -Xms2g

C:\fscrawler-es7-2.7-SNAPSHOT\bin\fscrawler.bat --config_dir C:\fscrawler-es7-2.7-SNAPSHOT\config data >> C:\fscrawler-es7-2.7-SNAPSHOT\logs\fscrawler.log 2>&1"

the cmd display nothing and the fscrawler.log has this content:
"ERROR StatusLogger Reconfiguration failed: No configuration found for '73d16e93' at 'null' in 'null'
Exception in thread "main" java.util.NoSuchElementException
	at java.base/java.util.Scanner.throwFor(Scanner.java:937)
	at java.base/java.util.Scanner.next(Scanner.java:1478)
	at fr.pilato.elasticsearch.crawler.fs.cli.FsCrawlerCli.main(FsCrawlerCli.java:239)
Terminate batch job (Y/N)? "

**Comment by dadoonet** [comment]
Why do you want this?

`    >> C:\fscrawler-es7-2.7-SNAPSHOT\logs\fscrawler.log 2>&1`

**Comment by lionliujia** [comment]
because it is in this page , I'm not familiar with fscrawler，so I  just According to the example to do
https://fscrawler.readthedocs.io/en/latest/installation.html

**Comment by lionliujia** [comment]
Create a fscrawlerRunner.bat as:
set JAVA_HOME=c:\Program Files\Java\jdk15.0.1
set FS_JAVA_OPTS=-Xmx2g -Xms2g
/Elastic/fscrawler/bin/fscrawler.bat --config_dir /Elastic/fscrawler data >> /Elastic/logs/fscrawler.log 2>&1

 if I run fscrawler.bat or fscrawler jobname directly， the result is the same:ERROR StatusLogger Reconfiguration failed: No configuration found for '73d16e93' at 'null' in 'null'

**Comment by ian-cameron** [comment]
Hey, I had the same error message, and the way to get the error to go away is to run the batch file from fscrawler home folder.  For example:
````
C:\temp\fscrawler> .\bin\fscrawler.bat
````
The above ^ works to start  FS Crawler.

But if I try to call it directly from within the bin folder, fscrwaler can't find the logging config:
````
PS C:\temp\fscrawler\bin> .\fscrawler.bat
ERROR StatusLogger Reconfiguration failed: No configuration found for '73d16e93' at 'null' in 'null'
````

So one fix is you can change the file ./bin/fscrawler.bat, line 30 to:
````
REM Define LOG4J2 config file
set JAVA_OPTS=%JAVA_OPTS% -Dlog4j.configurationFile=%FS_HOME%/config/log4j2.xml
````
(previously missing the "%FS_HOME%")

**Comment by dadoonet** [comment]
Amazing ! Would you like to send à PR?

**Comment by dadoonet** [comment]
Regression introduced by #1093

**Comment by lionliujia** [comment]
> Hey, I had the same error message, and the way to get the error to go away is to run the batch file from fscrawler home folder. For example:
> 
> ```
> C:\temp\fscrawler> .\bin\fscrawler.bat
> ```
> 
> The above ^ works to start FS Crawler.
> 
> But if I try to call it directly from within the bin folder, fscrwaler can't find the logging config:
> 
> ```
> PS C:\temp\fscrawler\bin> .\fscrawler.bat
> ERROR StatusLogger Reconfiguration failed: No configuration found for '73d16e93' at 'null' in 'null'
> ```
> 
> So one fix is you can change the file ./bin/fscrawler.bat, line 30 to:
> 
> ```
> REM Define LOG4J2 config file
> set JAVA_OPTS=%JAVA_OPTS% -Dlog4j.configurationFile=%FS_HOME%/config/log4j2.xml
> ```
> 
> (previously missing the "%FS_HOME%")

thanks !  you saved me

**Comment by cprivite** [comment]
Just ran into this today, can confirm the %FS_HOME% addition fixes it.

**Comment by dadoonet** [comment]
Someone would like to contribute a PR?

**Comment by ian-cameron** [comment]
I thought I did a PR for this fix with #1094, but maybe I didn't do it correct?

**Comment by cprivite** [comment]
The code changes listed there look like they'd fix it, but I don't think a new snapshot has been cut that includes them? It's really hard to figure out what's released when we're in perpetual SNAPSHOT version hell.

**Comment by dadoonet** [comment]
Thanks for checking! Sounds like there's an issue at build time. Need to check or at least run  a manual deploy.

Thanks @ian-cameron for the PR. I'm a bit overloaded with the Elastic Community Conference next week and I forgot that you already fixed it. Sorry 😉

**Comment by dadoonet** [comment]
Indeed. The deploy phase is broken. Will try to fix this later today. Thanks all!

**Comment by dadoonet** [comment]
I manually deployed a new version. Could someone try it and tell me if it's fixed?

I still need to check why CI does not deploy it correctly...

**Comment by cprivite** [comment]
Tried the new build today, looks like it fixed the issue.

**Comment by dadoonet** [comment]
Thanks for confirming!
