### ISSUE TITLE
Add a test to detect renamed files

### ISSUE THREAD

**Issue by charbo** [dadoonet/fscrawler#110]
It seems that renaming a file is ignored.
Step to reproduce:
1- indexing a file
2- Search the file: result OK
3- Rename the file
4- Wait for update, Search the file: result KO, the file is'nt found

**Comment by dadoonet** [comment]
Yeah renaming a file does not change its date on the system so as it's older than the last run, it's not taken into account.
If you copy the file and remove the old one, then probably the new copy will be recent.

Or may be using `touch` on the file might work?

**Comment by dadoonet** [comment]
I added a test and it seems to work fine on MacOSX. May be there is an issue with renaming files in other systems?

**Comment by shadiakiki1986** [comment]
Hello. I just faced this issue. Does the test in the commit above include testing that the file is reindexed under the new name? I looked at it and didn't see that it did

**Comment by dadoonet** [comment]
@shadiakiki1986 yes. At least I hope: https://github.com/dadoonet/fscrawler/commit/7495a55cf6bd157da74e6ce30a44893c367d5c40#diff-2029e10eea382c8cc9bd751c9419441aR500
