### ISSUE TITLE
Do a release

### ISSUE THREAD

**Issue by cprivite** [dadoonet/fscrawler#1105]
**Is your feature request related to a problem? Please describe.**
No.

The lack of releases for this project are a problem. It's difficult to know who is on what, compare bugs and features with other users, or get a sense if the project is moving forward, how, and with what cadence. It's also not possible to do CI/CD deployment with the current snapshot based releases due to a lack of tagging.

**Describe the solution you'd like**

My suggestion is to cut a release and start moving to semantic versioning again instead of every development being added to a rolling snapshot. 

**Describe alternatives you've considered**

Use the snapshots from the master branch, which are not ideal and lead to version confusion when comparing configurations with other users.

**Comment by dadoonet** [comment]
I totally agree with you. The thing is that I'd really love to provide [Docker images](https://github.com/dadoonet/fscrawler/pull/820) as part of this release.

Here are the issues/bugs that I'd like to fix before cutting a release:

https://github.com/dadoonet/fscrawler/milestone/24

But I do hear you about that need. I wish that days have more than 24 hours :) 

BTW I'm moving your question to a discussion.
