### ISSUE TITLE
failed to create elasticsearch client on Elasticsearch

### ISSUE THREAD

**Issue by espinosa** [dadoonet/fscrawler#1177]
Bonjour David @dadoonet,
Peux-tu mettre à jour fscrawler sur docker hub avec le dernier commit (188d10d) ?
La dernière version sur docker hub utilise le client es 7.12 et non pas 7.13, d'où l'erreur.
Encore merci pour ton travail !

**Comment by dadoonet** [comment]
Peux-tu partager le message d'erreur complet ? Il ne devrait pas y avoir de problème avec le client 7.12.

**Comment by espinosa** [comment]
Merci pour ta rapide réponse.
J'utilise l'image docker.elastic.co/enterprise-search/enterprise-search:7.13.2 et dadoonet/fscrawler d'il y a 13 jours. Après avoir regardé le code, j'ai supposé que le client 7.12 n'est pas compatible avec le serveur 7.13 car l'exception à l'air de provenir de la fonction checkVersion().

Le message fscrawler est: 
[f.p.e.c.f.c.v.ElasticsearchClientV7] failed to create elasticsearch client on Elasticsearch{nodes=[http://x.x.x.x:9200], index='fs_nas', indexFolder='fs_nas_folder', bulkSize=100, flushInterval=5s, byteSize=10mb, username='elastic', pipeline='null', pathPrefix='null', sslVerification='false'}, disabling crawler...
08:55:37,675 [1;31mFATAL[m [f.p.e.c.f.c.FsCrawlerCli] We can not start Elasticsearch Client. Exiting.
java.net.ConnectException: Timeout connecting to [/x.x.x.x:9200]
	at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:880) ~[elasticsearch-rest-client-7.12.0.jar:7.12.0]

Pas de log trouvé sur le serveur elastic search.

**Comment by dadoonet** [comment]
Le problème est ici : "Timeout connecting to [/x.x.x.x:9200]".

La machine où tourne FSCrawler n'arrive pas à se connecter au noeud Elasticsearch.

Peux-tu lancer depuis la machine où tourne FSCrawler:

```sh
curl x.x.x.x:9200/
```

Est-ce que le serveur est sécurisé ? (login/password)? Est-ce qu'il tourne sur cloud.elastic.co?

Quel est le fichier de configuration exact ?

Peux-tu relancer avec l'option `--trace` STP?
