### ISSUE TITLE
FTP crawler

### ISSUE THREAD

**Issue by helsonxiao** [dadoonet/fscrawler#1184]
**Is your feature request related to a problem? Please describe.**

I'm developing a special service which can not always access server via ssh(server is not mine or for other security reasons).

**Describe the solution you'd like**

I intend to implement two new crawlers(FTP and SMB).
- Hopefully I only need to implement these two classes under `crawler` folder.
- Extends `FsParserAbstract` under `core` folder.
- Some related parameters(username, password, port, ...) should be parsed in `settings`.

I've never used FTP/SMB in java before, so I'm not 100% sure if they could do the same thing. Any other clues will be very helpful to me! Thanks!

**Describe alternatives you've considered**

After checked all related issues, I think mounting them as remote directories would be an alternative?

**Comment by dadoonet** [comment]
Have a look at #147 and #546 

I think I started a branch a long time ago to support FTP but did not succeed as I wanted to make it work.

**Comment by helsonxiao** [comment]
Thanks @dadoonet . Perhaps mounting them as directories is the only way currently. Could you share your ftp branch? Maybe we(and people with same needs) can make it work together.

**Comment by dadoonet** [comment]
> Perhaps mounting them as directories is the only way currently.

Yes. I think so.



> Could you share your ftp branch? Maybe we(and people with same needs) can make it work together.

It's a 5 years old branch which is a way behind the master branch but that could at least give you an idea: https://github.com/dadoonet/fscrawler/tree/ftp

It contains 3 commits:

* https://github.com/dadoonet/fscrawler/commit/69e7fa36b90047dba207e5f89a70e4f241ba2e4e
* https://github.com/dadoonet/fscrawler/commit/a9d35e0310653967c6a5759ddbf075c327fc1235
* https://github.com/dadoonet/fscrawler/commit/0401e71af00c8211ab8d83343b23ccc98fc5bbff

I think that the most important one is the first one. Not sure. Can't recall :(

**Comment by helsonxiao** [comment]
> I think that the most important one is the first one.

Yes, that's the most important one! I'll do the mounting first and then see if it's necessary to get back on this branch.

**Comment by helsonxiao** [comment]
Hi @dadoonet , I've implemented a simple version of FTP crawler. Also, SMB crawler(with several versions) is working in progress. We'll test them in our project and then make at least two PRs.

https://github.com/waterstone-company/fscrawler/commit/8d32259e6c419c8c4af40af326be79e7ad1fcc76

**Comment by helsonxiao** [comment]
I encountered a problem about `pathSeparator` [here](https://github.com/dadoonet/fscrawler/blob/master/core/src/main/java/fr/pilato/elasticsearch/crawler/fs/FsParserAbstract.java#L100) and I think it's not appropriate to let crawler choose separator for server using `OsValidator`(it's a client info). Maybe we should declare separator explicitly. I wrote a function to parse separator from path. Please see this PR. https://github.com/dadoonet/fscrawler/pull/1199

https://github.com/dadoonet/fscrawler/pull/1199/files#diff-27aabc48cd80adbdd85f89c53ff70563163da6ed75cb3b72251179dad706c038R286

Some places where problems could be caused:

1. Virtual path is not computed correctly with backward slash. I believe this will happen on Windows local crawling.
https://github.com/dadoonet/fscrawler/blob/master/framework/src/main/java/fr/pilato/elasticsearch/crawler/fs/framework/FsCrawlerUtil.java#L289

2. Doc id is generated from filename and path, but this way is using crawler's separator, not server's. That means if I switch my crawler from linux to windows, doc id is generated differently.
https://github.com/dadoonet/fscrawler/blob/faf473099b26843e577e2f48c55e390d7ca312a2/core/src/main/java/fr/pilato/elasticsearch/crawler/fs/FsParserAbstract.java#L495

Looking forward to your thoughts! @dadoonet

**Comment by dadoonet** [comment]
This will be fixed by your PR #1203.
