### ISSUE TITLE
Provide arm64 Docker image

### ISSUE THREAD

**Issue by ebekebe** [dadoonet/fscrawler#1232]
I would like to run fscrawler on a Raspberry Pi 4, but it has arm64 architecture. Although the core is written for JVM and should be architecture independent, the produced docker image is not. So it is currently not possible to follow [the instructions for Docker](https://fscrawler.readthedocs.io/en/fscrawler-2.7/installation.html#using-docker) on any platform other than amd64.

I would like to see a multi-architecture Docker build. This can be achieved by incorporating [Docker BuildKit](https://docs.docker.com/buildx/working-with-buildx/#build-multi-platform-images) into the image generation process. Especially arm64 would be important for me and others who want to run it on a rpi.

I checked the [Dockerfile](https://github.com/dadoonet/fscrawler/blob/master/distribution/src/main/docker/Dockerfile) and it uses a base image that is available for arm64. Also, the instructions are all platform independent. So I guess that the Dockerfile can be used as is with BuildKit.

**Comment by dadoonet** [comment]
Would you like to provide à PR for this?

**Comment by ebekebe** [comment]
> Would you like to provide à PR for this?

I would like to help, but I am not familiar with the Java tooling. I haven't found a `docker build` command in the GitHub workflows. I guess that maven is somehow doing the docker build, but this is beyond my expertise.
Could you provide a Dockerfile that builds the whole project inside of the container instead of copying the result to the Dockerfile? I could then test this locally without needing knowledge of the maven build process and would probably be able to create a PR.

**Comment by 24601** [comment]
@ebekebe - I have pushed images to Docker Hub for arm64 (for 2.10-SNAPSHOT):

https://hub.docker.com/repository/docker/basitmustafa/fscrawler

**Comment by dadoonet** [comment]
@24601 Do you think this could be added to the current build?

**Comment by 24601** [comment]
@dadoonet - I am going to try to add the buildx command to compile for arm64 on intel machines (and vice versa) today. I will try to get you a PR today.

**Comment by 24601** [comment]
@dadoonet - I have opened PR #1518 that should satisfy this. It worked when I pushed to my own Docker repo (see above): it build and pushed images for both arches on my M1 MacBook Pro (the examples also run natively now instead of using qemu to run the amd64 images very slowly). 

Hopefully this helps.
