### ISSUE TITLE
Fscrawler version 2.7 install on RHEL8 log files fscrawler.log missing

### ISSUE THREAD

**Issue by rcheatham1** [dadoonet/fscrawler#1235]
> ### Discussed in https://github.com/dadoonet/fscrawler/discussions/1234

<div type='discussions-op-text'>

<sup>Originally posted by **rcheatham1** August 19, 2021</sup>
Hello,

We currently have Fscrawler version 2.7 installed on RHEL8 server.  According to the documentation a fscawler.log file is created when the software gets installed.  I'm  new to the Linux environment but I've search everywhere and the log file doesn't exist. I look in the directory when its installed and I only have a bin and lib directory.  Can someone help.  </div>

**Comment by dadoonet** [comment]
Not when it gets installed but when it runs.
