### ISSUE TITLE
Install fail or first test fail with fscrawler :-(

### ISSUE THREAD

**Issue by danyill** [dadoonet/fscrawler#127]
# What happened and what was expected?

I expected a short indexing run if I created the ```/tmp/es``` temporary folder as per README.md, added one file as per the README.md but all I received was errors which didn't assist. Would appreciate assistance. Perhaps an install section in the README.md? 

Sorry - I'm not terribly familiar with Elasticsearch or fscrawler but wanted to have a bash at a local filesystem searching engine using Elasticsearch. Sorry if this be a newb question.

# Details below:

## OS & Versions

	mulhollandd@alexandria:/media/test/Elasticsearch/fscrawler-2.0.0/bin$ lsb_release -a
	No LSB modules are available.
	Distributor ID: Debian
	Description:    Debian GNU/Linux 8.2 (jessie)
	Release:        8.2
	Codename:       jessie

	mulhollandd@alexandria:/media/test/Elasticsearch/fscrawler-2.0.0/bin$ uname -r
	3.16.0-4-amd64

## Based on this:

* https://discuss.elastic.co/t/announcement-elasticsearch-file-system-crawler-2-0-0-released/33384/2
* https://github.com/dadoonet/fscrawler

## Check version:

	dan@test:/media/test/Elasticsearch$ elasticsearch-2.0.0/bin/elasticsearch -version
	Version: 2.0.0, Build: de54438/2015-10-22T08:09:48Z, JVM: 1.8.0_66-internal

## Create an index

	nano ~/.fscrawler/test.json

## Insert the following

	{
	  "name" : "test"
	}

## Make sure there is a folder there and a few checks

	mkdir -p /tmp/es # in case it needs the folder there
	nano /tmp/es/hi # in case it want's a file, added gibberish
	sudo ufw disable # in case it's a firewall problem

## Try to run fscrawler

	dan@test:/media/test/Elasticsearch/fscrawler-2.0.0/bin$ ./fscrawler 
	18:40:42,465 INFO  [f.p.e.c.f.FsCrawler] No job specified. Here is the list of existing jobs:
	18:40:42,468 INFO  [f.p.e.c.f.FsCrawler] [1] - test
	18:40:42,468 INFO  [f.p.e.c.f.FsCrawler] Choose your job [1-1]...
	1
	18:40:44,352 INFO  [f.p.e.c.f.FsCrawlerImpl] Starting FS crawler
	18:40:44,396 WARN  [f.p.e.c.f.FsCrawlerImpl] failed to create index [test], disabling crawler...
	18:40:44,396 FATAL [f.p.e.c.f.FsCrawler] Fatal error received while running the crawler: []
	18:40:44,397 INFO  [f.p.e.c.f.FsCrawlerImpl] Closing fs crawler

## Run again with debug

	dan@test:/media/test/Elasticsearch/fscrawler-2.0.0/bin$ ./fscrawler --debug
	18:41:09,273 INFO  [f.p.e.c.f.FsCrawler] No job specified. Here is the list of existing jobs:
	18:41:09,276 INFO  [f.p.e.c.f.FsCrawler] [1] - test
	18:41:09,276 INFO  [f.p.e.c.f.FsCrawler] Choose your job [1-1]...
	1
	18:41:10,876 DEBUG [f.p.e.c.f.FsCrawler] Starting job [test]...
	18:41:11,199 INFO  [f.p.e.c.f.FsCrawlerImpl] Starting FS crawler
	18:41:11,207 DEBUG [f.p.e.c.f.c.ElasticsearchClient] create index [test]
	18:41:11,243 WARN  [f.p.e.c.f.FsCrawlerImpl] failed to create index [test], disabling crawler...
	18:41:11,243 FATAL [f.p.e.c.f.FsCrawler] Fatal error received while running the crawler: []
	18:41:11,243 DEBUG [f.p.e.c.f.FsCrawler] error caught
	com.google.api.client.http.HttpResponseException: 
			at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1061) ~[google-http-client-1.20.0.jar:1.20.0]
			at fr.pilato.elasticsearch.crawler.fs.client.ElasticsearchClient.createIndex(ElasticsearchClient.java:96) ~[fscrawler-2.0.0.jar:?]
			at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl.start(FsCrawlerImpl.java:130) ~[fscrawler-2.0.0.jar:?]
			at fr.pilato.elasticsearch.crawler.fs.FsCrawler.main(FsCrawler.java:185) [fscrawler-2.0.0.jar:?]
	18:41:11,250 INFO  [f.p.e.c.f.FsCrawlerImpl] Closing fs crawler

## Run again with trace

	dan@test:/media/test/Elasticsearch/fscrawler-2.0.0/bin$ ./fscrawler --trace
	18:41:42,032 INFO  [f.p.e.c.f.FsCrawler] No job specified. Here is the list of existing jobs:
	18:41:42,035 INFO  [f.p.e.c.f.FsCrawler] [1] - test
	18:41:42,035 INFO  [f.p.e.c.f.FsCrawler] Choose your job [1-1]...
	1
	18:41:43,413 DEBUG [f.p.e.c.f.FsCrawler] Starting job [test]...
	18:41:43,733 TRACE [f.p.e.c.f.FsCrawler] settings used for this crawler: [{
	  "name" : "test",
	  "fs" : {
		"url" : "/tmp/es",
		"update_rate" : "15m",
		"includes" : null,
		"excludes" : null,
		"json_support" : false,
		"filename_as_id" : false,
		"add_filesize" : true,
		"remove_deleted" : true,
		"store_source" : false,
		"indexed_chars" : null
	  },
	  "server" : null,
	  "elasticsearch" : {
		"nodes" : [ {
		  "host" : "127.0.0.1",
		  "port" : 9300
		} ],
		"index" : null,
		"type" : "doc",
		"bulk_size" : 100,
		"flush_interval" : "5s"
	  }
	}]
	18:41:43,734 INFO  [f.p.e.c.f.FsCrawlerImpl] Starting FS crawler
	18:41:43,742 DEBUG [f.p.e.c.f.c.ElasticsearchClient] create index [test]
	18:41:43,779 WARN  [f.p.e.c.f.FsCrawlerImpl] failed to create index [test], disabling crawler...
	18:41:43,780 FATAL [f.p.e.c.f.FsCrawler] Fatal error received while running the crawler: []
	18:41:43,780 DEBUG [f.p.e.c.f.FsCrawler] error caught
	com.google.api.client.http.HttpResponseException: 
			at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1061) ~[google-http-client-1.20.0.jar:1.20.0]
			at fr.pilato.elasticsearch.crawler.fs.client.ElasticsearchClient.createIndex(ElasticsearchClient.java:96) ~[fscrawler-2.0.0.jar:?]
			at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl.start(FsCrawlerImpl.java:130) ~[fscrawler-2.0.0.jar:?]
			at fr.pilato.elasticsearch.crawler.fs.FsCrawler.main(FsCrawler.java:185) [fscrawler-2.0.0.jar:?]
	18:41:43,783 INFO  [f.p.e.c.f.FsCrawlerImpl] Closing fs crawler

## Can't see anything wrong with the Elasticsearch instance which I am running just from the command line

	dan@test:/media/test/Elasticsearch/elasticsearch-2.0.0$ ./bin/elasticsearch
	[2015-11-15 18:22:30,958][INFO ][node                     ] [Spider-Man] version[2.0.0], pid[3455], build[de54438/2015-10-22T08:09:48Z]
	[2015-11-15 18:22:30,959][INFO ][node                     ] [Spider-Man] initializing ...
	[2015-11-15 18:22:31,018][INFO ][plugins                  ] [Spider-Man] loaded [], sites []
	[2015-11-15 18:22:31,090][INFO ][env                      ] [Spider-Man] using [1] data paths, mounts [[/media/test (/dev/mapper/crypt_sdd1)]], net usable_space [2.1tb], net total_space [3.6tb], spins? [possibly], types [btrfs]
	[2015-11-15 18:22:32,610][INFO ][node                     ] [Spider-Man] initialized
	[2015-11-15 18:22:32,610][INFO ][node                     ] [Spider-Man] starting ...
	[2015-11-15 18:22:32,678][INFO ][transport                ] [Spider-Man] publish_address {127.0.0.1:9300}, bound_addresses {127.0.0.1:9300}, {[::1]:9300}
	[2015-11-15 18:22:32,688][INFO ][discovery                ] [Spider-Man] elasticsearch/z0rGM8vVRmCrlXcuQ0k_Kw
	[2015-11-15 18:22:35,739][INFO ][cluster.service          ] [Spider-Man] new_master {Spider-Man}{z0rGM8vVRmCrlXcuQ0k_Kw}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-join(elected_as_master, [0] joins received)
	[2015-11-15 18:22:35,796][INFO ][http                     ] [Spider-Man] publish_address {127.0.0.1:9200}, bound_addresses {127.0.0.1:9200}, {[::1]:9200}
	[2015-11-15 18:22:35,796][INFO ][node                     ] [Spider-Man] started
	[2015-11-15 18:22:35,838][INFO ][gateway                  ] [Spider-Man] recovered [0] indices into cluster_state

**Comment by dadoonet** [comment]
Thank you for this detailled report. Really appreciated. 

Just to make sure: you are running fscrawler and elasticsearch on the same machine, right?

**Comment by danyill** [comment]
Thanks for the quick response - Yes, a headless Debian server. I can attempt to replicate in a vm if it would help, or if you have some diagnostic suggestions.

**Comment by dadoonet** [comment]
No everything looks fine. 

I think I need to add more traces because the logs here don't give enough details.

I'll try to reproduce. In the meantime, instead of manually creating the job, can you run fscrawler anothertest?

It should ask you to create it with a default file. Then run fscrawler again.

**Comment by danyill** [comment]
Tried running again with ```fscrawler anothertest```, same result, an ```HttpResponseException```.

Tried reboot and attempted again as I had installed the Debian package ```openjdk-8-jre-headless``` without a reboot for previous testing, but this made no difference.

**Comment by dadoonet** [comment]
So I tried a manual installation:

* install elasticsearch 2.1.0
* start it `bin/elasticsearch`

```sh
wget https://repo1.maven.org/maven2/fr/pilato/elasticsearch/crawler/fscrawler/2.0.0/fscrawler-2.0.0.zip
unzip fscrawler-2.0.0.zip
```

My `~/.fscrawler/david.json` file contains:

```json
{
  "name" : "david",
  "fs" : {
    "url" : "/Users/dpilato/tmp",
    "update_rate" : "5s",
    "includes" : null,
    "excludes" : null,
    "json_support" : false,
    "filename_as_id" : false,
    "add_filesize" : true,
    "remove_deleted" : true,
    "store_source" : false,
    "indexed_chars" : "0.0"
  },
  "server" : null,
  "elasticsearch" : {
    "nodes" : [ {
      "host" : "127.0.0.1",
      "port" : 9200
    } ],
    "index" : "david",
    "type" : "doc",
    "bulk_size" : 100,
    "flush_interval" : "5s"
  }
}
```

Launching `fscrawler-2.0.0/bin/fscrawler`:

```
17:31:34,927 INFO  [f.p.e.c.f.FsCrawler] No job specified. Here is the list of existing jobs:
17:31:34,933 INFO  [f.p.e.c.f.FsCrawler] [1] - david
17:31:34,934 INFO  [f.p.e.c.f.FsCrawler] Choose your job [1-1]...
1
17:31:43,419 INFO  [f.p.e.c.f.FsCrawlerImpl] Starting FS crawler
17:31:43,787 INFO  [f.p.e.c.f.FsCrawlerImpl] creating fs crawler thread [david] for [/Users/dpilato/tmp] every [5s]
17:31:59,606 INFO  [f.p.e.c.f.FsCrawlerImpl] Closing fs crawler
```

Then, I start searching:

```
curl localhost:9200/david/_search?pretty
```

Gives expected results:

```json
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 5,
    "max_score" : 1.0,
    "hits" : [ ... ]
  }
}
```

So I don't know what is happening for you.
Which JVM are you using?

I'm running on a Mac with:

```sh
 $ java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
```

**Comment by danyill** [comment]
Thank you. I've done some testing on a Debian 8.2 VM. Turns out your json file works nicely, however if I use 
{
  "name" : "test"
}
I get the same error as before. I think this issue may be that the "The most simple crawler" section of README.MD may not be accurate or helpful for the new version. Can you confirm?

**Comment by danyill** [comment]
Thank you David. 

1. Do you have build instructions for fscrawler? I'm trying to get things working and have experienced an interesting range of problems some of which result in no error message. If I work on the basis of the existing version I may report bugs which you have already resolved through your ```NPE``` commit above. 

2. I think there are more ```NPE``` problems and the ```README.MD``` is not presently usable. I'd be happy to have a bash at identifying problems and making suggestions if that would be helpful.

3. Having said all of this, I have been able to beautifully full text search some documents which has made me very happy based on your ```david.json``` above.

**Comment by dadoonet** [comment]
@danyill it's a maven project so you basically just need to run `mvn install`.

**Comment by FredDut** [comment]
Wrong port (9300) in the example?

**Comment by dadoonet** [comment]
@freddut very good catch! Indeed 

Wanna submit a PR?
