### ISSUE TITLE
job reference documentation needs update (fscrawler 2.8)

### ISSUE THREAD

**Issue by dadoonet** [dadoonet/fscrawler#1344]
### Discussed in https://github.com/dadoonet/fscrawler/discussions/1342

<div type='discussions-op-text'>

<sup>Originally posted by **cbb-colab** January  5, 2022</sup>
This is just to improve the documentation:

using fscrawler 2.8 (from docker image: dadoonet/fscrawler:noocr) I created my first job

I took the job description from

https://fscrawler.readthedocs.io/en/latest/admin/fs/index.html

An created my job based on this example.

a)
On running it gave a warning on one setting to be a deprecated setting,.

The offending item for me was
pdf_ocr: false

which I changed then to
ocr.pdf_strategy: no_ocr

as proposed

b)
Also in the config entry
follow_symlink: false

option was missing, which I needed to change and needed to look up the option somewhere else</div>

**Comment by cbb-colab** [comment]
I added my changes to https://github.com/cbb-colab/fscrawler/tree/origin/improve-documentaion (index.rst, local-fs.rst
[changes.zip](https://github.com/dadoonet/fscrawler/files/7817938/changes.zip)
)

**Comment by dadoonet** [comment]
Merged. Thanks!
