### ISSUE TITLE
support index client hostname

### ISSUE THREAD

**Issue by boliza** [dadoonet/fscrawler#135]
support index client hostname

**Comment by dadoonet** [comment]
What do you mean? Could you explain a bit more?

**Comment by boliza** [comment]
Sorry . I think this a tool to index files(just files) of a node.

**Comment by dadoonet** [comment]
Yes but I still curious about what you are looking for.

**Comment by boliza** [comment]
I want statistics the file size、create_date of sstables (I manager a few C* Cluster).so I can force compaction the sstables which is very large
