### ISSUE TITLE
Tesseract does not work properly in ocr enable. 

### ISSUE THREAD

**Issue by ywjung** [dadoonet/fscrawler#1357]
**Describe the bug**

Tesseract does not work properly in ocr enable. 
The reason is in TikaInstance.java ocrActivated = fs.getOcr().isEnabled(); there is a problem with
It operates in the order of initTika > initContext > initParser, 
but the ocrActivated check is in initParser, 
so it is always false in initContext. 

thus
```java
     private static void initTika(Fs fs) {
        ocrActivated = fs.getOcr().isEnabled();  <- insert
         initContext(fs);
         initParser(fs);
     }

    private static void initParser(Fs fs) {
        if (parser == null) {
            PDFParser pdfParser = new PDFParser();
            DefaultParser defaultParser;
            TesseractOCRParser ocrParser;

            // To solve https://issues.apache.org/jira/browse/TIKA-3364
            // PDF content might be extracted multiple times.
            pdfParser.getPDFParserConfig().setExtractBookmarksText(false);

//            ocrActivated = fs.getOcr().isEnabled();   <- delete
```

correction is required as

If I'm misunderstanding something, ask for clarification.

Additionally, in Korea, language recognition
  In the initContext method of TikaInstance.java
  config.setLanguage(fs.getOcr().getLanguage()); 
below
config.setPreserveInterwordSpacing(true); 
setting is required as If possible, ask to enable this in settings.

**Versions:**
 - OS: windows 11, ubuntu
 - test Version : 2.7 ~ 2.10

**Attachment**

[modified TikaInstance.txt](https://github.com/dadoonet/fscrawler/files/7876738/modified.TikaInstance.txt)

**Comment by dadoonet** [comment]
Thanks for reporting. Would you like to contribute your patch as a pull request so I can easily evaluate this?

**Comment by ywjung** [comment]
Requested as a pull request.!!(#1358)
