### ISSUE TITLE
Feature Request: Exclude and Include based on directory or full path name/URL

### ISSUE THREAD

**Issue by danyill** [dadoonet/fscrawler#139]
This is a feature request:

A use case I care about is indexing a file system where I am using BTRFS as the filesystem and I am regularly taking snapshots, using [snapper](http://snapper.io/). This creates a problem when using fscrawler:

* When taking a BTRFS snapshots of a folder ```/media/x```, snapper creates a folder ```/media/x/.snapshots```.
* This will then contain a number of folders, depending on the number of snapshots and retention policy which are read-only copies of the full filesystem going back e.g. 1 hour, 1 day, 1 month etc. etc.
* I need to be able to index the parent folder ```/media/x``` without indexing the ```/media/x/.snapshots``` folder.

Obviously something can be done with filesystem permissions, but it would be ideal if the includes or excludes filters in the ```~.fscrawler/<<job_name>>.json``` could be regular expressions based on the full path name.

**Comment by dadoonet** [comment]
+1. I wonder if it's a feature request or a bug though :)

**Comment by dadoonet** [comment]
Fixed! Thanks for raising it!
