### ISSUE TITLE
change in generateIdFromFilename from 2.6 to 2.10 effecting generated document IDs

### ISSUE THREAD

**Issue by jackpenman123** [dadoonet/fscrawler#1394]
on versions of crawler before 2.7 the method generateIdFromFilename contained the following code: 

```java
    private String generateIdFromFilename(String filename, String filepath) throws NoSuchAlgorithmException {
        return fsSettings.getFs().isFilenameAsId() ? filename : SignTool.sign((new File(filepath, filename)).toString());
    }
```

while in newer versions this method contains the following code which appears to escape slashes found in the url 

```java
    private String generateIdFromFilename(String filename, String filepath) throws NoSuchAlgorithmException {
        String filepathForId = filepath.replace("\\", "/");
        String filenameForId = filename.replace("\\", "").replace("/", "");
        String idSource = filepathForId.endsWith("/") ? filepathForId.concat(filenameForId) : filepathForId.concat("/").concat(filenameForId);
        return fsSettings.getFs().isFilenameAsId() ? filename : SignTool.sign(idSource);
    }
``` 

We recently had to upgrade our version of crawler due to the log4j security issue and have noticed that crawler seems to have inserted duplicated files into elastic because it has created new IDs for the same files 

we are indexing on network drives where the URL is preceded with \\\\ eg. \\\\network\\folder1\\folder2

therefore the old code would have created an id using the URL \\\\\\network\\\\folder1\\\\folder2 while the new code escapes the slashes and generates the IDs using the path of: \\\\network\folder1\folder2 

We are wondering why this change was made and if this change has effected anyone else.

**Job Settings**

```
name: "XXXXXX"
fs:
url: "\\\\\\\\XXXXX\\\\XXX\\\\XXXX\\\\XXXXX\\\\XXXXXXX\\\\"
continueFromProgressFile: false
update_rate: "1m"
json_support: false
filename_as_id: false
add_filesize: true
remove_deleted: true
add_as_inner_object: false
store_source: false
index_content: true
indexed_chars: "1"
attributes_support: true
raw_metadata: true
xml_support: false
index_folders: true
lang_detect: false
continue_on_error: true
ocr:
language: "eng"
enabled: true
pdf_strategy: "ocr_and_text"
follow_symlinks: false
elasticsearch:
nodes:
- url: "XXXX"
index: "XXXXXXX"
bulk_size: 10000
flush_interval: "5s"
byte_size: "10mb"
ssl_verification: false
pipeline: "XXXXXXXXX"
username: "XXXX"
password: "XXXXXX"
```

**Expected behavior**

We expected the new version to simply update the existing files in elastic and not duplicate them 

**Versions:**
 - OS: windows 10
 - Version 2.10

**Comment by helsonxiao** [comment]
This change was brought in by https://github.com/dadoonet/fscrawler/pull/1203/files#diff-06eddfd8341c0ac07fe187d2533a5e6342d072014470f96118b9092919568ddfL495. It intends to reslove the inconsistent id between different fscrawler servers. Let me make more explanations.

Here's the old function.
```
private String generateIdFromFilename(String filename, String filepath) throws NoSuchAlgorithmException {
    return fsSettings.getFs().isFilenameAsId() ? filename : SignTool.sign((new File(filepath, filename)).toString());
}
```

`(new File(filepath, filename)).toString()` generates a source depends on server OS. That means if we have fscrawlers running on Windows and Linux, the same file in the same place will have two different ids. It's not convenient to deploy a same version fscrawler on a different OS, so I modified the method.

I think you can run a [restart job](https://fscrawler.readthedocs.io/en/fscrawler-2.9/admin/cli-options.html#restart) for the upgrade. Also we'd better to provide an option for the old logic in case someone use the old id as a db column.

**Comment by jackpenman123** [comment]
Just to confirm then, it was this change that caused our issue with the new IDs being made then?

**Comment by helsonxiao** [comment]
Yes. This change is a bug fix but it's also a breaking change. I think we should do something then. @dadoonet

**Comment by jackpenman123** [comment]
Ok thank you, we will just run a restart then to update the IDs

**Comment by dadoonet** [comment]
Yeah this has changed as @helsonxiao explained.
I don't really think we should implement something yet to upgrade from a 2.6 to 2.10 version. I hope that a very few number of people are using this old version so it might not worth it.

WDYT?

I'm closing this but I'm open to discussion (and PR if needed 😄)
