### ISSUE TITLE
OCR Support

### ISSUE THREAD

**Issue by sclausen** [dadoonet/fscrawler#140]
It would be a really nice feature, if scanned PDF documents would be parsed by an OCR software. https://wiki.apache.org/tika/TikaOCR

**Comment by dadoonet** [comment]
If I'm not mistaken (but never found time to run a test), as soon as Tesseract is installed, Tika should be able to use it out of the box right?

Did you try it? Do you think there is something we should change in FSCrawler to support it?
I think that we should probably add a new settings section which could help setting `org/apache/tika/parser/ocr/TesseractOCRConfig.properties` if needed to be able to set:

Tesseract installation path = ""
* Language dictionary = "eng"
* Page Segmentation Mode = "1"
* Minmum file size = 0
* Maximum file size = 2147483647
* Timeout = 120

As explained in the page you linked.

**Comment by Jdecaudin** [comment]
It works out of the box. Tested with : 
 * Ubuntu 14.04
 * Elasticsearch 2.4
 * fscrawler 2.1
 * tesseract-ocr

**Comment by dadoonet** [comment]
@Jdecaudin Awesome news! Would you like to send a documentation PR which explains some basic things to make that work?

Thanks a lot for your feedback!
