### ISSUE TITLE
No supported fscrawler version for ES8.1.1 Workplace Search

### ISSUE THREAD

**Issue by zydisney** [dadoonet/fscrawler#1430]
I just found the workplace search here [fscrawler/contrib/docker-compose-it/](fscrawler/contrib/docker-compose-it/) and follow the `docker-compose up` setps to work it out. I was tring to test it with fscrawler release versions, but it seems no supported fscrawler that work for ES8.1.1. Is there is a fscrawler version in docker, or any config to be modified to make it work?

**Comment by dadoonet** [comment]
2.10-SNAPSHOT supports it.
You could try it.

Have a look at https://fscrawler.readthedocs.io/en/latest/

Take the latest build from: https://s01.oss.sonatype.org/content/repositories/snapshots/fr/pilato/elasticsearch/crawler/fscrawler-distribution/2.10-SNAPSHOT/
