### ISSUE TITLE
stats.json and status.json

### ISSUE THREAD

**Issue by aldav** [dadoonet/fscrawler#145]
I run fscrawler in debug mode - seems everything is going OK but I don't see changes in status.json and it has not created stats.json at all.
As it said "It means that if you stop the job at some point, FS crawler will restart it from where it stops."
so I suppose something should be changed constantly.

could you help me find what's wrong?

**Comment by dadoonet** [comment]
Indeed `_stats.json` is not generated. See #128.

What are the debug traces you are seeing?

FSCrawler is by default running every 15 minutes so it should update `_status` file only after a new run.
Are you using default values?

**Comment by dadoonet** [comment]
I'm closing the issue for now but feel free to reopen if you still have troubles.

Thanks for reporting!
