### ISSUE TITLE
Instructions for docker-compose contrib are out of date

### ISSUE THREAD

**Issue by deg** [dadoonet/fscrawler#1465]
The instructions in https://fscrawler.readthedocs.io/en/latest/user/tips.html | `Using docker-compose` seem to be out-of-date. I tried following the instructions there to "setup a node ElasticSearch cluster, a copy of Kibana for searching and FSCrawler as containers".

They suggest launching docker-compse from the contrib directory. But it is no longer there. Instead, there are four sub-directories, each with a different setup. 

None of the four  options match the documentation; docker-compose-example does not include Kibana, and the other three do not include FSCrawler.

Is there up-to-date documentation somewhere that gives an easy recipe to try out ElasticSearch+Kibana+FSCrawler?

**Comment by dadoonet** [comment]
That's very true. Let me try to see if I can come with something.

**Comment by dadoonet** [comment]
@deg Could you please check if https://github.com/dadoonet/fscrawler/pull/1466 is working for you?

**Comment by deg** [comment]
I'm not sure.  I can't test fully; I'm completely new to most of these tools.
But, some good and some bad that I can see:
- You added two new configurations, with no changes to the documentation, so I wasn't sure what I needed to do.
- Looking at the yml files, it looked like `docker-compose-example-elasticsearch` was the one I wanted. (The other had "enterprisesearch". I don't know what that is yet, but the name sounds like it is a more complex config.  So, I did

```
cd contrib/docker-compose-example-elasticsearch
# edit line 164 of the yml to point to my docs
docker-compose up -d
```

- Good news: three docker spun up. Two reported `(healthy)` and the third (fscrawler) looked fine too
- Good news: I was able to login to localhost:5601 and login with elastic/changeme
- Bad news: In prior configs, localhost:9200 gave me an elasticsearch config page. Now, it didn't. Looking at the diffs of your commit, I realized that you were now using https. So, I tried that, but chrome gave a `NET::ERR_CERT_INVALID` and would not let me connect.

I don't know enough yet to test further

**Comment by deg** [comment]
Oh, and fwiw, the log file is giving a similar warning:

```
elasticsearch_1  | {"@timestamp":"2022-07-25T18:08:15.354Z", "log.level": "WARN", "message":"http client did not trust this server's certificate, closing connection Netty4HttpChannel{localAddress=/172.30.0.3:9200, remoteAddress=/172.30.0.1:56750}", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[elasticsearch][transport_worker][T#2]","log.logger":"org.elasticsearch.xpack.security.transport.netty4.SecurityNetty4HttpServerTransport","elasticsearch.cluster.uuid":"y7tThfRASl6pHTIyxM_iTg","elasticsearch.node.id":"9hSYd9r3R_atnyD1-GGPfw","elasticsearch.node.name":"elasticsearch","elasticsearch.cluster.name":"docker-cluster"}
```

**Comment by deg** [comment]
And, it looks like certificates do exist:

```
$ docker exec -it fscrawler_elasticsearch_1 /bin/sh
sh-5.0$ cd /usr/share/elasticsearch/config/certs/
sh-5.0$ ls -lR
.:
total 20
drwxr-x--- 2 root root 4096 Jul 24 18:53 ca
-rw-r----- 1 root root 2519 Jul 24 18:53 ca.zip
-rw-r----- 1 root root 2652 Jul 24 18:53 certs.zip
drwxr-x--- 2 root root 4096 Jul 24 18:53 elasticsearch
-rw-r----- 1 root root  116 Jul 25 18:07 instances.yml

./ca:
total 8
-rw-r----- 1 root root 1200 Jul 24 18:53 ca.crt
-rw-r----- 1 root root 1675 Jul 24 18:53 ca.key

./elasticsearch:
total 8
-rw-r----- 1 root root 1212 Jul 24 18:53 elasticsearch.crt
-rw-r----- 1 root root 1679 Jul 24 18:53 elasticsearch.key
sh-5.0$
```

**Comment by dadoonet** [comment]
@deg I updated the PR.

I'm going to merge it anytime soon as it works very well on my machine ;) 

Indeed I created 2 examples:

* `docker-compose-example-elasticsearch` is for Elasticsearch (starting Kibana, FSCrawler in watch mode)
* `docker-compose-example-workplace` is for Workplace Search (starting Enterprise Search, Elasticsearch, Kibana, an HTTPD service and FSCrawler which run once and exit)

About the errors you are seeing, could you first run:

```sh
docker-compose down -v
```

To make sure it removes the docker volumes before starting. And then launch:

```sh
docker-compose up
```

**Comment by deg** [comment]
You are right; I forgot to add "-v" to my `docker-compose down` yesterday.  (It might be a good idea to add a line or two of shutdown instructions in the doc).

Today, I tried again with your latest commits and after cleaning out the volumes.  This fixed the error messages in the logs, but chrome still gave the privacy warning when I browsed to https://localhost:9200.

I was able to bludgeon around the warning with the Chrome "thisisunsafe" hack. With this, I was able to see the ElasticSearch status page.

At this point, I was still concerned but hoped that this was just Chrome caching something from yesterday.

Alas, no. I then tested in Safari too (a very clean env, since I basically never use Safari).
Safari gave the privacy warning too.  Viewing the certificate, it showed `"elasticsearch" certificate is not standards compliant`.

I don't know if this is something you can fix in your .yml, or if it is a deeper conflict between ElasticSearch and the latest browser security checks, or an unavoidable consequence of HTTPS on localhost. But I think it does need either a fix or a warning/workaround in the doc.

**Comment by dadoonet** [comment]
> Today, I tried again with your latest commits and after cleaning out the volumes. This fixed the error messages in the logs, but chrome still gave the privacy warning when I browsed to https://localhost:9200/.

I think that's expected as it's a self-signed certificate.

If you want to curl this endpoint for example, you need to use the `--insecure` option.
That's also why I'm using `elasticsearch.ssl_verification: false` in the job settings.

Of course, for production use, you would need a proper certificate.

Note that you should open Elasticsearch from a browser but Kibana.

**Comment by deg** [comment]
Gotcha, thanks.  (I have very little experience with ElasticSearch and none with Kibana or Fscrawler; I'm installing this to play and learn).

Anyway, thank you for your amazingly fast response time. If the whole community is like you, this learning experience is going to be a pleasure!
