### ISSUE TITLE
Ability to lookup files over ftp

### ISSUE THREAD

**Issue by mdimranullah** [dadoonet/fscrawler#147]
It would be nice if we are able to lookup files over ftp. Is this something that is already existing or something that should be as an enhancement?

```
"server" : {
    "hostname" : "ftp.abc.xyz",
    "port" : 21,
    "username":abc,
    "password":xyz,
    "protocol" : "ftp"
  }
```

**Comment by dadoonet** [comment]
I started some work on that but I prefer waiting for #367 first.
