### ISSUE TITLE
Moving files around the indexed directory deletes them without updating their new location (Windows)

### ISSUE THREAD

**Issue by petosorus** [dadoonet/fscrawler#148]
Hi!
I started playing with fscrawler four days ago, and noted that if I cut and paste a file within the indexed directory, it gets removed from the index, but it's not readded at its new location.

Accordind to [#60](https://github.com/dadoonet/fscrawler/issues/60), it is because fscrawler relies on the last-update date of the file, so the program works.

I would like to change this to add the file again to the index after having moving the file. I'm willing to make a pull request if I can manage to do this, but I don't really know how yet.
Do you have an idea of how to do it, and pointers as to where to look in fscrawler for this?

**Comment by dadoonet** [comment]
I believe it's the same issue as #136, right?

**Comment by petosorus** [comment]
Yes it is.

**Comment by dadoonet** [comment]
So I'm closing yours as duplicate.

Thanks for your answer!
