### ISSUE TITLE
FsCrawler.main() polls isClosed() without delay

### ISSUE THREAD

**Issue by sgoeschl** [dadoonet/fscrawler#149]
Had my first look at the project and was puzzled why it needs 100% CPU time :-)

```Java
// We just have to wait until the process is stopped
while (!fsCrawler.isClosed()) {
    // We wait...
}
```

**Comment by dadoonet** [comment]
Indeed. That's so stupid! :)

**Comment by sgoeschl** [comment]
Created a PR since it was easy to fix :-)

**Comment by dadoonet** [comment]
Yeah. Saw it and really appreciated!
AFK at this moment but I'll most likely merge it tomorrow.
