### ISSUE TITLE
Does it make sense to add the owner & group of a file?

### ISSUE THREAD

**Issue by sgoeschl** [dadoonet/fscrawler#151]
Currently having a look how to tailor the code to my needs :-)

Does it make sense to extract the file owner & group from a file and store it in ES - having said that

* group will not work on Windows
* owner/group will not work from SFTP

Thanks in advance

Siegfried Goeschl

**Comment by dadoonet** [comment]
It does IMO.

Should be optional though (disabled by default?).

**Comment by sgoeschl** [comment]
Another high-level question - where to place it

* Extend fr.pilato.elasticsearch.crawler.fs.meta.doc.File to add "owner" & "group"
* Add a new fr.pilato.elasticsearch.crawler.fs.meta.doc.Attributes

Thanks in advance

Siegfried Goeschl

**Comment by dadoonet** [comment]
I'd probably do the later

**Comment by sgoeschl** [comment]
Created https://github.com/dadoonet/fscrawler/pull/152
