### ISSUE TITLE
Index mapping shown in README.md is invalid

### ISSUE THREAD

**Issue by sgoeschl** [dadoonet/fscrawler#153]
I think the given example in "README.md" is not valid, e.g. the snippet

```
"file" : {
    "properties" : {
      "content_type" : {
          "type" : "string",
          "analyzer" : "not_analyzed",
          "store" : "yes"
      },
```

references an analyser with the name "not_analyzed". The intention was probably the following

```
"index" : "not_analyzed"
```

Currently the following error message is shown

```
{
   "error": {
      "root_cause": [
         {
            "type": "mapper_parsing_exception",
            "reason": "analyzer [not_analyzed] not found for field [content_type]"
         }
      ],
      "type": "mapper_parsing_exception",
      "reason": "analyzer [not_analyzed] not found for field [content_type]"
   },
   "status": 400
}
```

**Comment by sgoeschl** [comment]
I assume that the example uses Kibana - would it be okay to use curl instead?

**Comment by dadoonet** [comment]
Indeed.
That being said I was also thinking of updating to Elasticsearch 5.0. So using type keyword instead.
May be I should call Elasticsearch when fscrawler starts and use the right mapping depending on the version.

**Comment by sgoeschl** [comment]
Created https://github.com/dadoonet/fscrawler/pull/154

**Comment by sgoeschl** [comment]
What about

* asking ES to get the major version 
* load the JSON from file instead of creating it

You could have

```
.
|-- conf
|   |-- index
|   |   |-- 2
|   |   |   `-- index.json
|   |   |-- 5
|   |   |   `-- index.json
```

That would also receive a lot of pain when playing with custom mappings

**Comment by dadoonet** [comment]
Works for me

**Comment by sgoeschl** [comment]
One more idea - you could use the "job_name" to pick up "conf/index/X/job_name.json" and if it is not found fall back to "conf/index/X/_mapping.json". That would allow to wire the correct index mapping with jobs assuming that they use a custom mapping.
