### ISSUE TITLE
Fscrawler using wrong endpoint

### ISSUE THREAD

**Issue by C-monC** [dadoonet/fscrawler#1559]
Hi,

I am using the the latest docker image of fscrawler. The default configuration.

Reproduce:
Insert a document with devtools or some other thing with an id of 5104. 
Run fscrawler with random file `curl -F "file=@test.txt" -F "index=documents" -F "id=5104" "http://127.0.0.1:8080/fscrawler/_document"`
``` gives the response:
{
  "ok" : true,
  "filename" : "test.txt",
  "url" : "http://elasticsearch:9200/documents/_doc/5104",
  "doc" : {
    "content" : "This is my sdfghsdfksdjkbvjktext\n\n",
    "meta" : { },
    "file" : {
      "extension" : "txt",
      "content_type" : "text/plain; charset=ISO-8859-1",
      "indexing_date" : "2022-12-06T10:18:22.968+00:00",
      "filename" : "test.txt",
      "indexed_chars" : 1000000
    },
    "path" : {
      "virtual" : "test.txt",
      "real" : "test.txt"
    }
  }
}
```
http://elasticsearch:9200/documents/_doc/5104 will create a new document everytime. I can confirm this is the case by getting doc 5104.

Is there anyway to not insert a new document everytime -> I need to change that url to http://elasticsearch:9200/documents/_update/5104.

Is there a reason upsert is not the default behaviour?
Thanks.

**Comment by C-monC** [comment]
I would like to upsert/merge. I use logstash to insert certain metadata collected from relational db's and then fscrawler for metadata/content. 
The document could exist before hand.

**Comment by C-monC** [comment]
The elasticsearch document can be modified by other services before or/and after fscrawler inserts the content (The document could be flagged for ocr-ing or be a pdf form that needs to be filled in by a human).

I could use logstash but by keeping them separate updates to documents that don't involve the content are lightweight i.e. changing the document's last edited date.

**Comment by dadoonet** [comment]
> Is there a reason upsert is not the default behaviour?

To answer this question (and the title of your issue), I don't consider this as a bug but more a feature request.
Using the default behavior of Elasticsearch is the way to go IMO.
It avoids unnecessary "lookups" on Elasticsearch side when doing upserts. 

The way that use case has been implemented so far is by providing the other elements to be merged to FSCrawler instead.

Note that the [Update API](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html) does not support ingest pipelines.

**Comment by C-monC** [comment]
That would be great, thanks. I have never written Java besides an android app a few years ago.

I've cloned the repo already and started reading through the codebase. 
The DocumentApi.java has FsCrawlerDocumentService could you point out where void index() is actually implemented? I mean where the api request is made and the reponse is returned from elastic.

**Comment by dadoonet** [comment]
So you need to add a new `ElasticsearchUpdateOperation`, similar to the [ElasticsearchIndexOperation](https://github.com/dadoonet/fscrawler/blob/master/elasticsearch-client/src/main/java/fr/pilato/elasticsearch/crawler/fs/client/ElasticsearchIndexOperation.java).

Also modify this: https://github.com/dadoonet/fscrawler/blob/master/elasticsearch-client/src/main/java/fr/pilato/elasticsearch/crawler/fs/client/ElasticsearchEngine.java#L39-L87

Add the new option in https://github.com/dadoonet/fscrawler/blob/master/settings/src/main/java/fr/pilato/elasticsearch/crawler/fs/settings/Elasticsearch.java

And document it here: https://github.com/dadoonet/fscrawler/blob/master/docs/source/admin/fs/elasticsearch.rst

That'd be a good start. Then we can also talk later about unit tests and integration tests.

**Comment by C-monC** [comment]
I got pretty far but I'm stuck and found a workaround (using Tika directly).

On this [line](https://github.com/dadoonet/fscrawler/blob/master/elasticsearch-client/src/main/java/fr/pilato/elasticsearch/crawler/fs/client/ElasticsearchEngine.java#L83) the ndjson passed to the bulk function is `"{"update":{"_index":"documents","_id":"5104"}}"` but I get the error `Error while running POST http://127.0.0.1:9200/_bulk: {"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: no requests added;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: no requests added;"},"status":400}`.

Thanks for your help and I appreciate the speedy replies

**Comment by C-monC** [comment]
I got pretty far but I'm stuck and found a workaround (using Tika directly).

On this [line](https://github.com/dadoonet/fscrawler/blob/master/elasticsearch-client/src/main/java/fr/pilato/elasticsearch/crawler/fs/client/ElasticsearchEngine.java#L83) the ndjson passed to the bulk function is `"{"update":{"_index":"documents","_id":"5104"}}"` but I get the error `Error while running POST http://127.0.0.1:9200/_bulk: {"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: no requests added;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: no requests added;"},"status":400}`.

Thanks for your help and I appreciate the speedy replies

**Comment by dadoonet** [comment]
Could you share your branch? Even incomplete? That might be a good start for me to implement this.

**Comment by C-monC** [comment]
Sure, I've forked to https://github.com/C-monC/fscrawler and the branch is update_index.

I've set the default value of use_update_api to True just for debugging.
