### ISSUE TITLE
Add Gitpod to help developers to contribute

### ISSUE THREAD

**Issue by dadoonet** [dadoonet/fscrawler#1591]
See https://www.gitpod.io/

Two files to add:

* `.gitpod.dockerfile`
* `.gitpod.yml`

See an example at https://github.com/k8s-operator-workshop/hello-world-from-quarkus-solution

**Comment by davidaparicio** [comment]
Great idea! If you want, I can made a PR about these 2 Gitpod files.
PS: Thx a lot for your great talk today, at the SnowCamp 2023 🥇

**Comment by dadoonet** [comment]
> Great idea! If you want, I can made a PR about these 2 Gitpod files.
> PS: Thx a lot for your great talk today, at the SnowCamp 2023 🥇

Thanks! That'd be lovely!

**Comment by davidaparicio** [comment]
It's ready (currently with default dockerfile & gitpod values, cf [Java for Gitpod doc](https://www.gitpod.io/docs/introduction/languages/java)).
It means a ```openjdk 11.0.17 2022-10-18 LTS```
If I'm not wrong, no port opening needed, and specific packages ;)

You can give a try with this link: https://gitpod.io/#/https://github.com/davidaparicio/fscrawler/tree/gitpod

Let's me know your thoughts and your improvements 

PS: Instead the extension "redhat.java", I used the Java VS Code pack :)
![Screenshot 2023-01-28 at 13 09 24](https://user-images.githubusercontent.com/809982/215265702-d214851e-ba1c-47a1-86d8-32826e157e73.jpg)

Some logs, these commands are run during the Gitpod workspace launch:
```
gitpod /workspace/fscrawler (gitpod) $  HISTFILE=/workspace/.gitpod/cmd-0 history -r; {
> mvn clean package -DskipTests
> } && {
> echo "FSCrawler documentation available here:"
> echo "https://fscrawler.readthedocs.io/en/latest/dev/build.html"
> echo "Gitpod ready, happy coding !"
> 
> }
Picked up JAVA_TOOL_OPTIONS:  -Xmx3489m
[INFO] Scanning for projects...
```

mvn package took 5min on Gitpod (full)

If I skip tests, the deployment took 03:44 min 👍 
```
[INFO] --- maven-resources-plugin:3.3.0:copy-resources (copy-resources) @ fscrawler-contrib ---
[INFO] Copying 5 resources
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for FSCrawler 2.10-SNAPSHOT:
[INFO] 
[INFO] FSCrawler .......................................... SUCCESS [  0.790 s]
[INFO] FSCrawler Test Framework ........................... SUCCESS [ 21.946 s]
[INFO] FSCrawler Framework ................................ SUCCESS [  6.355 s]
[INFO] FSCrawler Settings ................................. SUCCESS [  1.213 s]
[INFO] FSCrawler Test Documents ........................... SUCCESS [  0.260 s]
[INFO] FSCrawler Beans .................................... SUCCESS [  0.329 s]
[INFO] FSCrawler 3rd Party libraries ...................... SUCCESS [  0.002 s]
[INFO] FSCrawler Workplace Search Client .................. SUCCESS [  6.288 s]
[INFO] FSCrawler Elasticsearch Client ..................... SUCCESS [  6.108 s]
[INFO] FSCrawler Tika ..................................... SUCCESS [ 24.686 s]
[INFO] FSCrawler Crawlers ................................. SUCCESS [  0.011 s]
[INFO] FSCrawler Abstract Crawler ......................... SUCCESS [  0.294 s]
[INFO] FSCrawler Crawlers: FS ............................. SUCCESS [  0.405 s]
[INFO] FSCrawler Crawlers: FTP ............................ SUCCESS [  0.806 s]
[INFO] FSCrawler Crawlers: SSH ............................ SUCCESS [  0.586 s]
[INFO] FSCrawler Core ..................................... SUCCESS [  2.820 s]
[INFO] FSCrawler Rest Server .............................. SUCCESS [  1.594 s]
[INFO] FSCrawler Integration Tests ........................ SUCCESS [  4.306 s]
[INFO] FSCrawler Cli ...................................... SUCCESS [  1.699 s]
[INFO] FSCrawler ZIP Distribution ......................... SUCCESS [02:21 min]
[INFO] FSCrawler Documentation ............................ SUCCESS [  0.017 s]
[INFO] FSCrawler Contribution Examples .................... SUCCESS [  0.056 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:44 min
[INFO] Finished at: 2023-01-28T12:25:48Z
[INFO] ------------------------------------------------------------------------
FSCrawler documentation available here:
https://fscrawler.readthedocs.io/en/latest/dev/build.html
Gitpod ready, happy coding !
gitpod /workspace/fscrawler (gitpod) $ 
```

For info
```
gitpod /workspace/fscrawler (gitpod) $ java --version
Picked up JAVA_TOOL_OPTIONS:  -Xmx3489m
openjdk 11.0.17 2022-10-18 LTS
OpenJDK Runtime Environment Zulu11.60+19-CA (build 11.0.17+8-LTS)
OpenJDK 64-Bit Server VM Zulu11.60+19-CA (build 11.0.17+8-LTS, mixed mode)
```

**Comment by davidaparicio** [comment]
I started to review optimizations like Maven caching
https://www.gitpod.io/docs/introduction/languages/java#caching-maven-dependencies

More information/inputs are available here (prebuilds vs Docker image):
https://www.gitpod.io/docs/configure/projects/prebuilds
https://www.gitpod.io/docs/configure/workspaces/workspace-image

After reading them, I understand Docker is not the only one solution, and not totally the best/optimized one. 
We must give a try to see if pre-builds can answer our needs :)

But, in order to gain these pre-builds ready, Gitpod requires a Team (link to this repository).
![Screenshot 2023-01-30 at 08 49 26](https://user-images.githubusercontent.com/809982/215421243-4c9a1ce7-8ce9-4649-9900-cce1ffc0d4a7.jpg)
![Screenshot 2023-01-30 at 09 03 47](https://user-images.githubusercontent.com/809982/215421289-4dd3843a-22e9-4fee-8629-249753c38fff.jpg)

The result:
![Screenshot 2023-01-30 at 09 04 36](https://user-images.githubusercontent.com/809982/215421323-cbf7ab73-ebf2-42ac-b8ae-6b4d6af34b12.jpg)

Maybe @dadoonet you can apply to: https://www.gitpod.io/for/opensource :)

**Comment by dadoonet** [comment]
> Maybe @dadoonet you can apply to: https://www.gitpod.io/for/opensource :)

I did last week! Just at the end of the workshop at SnowCamp! I'm waiting for their answer 😊

**Comment by Siddhant-K-code** [comment]
👋🏽 from Gitpod 😄 

> >Maybe @dadoonet you can apply to: https://www.gitpod.io/for/opensource :)
>
> I did last week! Just at the end of the workshop at SnowCamp! I'm waiting for their answer

Just sent you an email. Welcome to the Gitpod for Open Source Plan 🥳 

_(sorry for the delays)_

**Comment by davidaparicio** [comment]
When we tried a ```mvn verify```, I always faced this issue :/

```
[+] Running 8/9
 ⠿ Network fscrawler_default                Created                                                                                              0.1s
 ⠿ Volume "fscrawler_enterprisesearchdata"  Created                                                                                              0.0s
 ⠿ Volume "fscrawler_esdata"                Created                                                                                              0.0s
 ⠿ Volume "fscrawler_kibanadata"            Created                                                                                              0.0s
 ⠿ Volume "fscrawler_certs"                 Created                                                                                              0.0s
 ⠿ Container fscrawler-setup-1              Healthy                                                                                              7.8s
 ⠿ Container fscrawler-elasticsearch-1      Starting                                                                                             8.7s
 ⠿ Container fscrawler-kibana-1             Created                                                                                              0.0s
 ⠿ Container fscrawler-enterprisesearch-1   Created                                                                                              0.0s
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting rlimits for ready process: error setting rlimit type 8: operation not permitted: unknown
```

**Comment by dadoonet** [comment]
Closed with #1598.

**Comment by davidaparicio** [comment]
Everything is working well about this subject?

**Comment by davidaparicio** [comment]
> 👋🏽 from Gitpod 😄
> 
> > > Maybe @dadoonet you can apply to: https://www.gitpod.io/for/opensource :)
> > 
> > 
> > I did last week! Just at the end of the workshop at SnowCamp! I'm waiting for their answer
> 
> Just sent you an email. Welcome to the Gitpod for Open Source Plan 🥳
> 
> _(sorry for the delays)_

@dadoonet did you enable the prebuild action in your opensource organization (for caching purposes) ?
Normally the workspace will be spawn as a 🚀 (<10sec, with pre-loaded tests too)

**Comment by dadoonet** [comment]
> > 👋🏽 from Gitpod 😄
> > > > Maybe @dadoonet you can apply to: https://www.gitpod.io/for/opensource :)
> > > 
> > > 
> > > I did last week! Just at the end of the workshop at SnowCamp! I'm waiting for their answer
> > 
> > 
> > Just sent you an email. Welcome to the Gitpod for Open Source Plan 🥳
> > _(sorry for the delays)_
> 
> @dadoonet did you enable the prebuild action in your opensource organization (for caching purposes) ? Normally the workspace will be spawn as a 🚀 (<10sec, with pre-loaded tests too)

I don't think I did. How/where do you do that?
