### ISSUE TITLE
Upgrade Apache Tika 1.13

### ISSUE THREAD

**Issue by sgoeschl** [dadoonet/fscrawler#161]
The Tika version being used is nearly one year old - the newest release contains a new tika-langdetect module which should work better now :-)

Any objections to migrate to Tika 1.13?

**Comment by dadoonet** [comment]
++

**Comment by sgoeschl** [comment]
Guess that would mean "+1" in my old-fashioned ways :-)

**Comment by dadoonet** [comment]
:+1:  :)

**Comment by sgoeschl** [comment]
Hi David, if you have some spare cycles have a look at https://github.com/sgoeschl/fscrawler/tree/feature/FSCRAWLER-161

* migrated to Tika 1.13
* try to parse the `document creation date` with some re-surrected code
* The FsDateStringParser & tests are just copy & paste are not final but a starting point

**Comment by sgoeschl** [comment]
Some comments would be still appreciated :-)

**Comment by dadoonet** [comment]
@sgoeschl I just started to look at it today and it looks very nice. I left 2 comments.
Really worths opening a PR
