### ISSUE TITLE
Multi-language support for indexed documents

### ISSUE THREAD

**Issue by sgoeschl** [dadoonet/fscrawler#162]
I probably have to tackle the problem that my indexed documents comes with at least two languages - English & German :-)

What would be a proper way to add multi-language support?
- Update the index mapping to support "en", "de", "fr", "it" with the matching analyzers
- Use tika-landetect to get the primary language being used
- Store the detected language somewhere in the indexed document
- Fill the the "content.$(language)" 

Or is using a dynamically determined index name the better way, e.g. 

```
  "elasticsearch" : {
    "nodes" : [ {
      "host" : "127.0.0.1",
      "port" : 9200
    } ],
    "index" : "docs-${language}",
    "type" : "doc",
    "bulk_size" : 100,
    "flush_interval" : "5s"
  }
```

**Comment by dadoonet** [comment]
I started to implement it.

From FS crawler 2.2, you can ask for language detection using `lang_detect` option:

```json
{
  "name" : "test",
  "fs" : {
    "lang_detect" : true
  }
}
```

In that case, a new field named `meta.language` is added to the generated JSon document.

If you are using elasticsearch 5.0 or superior, you can use this value to send your document to a specific index
using a Node Ingest pipeline which has been introduced with #234.

For example, you can define a pipeline named `langdetect` with:

```sh
PUT _ingest/pipeline/langdetect
{
  "description" : "langdetect pipeline",
  "processors" : [
    {
      "set": {
        "field": "_index"
        "value": "myindex-{{meta.language}}"
      }
    }
  ]
}
```

In FS crawler settings, set both `fs.lang_detect` and `elasticsearch.pipeline` options:

```json
{
  "name" : "test",
  "fs" : {
    "lang_detect" : true
  },
  "elasticsearch" : {
    "pipeline" : "langdetect"
  }
}
```

And then, a document containing french text will be sent to `myindex-fr`.
A document containing english text will be sent to `myindex-en`.

You can also imagine changing the field name from `content` to `content-fr` or `content-en`. That will help you
to define the correct analyzer to use.

Language detection might detect more than one language in a given text but only the most accurate will be set.
Which means that if you have a document containing 80% of french and 20% of english, the document will be marked 
as `fr`.

Note that language detection is CPU and time consuming.

I will push my change anytime soon.

**Comment by Quix0r** [comment]
Please note that the shown POST example misses a comma, should be:
````
PUT _ingest/pipeline/langdetect
{
  "description" : "langdetect pipeline",
  "processors" : [
    {
      "set": {
        "field": "_index",
        "value": "myindex-{{meta.language}}"
      }
    }
  ]
}
````
(after `"field": "_index"`)

**Comment by dadoonet** [comment]
Wanna send a PR?
