### ISSUE TITLE
Arm Docker Image

### ISSUE THREAD

**Issue by Logicer16** [dadoonet/fscrawler#1681]
**Is your feature request related to a problem? Please describe.**

I want to run fscrawler in a docker container on my raspberry pi. However, as this is an arm computer and the docker image is only being built for x86, this does not work.

**Describe the solution you'd like**

Build and distribute an arm docker image of fscrawler.

**Describe alternatives you've considered**

Building from scratch: this is unwieldy and time consuming when compared to the convenience of pulling and running a docker image

**Comment by Logicer16** [comment]
I am not familiar with using `docker-maven-plugin` to build images; I've only ever used the docker cli for build. 

I've had a look through the documentation though and have found [5.1.6. Multi-Architecture Build](https://dmp.fabric8.io/#build-buildx). Based on the current build configuration, `docker.buildx.platform` may also be of interest. Specifying `linux/amd64,linux/arm64` as the platform should build for both architectures.

**Comment by Logicer16** [comment]
Just realised this is a duplicate of #1232 


@dadoonet Did you need any help getting #1518 merged?

**Comment by dadoonet** [comment]
Ha! I forgot about it 🤦🏼‍♂️.

it just needs a rebase on main branch 😉
