### ISSUE TITLE
Version 2.10, REST API, POST new file, Error 500

### ISSUE THREAD

**Issue by ebors-sysnetcz** [dadoonet/fscrawler#1748]
**Describe the bug**

Using the latest version, 2.10. Application is running. 
Using POST Man as client, with the correct setting like in screenshot, i have got the error 500. 
The method uploadToDocumentService is called according to the log, but no more information.

**Logs**

```
2023-10-25 22:52:32 20:52:32,151 DEBUG [f.p.e.c.f.r.RestApi] uploadToDocumentService(true, null, null, null, ...)
```

**Expected behavior**

An file should be uploaded to the app to be processed.

**Versions:**
 - Windows 11
 - Docker (Desktop)
 - Running the app as container
 - Version 2.10 (latest)

**Attachment**

Screenshot of the POSTMAN calling
<img width="616" alt="Snímek obrazovky 2023-10-25 225452" src="https://github.com/dadoonet/fscrawler/assets/49151505/9cccfdaf-1e80-4303-8408-6c206fa51f74">
<img width="617" alt="Snímek obrazovky 2023-10-25 225507" src="https://github.com/dadoonet/fscrawler/assets/49151505/9e466fb1-f8ec-4c61-bf6e-6c001ce34a3e">

**Comment by ebors-sysnetcz** [comment]
Added info, that with curl it is working

<img width="765" alt="image" src="https://github.com/dadoonet/fscrawler/assets/49151505/6c888fb1-a2d8-400b-a52d-81d64497bb64">

**Comment by dadoonet** [comment]
Do you think that POSTMAN could mimic how curl is sending the request?
Or what is your suggestion for a code change?

**Comment by ebors-sysnetcz** [comment]
Yes, i will figure it out, and make the suggestion of the change. I will try to fork the project to the local and test with postman.

**Comment by ebors-sysnetcz** [comment]
Im not so familiar with grizzly2 web server, but its possible to see, what the request is incomming from outside (like log setting)? Or just to see more info in log, like exceptions, in the DocumentApi class method uploadToDocumentService ?

**Comment by dadoonet** [comment]
I think you can probably change the log level for those classes. Hopefully they are tracing everything.

**Comment by ebors-sysnetcz** [comment]
I have some news, i have tried from another module to use the Spring Rest API Client = WebTestClient, and the the REST API on the fscrawler its working very nice, i can upload with this way the attachments to process.  So its a question, if needed to debug the communication with POSTMAN.

The other nice to have could be the authentication of the REST API, with some API-KEY.

**Comment by fg-uulm** [comment]
I experienced the same behaviour, and traced it back by using Wireshark to compare the http requests to the name of the multipart part - if using anything else than "file" for the part I also get an error 500. With the name being "file" and unaltered settings, it seems to work. See attached wireshark screenshot and postman screenshot for reference for a working request.

 
![image](https://github.com/dadoonet/fscrawler/assets/19553942/ada79232-67b7-45f6-beb8-49d9bdefc323)
![image](https://github.com/dadoonet/fscrawler/assets/19553942/0665e05e-b095-460f-8d8d-10ffcc791616)

**Comment by dadoonet** [comment]
Amazing!

So basically, I should "just" check that file is not empty and send a proper error message instead, I guess.

**Comment by dadoonet** [comment]
> The other nice to have could be the authentication of the REST API, with some API-KEY.

Agreed. That'd be great to use Elasticsearch keys for that.
