### ISSUE TITLE
Allow loading external jars for custom Tika Parser

### ISSUE THREAD

**Issue by elgeom** [dadoonet/fscrawler#1769]
I have created a custom Tika Parser class, added a new type to custom-mimetypes.xml, built a jar.
Then a put this jar to FSCrawler lib directory. But still FSCrawler doesn't see my Parser and using EmptyParser...
What did I miss? Is there a way to add custom Tika Parser to FSCrawler?

**Comment by dadoonet** [comment]
That's a good question. 
The only way so far to configure your own parser is by using `tika_config_path`: https://fscrawler.readthedocs.io/en/latest/admin/fs/local-fs.html#tika-config-path

But I'm afraid that FSCrawler won't see your library as it does not load dynamically the jars which are in the `lib` dir apparently.
And I don't know why.

Do you have any idea?

Related issues:

* #1271 
* #1459

**Comment by elgeom** [comment]
It won't see my library, even configuring by using tika_config_path

**Comment by dadoonet** [comment]
Yes. That's the problem. I don't know why the jars are not seen in that case... 
Do you have any idea? That's probably a trivial problem (like a JVM option to add)... 

I'd like to add in the future a plugin mechanism but nothing I can do in the very short term sadly.

**Comment by dadoonet** [comment]
I might have found a workaround. Let me play a bit with this...

**Comment by dadoonet** [comment]
Would you mind sharing with me a minimal sample java code using a custom Tika Parser?

**Comment by elgeom** [comment]
Sure
[tika-parser-ep-package.zip](https://github.com/dadoonet/fscrawler/files/13941445/tika-parser-ep-package.zip)

**Comment by dadoonet** [comment]
Thanks. Do you have a file which can be used to trigger the parser?

**Comment by dadoonet** [comment]
So I think this should work:

* Add your jar to the `lib` dir
* Create a `/tmp/tikaConfig.xml` file:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<properties>
    <service-loader dynamic="true"/>
    <service-loader loadErrorHandler="IGNORE"/>
    <parsers>
        <parser class="com.sc.tika.parser.ep.LasParser">
            <mime>text/plain</mime>
        </parser>
    </parsers>
</properties>
```

* Modify your fscrawler `_settings.yaml`:

```yml
---
name: "test"
fs:
  url: "/tmp/docs"
  tika_config_path: '/tmp/tikaConfig.xml`
```

I modified the `LasParser` as is:

```java
public class LasParser extends AbstractParser {
    private final static Logger logger = LogManager.getLogger(LasParser.class);
    @Override
    public Set<MediaType> getSupportedTypes(ParseContext context) {
        logger.fatal("Hello LAS World");
        return Collections.singleton(MediaType.application("x-las"));
    }
    @Override
    public void parse(
            InputStream stream, ContentHandler handler,
            Metadata metadata, ParseContext context)
            throws IOException, SAXException, TikaException {
        logger.fatal("Hello LAS World");
    }
}
```

* Add a text file in `/tmp/docs`
* Run:

```sh
bin/fscrawler --restart test
```

This gives:

```
18:58:17,445 INFO  [f.p.e.c.f.t.TikaInstance] Using custom tika configuration from [/Users/dpilato/Documents/Elasticsearch/dev/fscrawler/distribution/target/fscrawler-distribution-2.10-SNAPSHOT/config/tikaConfig.xml].
18:58:17,681 FATAL [c.s.t.p.e.LasParser] Hello LAS World
```

So I guess this is all good.

Note that I did that using another dir `external` instead of `lib` which is something coming with #1803.
But this should work without this change.
