### ISSUE TITLE
Fscrawler 2.9-ocr-es7 ocr doesn't work as expected

### ISSUE THREAD

**Issue by zhangdahai112** [dadoonet/fscrawler#1821]
**when deploy to company's server it always print like this below**

like i said，log printed ，elastic index is wrong

**Job Settings**
![image](https://github.com/dadoonet/fscrawler/assets/46101698/493b0be0-0995-43aa-bf17-c2304a6675e2)
```yml
FULL FSCrawler Job Settings HERE
```

**Logs**
![image](https://github.com/dadoonet/fscrawler/assets/46101698/776719c7-b479-47d3-bbba-1a582054e444)

```
FULL FSCrawler LOGS HERE
```

**Expected behavior**

**Versions:**
 - OS: [Linux version 3.10.0-1127.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) ) #1 SMP Tue Mar 31 23:36:51 UTC 2020]
 - Version [redhat 4.8.5]

**Attachment**

If the bug is related to a given file, please share this file, so we can reuse it in tests
to reproduce the problem and may be use it in our integration tests.

**Comment by zhangdahai112** [comment]
i tried update system fonts but not work

**Comment by dadoonet** [comment]
Please try with the latest 2.10-SNAPSHOT instead.

**Comment by dadoonet** [comment]
But I don't think I can do anything if the jvm can't load the fonts. 
Anyway, it should be just a warning I guess.

**Comment by zhangdahai112** [comment]
thanks bro, may be its the system's fault, my local vm works fine and i dont think just a warning indeed influenced my search results in elastic, i'll keep working on it util solve it

**Comment by dadoonet** [comment]
So I think we can close it. Feel free to reopen if needed.

**Comment by zhangdahai112** [comment]
![image](https://github.com/dadoonet/fscrawler/assets/46101698/bce30284-08a1-4bad-8506-d965ab1f0798)
after rebuild the docker image finaly sovled ,thanks !btw, i think the base image ubuntu and fonts is the key to my problem
