### ISSUE TITLE
Generating results by passing a URL address

### ISSUE THREAD

**Issue by muxiaobai** [dadoonet/fscrawler#1890]
http://localhost:8180/fscrawler/_document?debug=true&simulate=true&url=http:demo.com/ADRTDSFFGTD.pdf

the url is a file download , and  By passing a URL address, the result can be generated like uploading a file

**Comment by dadoonet** [comment]
Yes. That'd be great to have 😊

**Comment by muxiaobai** [comment]
https://github.com/dadoonet/fscrawler/pull/1897
