### ISSUE TITLE
Cannot invoke "java.time.LocalDateTime.atZone(java.time.ZoneId)" because "modification" is null

### ISSUE THREAD

**Issue by klavdijS** [dadoonet/fscrawler#1895]
**Describe the bug**

When running fscrawler with docker for the first time over a remote SSH connection on a Windows server in a directory full of .zip files, fscrawler crashes with the following message (folder path redacted for privacy reasons):

![image](https://github.com/dadoonet/fscrawler/assets/15001788/6e00c68b-41ed-4583-99ff-6050d8be808f)

After the first unsuccessful run it then successfully runs periodically, but it does not index .zip files inside the folder. They are ignored all the time and are also not uploaded on the first run. 
If I add a *.pdf document to the folder, it is crawled successfully.

**Job Settings**

```yml
name: "job_name"
fs:
  url: "/E:/TEST/Documents/TEST/TEST/TEST/2023"
  update_rate: "1m"
  json_support: false
  filename_as_id: false
  add_filesize: true
  remove_deleted: true
  add_as_inner_object: false
  store_source: false
  index_content: true
  attributes_support: false
  raw_metadata: false
  xml_support: false
  index_folders: true
  lang_detect: false
  continue_on_error: true
  ocr:
    language: "eng"
    enabled: false
    pdf_strategy: "ocr_and_text"
  follow_symlinks: false
server:
  hostname: ssh.server.com
  port: 22
  username: "user"
  password: "pw"
  protocol: "ssh"
elasticsearch:
  nodes:
  - url: "https://es.server"
  username: es
  password: es_pw
  bulk_size: 100
  flush_interval: "5s"
  byte_size: "10mb"
  ssl_verification: false
  push_templates: true
```

**Logs**

```
Error while crawling /E:/TEST/Documents/TEST/TEST/TEST/2023: Cannot invoke "java.time.LocalDateTime.atZone(java.time.ZoneId)" because "modification" is null
13:23:29,321 WARN  [f.p.e.c.f.FsParserAbstract] Full stacktrace
java.lang.NullPointerException: Cannot invoke "java.time.LocalDateTime.atZone(java.time.ZoneId)" because "modification" is null
	at fr.pilato.elasticsearch.crawler.fs.beans.Folder.<init>(Folder.java:61) ~[fscrawler-beans-2.10-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.indexDirectory(FsParserAbstract.java:540) ~[fscrawler-core-2.10-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.run(FsParserAbstract.java:142) [fscrawler-core-2.10-SNAPSHOT.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
```

**Expected behavior**

Expected behavior is that the .zip files are successfully indexed the first time and that the fscrawler does not crash on start.

**Versions:**
 - OS: Ubuntu 22.04.4 LTS
 - Version latest docker version dadoonet/fscrawler:latest

**Attachment**

Unfortunately cannot share any files due to privacy concerns.

**Comment by dadoonet** [comment]
Thanks for reporting this. This is definitely a bug. 🫣

**Comment by dadoonet** [comment]
I created #1896 to fix this.

**Comment by dadoonet** [comment]
This should be ok now. Let's just wait for the next build to happen ;)
