### ISSUE TITLE
Index file hash/checksum

### ISSUE THREAD

**Issue by Muffinman** [dadoonet/fscrawler#192]
Hi,

I'm wondering if it's possible to index an MD5/SHA file hash/checksum when inserting the documents?

This would be very useful for us to detect duplicate files.

**Comment by dadoonet** [comment]
Sounds like a good idea to me

**Comment by dadoonet** [comment]
I pushed a new feature.

If you want FS crawler to generate a checksum for each file, set `checksum` to the algorithm you wish to use to compute the checksum, such as `MD5` or `SHA-1`.

```json
{
  "name": "test",
  "fs": {
    "checksum": "MD5"
  }
}
```

Will be in 2.1

**Comment by Muffinman** [comment]
Nice! Will give it a go, thanks.
