### ISSUE TITLE
NullPointerException when traversing certain directories when running on Windows

### ISSUE THREAD

**Issue by glaxaco** [dadoonet/fscrawler#197]
When crawling the "My Documents" folder on Windows, I am getting a NullPointerException in FileAbstractorFile.getFiles(). Apparently there are certain symbolic links ("My Music") etc. that don't play well with Java - see http://stackoverflow.com/a/30403010/2144 for a better explanation of the details.

**Comment by dadoonet** [comment]
Thank you!

**Comment by glaxaco** [comment]
Thanks for taking care of this! I appreciate it. If you take pull requests, I'd be happy to look at these sorts of issues in the future.

**Comment by dadoonet** [comment]
Sure! Feel free to contribute! :)
