### ISSUE TITLE
inotify usage instead of update_rate

### ISSUE THREAD

**Issue by mdef** [dadoonet/fscrawler#199]
It could be easily done with systemd path-based activation: A unit can be started based on activity on or the availability of certain filesystem paths.
This utilizes inotify. — Path unit configuration. 
But issue is, that fscrawler running in loop.

Is it possible to make fscrawler to exit after it finished scanning?

**Comment by dadoonet** [comment]
I think this is a valid concern.

Either we can support an option to the CLI like https://github.com/dadoonet/fscrawler/issues/137#issuecomment-221565344
Or in the job definition itself, add a new setting like: `"exit_after_job": true`, default to `false`.

**Comment by dadoonet** [comment]
I think it's now supported with #227.
