### ISSUE TITLE
Windows // Not able to start fscrawler...  

### ISSUE THREAD

**Issue by sbastos01** [dadoonet/fscrawler#200]
Not able to start fscrawler...   looping error

Here the invoking cmd.: `C:\kibi\kibi-4.4.2-windows64-demo-full\fscrawler-2.1\bin>fscrawler test.json --config_dir  C:\kibi\kibi-4.4.2-windows64-demo-full\fscrawler-2.1\bin`

1- I added all config and crawler dir under `fscrawler/bin`. 
2- Initially it was located at `fscrawler-2.1/bin/test.json`
3- system will delete test.json and create a copy to `fscrawler-2.1/bin/test/_settings.json`
   3.1- System will create `bin/test/_settings.json` <<< copy of test.json ( will remove ass well the last "}}"
4 System will error that `fscrawler-2.1/bin/test.json` was not there . will prompt to create test.json
5- System will look to not find test.json
![image](https://cloud.githubusercontent.com/assets/10553109/17260147/c3671efa-559c-11e6-8efc-a0b7486ba5b1.png)

Config:

```json
{
  "name" : "test",
  "fs" : {
    "url" : "C:\kibi\kibi-4.4.2-windows64-demo-full\fscrawler-2.1\Crawler",
```

Logs>>> 
Directory of C:\kibi\kibi-4.4.2-windows64-demo-full\fscrawler-2.1\bin

```
07/29/2016  10:57 AM    <DIR>          .
07/29/2016  10:57 AM    <DIR>          ..
07/28/2016  09:52 PM             1,135 fscrawler
07/28/2016  09:52 PM             1,078 fscrawler.bat
07/29/2016  10:57 AM               699 test.json
07/29/2016  10:38 AM    <DIR>          _default
07/29/2016  10:38 AM    <DIR>          _settings
               3 File(s)          2,912 bytes
               4 Dir(s)  894,151,491,584 bytes free
```

```
C:\kibi\kibi-4.4.2-windows64-demo-full\fscrawler-2.1\bin>fscrawler test.json --config_dir  C:\kibi\kibi-4.4.2-windows64-demo-full\fscrawler-2.1\bin
11:05:28,125 INFO  [f.p.e.c.f.u.FsCrawlerUtil] Moved Legacy file from [C:\kibi\kibi-4.4.2-windows64-demo-full\fscrawler-2.1\bin\test.json] to [C:\kibi\kibi-4.4.2-windows64-demo-full\fscrawler-2.1\bin\test\_settings.json]
11:05:28,138 WARN  [f.p.e.c.f.FsCrawler] job [test.json] does not exist
11:05:28,142 INFO  [f.p.e.c.f.FsCrawler] Do you want to create it (Y/N)?
y
Exception in thread "main" java.nio.file.NoSuchFileException: C:\kibi\kibi-4.4.2-windows64-demo-full\fscrawler-2.1\bin\test.json\_settings.json
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230)
        at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
        at java.nio.file.Files.newOutputStream(Files.java:216)
        at java.nio.file.Files.write(Files.java:3292)
        at fr.pilato.elasticsearch.crawler.fs.meta.MetaFileHandler.writeFile(MetaFileHandler.java:80)
        at fr.pilato.elasticsearch.crawler.fs.meta.settings.FsSettingsFileHandler.write(FsSettingsFileHandler.java:56)
        at fr.pilato.elasticsearch.crawler.fs.FsCrawler.main(FsCrawler.java:181)

C:\kibi\kibi-4.4.2-windows64-demo-full\fscrawler-2.1\bin>fscrawler test.json --config_dir  C:\kibi\kibi-4.4.2-windows64-demo-full\fscrawler-2.1\bin
11:10:18,528 WARN  [f.p.e.c.f.FsCrawler] job [test.json] does not exist
11:10:18,533 INFO  [f.p.e.c.f.FsCrawler] Do you want to create it (Y/N)?
n
```

**Comment by dadoonet** [comment]
Some comments.

I'd not put config files in a `bin` dir.
If you need to upgrade `fscrawler` it will be hard IMO.

Try with `/` instead of `\` in the URL config. Or use `\\` instead.

**Comment by sbastos01** [comment]
Yep. Will change it on docs....
Will move to a folder >>> /project01/

**Comment by dadoonet** [comment]
Does it work now?

**Comment by sbastos01** [comment]
Great !

yep. getting the index to be generated.  Will reply with more details and |
revised documentations...

InitiaLL ONLY TXT were being indexed... after while all types...

showing this msg: fail to determine group...


01:18:31,482 [33mWARN [m [f.p.e.c.f.u.FsCrawlerUtil] Failed to determine
'group' of \fscrawler-2.1-b\to-be-crawled\Serendipitous Discovery 02.rtf:
null
01:18:31,489 [33mWARN [m [f.p.e.c.f.u.FsCrawlerUtil] Failed to determine
'group' of \fscrawler-2.1-b\to-be-crawled\Serendipitous Discovery of my
things srbb - Copy.txt: null
01:18:31,491 [33mWARN [m [f.p.e.c.f.u.FsCrawlerUtil] Failed to determine
'group' of \fscrawler-2.1-b\to-be-crawled\Sergio B RESUME SUBMITAL AND
INTERVIEW AGREEMENT (1).doc: null
01:18:31,494 [33mWARN [m [f.p.e.c.f.u.FsCrawlerUtil] Failed to determine
'group' of \fscrawler-2.1-b\to-be-crawled\signed appraisal note.doc: null
01:18:31,497 [33mWARN [m [f.p.e.c.f.u.FsCrawlerUtil] Failed to determine
'group' of \fscrawler-2.1-b\to-be-crawled\Tech E training Course fee
Transfer details -  Big Data (1).pdf: null
01:18:31,505 [33mWARN [m [f.p.e.c.f.u.FsCrawlerUtil] Failed to determine
'group' of \fscrawler-2.1-b\to-be-crawled\test01000.txt: null


Cheers,
Sergio Bastos
I help the shift to red rabbit
+1-561.430.7667
skype: sbastos-ca
LinkedIn: http://www.linkedin.com/in/sbastos

**Comment by dadoonet** [comment]
Ha yeah. Group only works on Unix I think. I need to have better logs and move that to DEBUG instead.

**Comment by dadoonet** [comment]
So I'm closing this now. Note that #211 is fixing the WARN message you are getting.

**Comment by sbastos01** [comment]
I see.

Cheers,
Sergio Bastos
I help the shift to red rabbit
+1-561.430.7667
skype: sbastos-ca
LinkedIn: http://www.linkedin.com/in/sbastos
