### ISSUE TITLE
Index certain file types in folders recursively

### ISSUE THREAD

**Issue by DatanoiseTV** [dadoonet/fscrawler#206]
For my usecase, I want fscrawler to index all "*.mp4" files in all subfolders.
Therefore my configuration looks as following:

```json
{
  "name" : "Movies",
  "fs" : {
    "url" : "/Users/xyz/Downloads",
    "update_rate" : "15s",
    "includes" : [ "*.mp4"],
    "json_support" : false,
    "filename_as_id" : false,
    "add_filesize" : true,
    "store_source" : false,
    "index_content" : false
  },
  "server" : null,
  "elasticsearch" : {
    "nodes" : [ {
      "host" : "127.0.0.1",
      "port" : 9200
    } ],
    "index" : "koo",
    "type" : "doc",
    "bulk_size" : 1,
    "flush_interval" : "5s"
  }
}
```

But my document amount in ES stays at 0. --trace also doesn't show any helpful output.
Version: latest from git, on OSX

**Comment by dadoonet** [comment]
What gives the output of: 

```sh
curl 127.0.0.1:9200/koo?pretty
curl 127.0.0.1:9200/_cat/indices?v
```

**Comment by DatanoiseTV** [comment]
`{
  "koo" : {
    "aliases" : { },
    "mappings" : {
      "folder" : {
        "properties" : {
          "encoded" : {
            "type" : "string",
            "index" : "not_analyzed",
            "store" : true
          },
          "name" : {
            "type" : "string",
            "index" : "not_analyzed",
            "store" : true
          },
          "real" : {
            "type" : "string",
            "index" : "not_analyzed",
            "store" : true
          },
          "root" : {
            "type" : "string",
            "index" : "not_analyzed",
            "store" : true
          },
          "virtual" : {
            "type" : "string",
            "index" : "not_analyzed",
            "store" : true
          }
        }
      },
      "doc" : {
        "_source" : {
          "excludes" : [ "attachment" ]
        },
        "properties" : {
          "attachment" : {
            "type" : "binary",
            "store" : true
          },
          "attributes" : {
            "properties" : {
              "group" : {
                "type" : "string",
                "index" : "not_analyzed",
                "store" : true
              },
              "owner" : {
                "type" : "string",
                "index" : "not_analyzed",
                "store" : true
              }
            }
          },
          "content" : {
            "type" : "string",
            "store" : true
          },
          "file" : {
            "properties" : {
              "checksum" : {
                "type" : "string",
                "index" : "not_analyzed",
                "store" : true
              },
              "content_type" : {
                "type" : "string",
                "index" : "not_analyzed",
                "store" : true
              },
              "filename" : {
                "type" : "string",
                "index" : "not_analyzed",
                "store" : true
              },
              "filesize" : {
                "type" : "long",
                "store" : true
              },
              "indexed_chars" : {
                "type" : "long",
                "store" : true
              },
              "indexing_date" : {
                "type" : "date",
                "store" : true,
                "format" : "dateOptionalTime"
              },
              "last_modified" : {
                "type" : "date",
                "store" : true,
                "format" : "dateOptionalTime"
              },
              "url" : {
                "type" : "string",
                "index" : "no",
                "store" : true
              }
            }
          },
          "meta" : {
            "properties" : {
              "author" : {
                "type" : "string",
                "store" : true
              },
              "date" : {
                "type" : "date",
                "store" : true,
                "format" : "dateOptionalTime"
              },
              "keywords" : {
                "type" : "string",
                "store" : true
              },
              "title" : {
                "type" : "string",
                "store" : true
              }
            }
          },
          "path" : {
            "properties" : {
              "encoded" : {
                "type" : "string",
                "index" : "not_analyzed",
                "store" : true
              },
              "real" : {
                "type" : "string",
                "index" : "not_analyzed",
                "store" : true
              },
              "root" : {
                "type" : "string",
                "index" : "not_analyzed",
                "store" : true
              },
              "virtual" : {
                "type" : "string",
                "index" : "not_analyzed",
                "store" : true
              }
            }
          }
        }
      }
    },
    "settings" : {
      "index" : {
        "creation_date" : "1470672380134",
        "number_of_shards" : "5",
        "number_of_replicas" : "0",
        "uuid" : "Y55ySTXMQJaXLJ5q21Upcw",
        "version" : {
          "created" : "2030599"
        }
      }
    },
    "warmers" : { }
  }
}`

and

`
health status index pri rep docs.count docs.deleted store.size pri.store.size 
green  open   koo     5   0          2            0     13.1kb         13.1kb 
``

So far only 2 docs got indexed which were in the "root"-folder.

**Comment by dadoonet** [comment]
Sorry I meant:

```sh
curl 127.0.0.1:9200/koo/_search?pretty
```

Could you also run something like:

```sh
tree /Users/xyz/Downloads
```

Could you also try with another dir instead of Downloads?

Can you also paste the logs for FSCrawler? Using `--verbose`?

**Comment by tcarolan** [comment]
I have the same problem but downloaded the source and changed the code to accommodate my use case. My case is this: crawl a huge directory structure recursively and only index certain filetypes. The current set of "include" and "exclude" applies to BOTH filenames and directory names and does not include the entire path - preventing the use of regex for filetypes of let's say "*.doc" when you want to crawl down the file structure.  I tried all manner of regex to make it work but ended up moving the call to "FsCrawlerUtil.isIndexable" in method addFilesRecursively() to only apply to files and not also for directories. This could be greatly improved if a user of fscrawler could configure different regex pattern sets for files and another set for directories. That way I could exclude certain directories like ".git" or ".svn" (and include everything else) and include only certain filetypes separately.

**Comment by vakopian** [comment]
@dadoonet could you please confirm that applying the include patters to simple directory names is intentional in `addFilesRecursively`? The current code will only go into subdirectories recursively if the directory names match the provided include patterns, which is typically never, because the include patters have the file extensions. So despite the name `addFilesRecursively`, this method will typically not work recursively at all.
The fix is very easy and I can make a pull request if you agree: the line [FsCrawlerImpl.java#L365](https://github.com/dadoonet/fscrawler/blob/0b86c7c6e6138f43330dd3bec30568b4ab91ed6a/src/main/java/fr/pilato/elasticsearch/crawler/fs/FsCrawlerImpl.java#L365) should be changed from
```
if (isIndexable)
```
to
```
if (child.directory || isIndexable)
```

**Comment by dadoonet** [comment]
Please do!
