### ISSUE TITLE
Using elastic / changeme username / password for a better OOTB experience

### ISSUE THREAD

**Issue by dadoonet** [dadoonet/fscrawler#210]
Follow up for #144 and #207 

This is more a question for users than a fix yet.

Should we use a default `username` / `password` for FS Crawler?

* All the time - even if the cluster is not secured? It should work as credentials will just be ignored
* When no `username` is set, based on detection: we first try to connect to the cluster with no credentials. If it fails, we fallback to `elastic` / `changeme`. If it fails, we stop FS Crawler.

Thoughts?

**Comment by skearns64** [comment]
Personally, I think I prefer having the specification of username/password being explicit here. I don't think we want to encourage users to keep/use default passwords. 

Where I see default usernames/passwords being most useful is in the initial getting started experience. Here, I don't see that as the case - you would typically want to have a specific user for fscrawler, which had write access to only the specific indices that are appropriate.  

To help with the the getting started experience, I would imagine that we could have a fscrawler pack that includes a Kibana "Add Data Wizard," similar to the "upload CSV" feature that is in 5.0. As part of the wizard, it could help you create a user with the most restricted permissions possible.

**Comment by dadoonet** [comment]
That makes a lot of sense to me. Thanks @skearns64!
Having `Add Data Wizard` Kibana option would make sense. And actually having a FSCrawler plugin for Kibana would make sense.
Needs some thinking as it's not as straightforward as it seems :) 

Closing this issue for now. Thanks again!
