### ISSUE TITLE
Add support for multiple roots

### ISSUE THREAD

**Issue by mdussere** [dadoonet/fscrawler#223]
Hello,

I'm new to fscrawler and it looks very promising  to me.

The only concern I have is that I have several mount points to index and I don't want to run several processes. 
Is there a way to give a table of roots for fscrowler to index ?
Is it possible to tell fscrowler not to loop but to index once and exit ? (I would script the main loop myself)

Thanks for your time.
Regards

Michael

**Comment by dadoonet** [comment]
> Is it possible to tell fscrawler not to loop but to index once and exit ? (I would script the main loop myself)

Not with the current version, but I'll be happy to add it. Could you open another issue for it?

> Is there a way to give a table of roots for fscrawler to index ?

Not with the current version. This one is harder to solve but doable though. Let's keep your issue opened and I'll think about it next time I'll work on FSCrawler.

**Comment by dadoonet** [comment]
As I now have implemented #227, I guess you can run something like:

```sh
bin/fscrawler job1 --loop 1; bin/fscrawler job2 --loop 1
```

You should be able to index multiple paths, one after the other.
So I guess we can close this.

Reopen if you think it won't work in your case.
