### ISSUE TITLE
Documentation request: update_rate

### ISSUE THREAD

**Issue by Muffinman** [dadoonet/fscrawler#225]
Hi,

I'm wondering what the `update_rate` config option actually does... and what a sensible value to set this at would be?

I'm indexing two different volumes on different instances of FSCrawler, one which contains ~5000 files/dirs and the other contains several million.

Having a `5m` `update_date` seems to work fine on the smaller volume, but it does not sound very sensible to attempt to rescan the entire filesystem this often for my large volume (I'm assuming that's what it does).

I can see in your examples sometimes `update_rate` is set to as little as `15s` - would this cause a lot of load with larger indexes?

It would be nice to have some clarification in the docs for this config option, what it does and what the implications are of setting it too low / high.

**Comment by dadoonet** [comment]
> I can see in your examples sometimes `update_rate` is set to as little as `15s`

Worse than that. There is one example set to `5s` which is only good for unit tests. :)

`update_rate` is the pause duration between the last time we read the file system and another run.
Which means that if you set it to `15m` (the default value), the next scan will happen on 15 minutes after the end of the current scan, whatever its duration.

I think that keeping it high is reasonable. That being said, the way FSCrawler works today is far from being ideal.
I started a branch some months ago about using a RSync like system instead. That would avoid having to wait for anything.

I agree that `update_rate` should have a better documentation. I'll fix that unless you want to send a PR for it.
