### ISSUE TITLE
Support line by line indexation for TXT files

### ISSUE THREAD

**Issue by lbgws2** [dadoonet/fscrawler#226]
When fscrawler index a file ,it's index line by line or index the whole file?

how to index a file line by line?

**Comment by dadoonet** [comment]
What kind of file are you thinking about? Like a PDF?

**Comment by lbgws2** [comment]
a text file

**Comment by dadoonet** [comment]
So Tika which is used behind the scene does not extract by line or page or whatever but only the full text.
What is your use case exactly?

Asking that because for a text file we can omit Tika and directly stream the content and do whatever processing we want.

**Comment by lbgws2** [comment]
1.my files larger than 50GB,a single is more than 100Kb,if index the whole file,the results of match is too lot,
2.i want to export the rusults to analysis,for nlp.

**Comment by lbgws2** [comment]
or change a text file to a csv file ?

**Comment by dadoonet** [comment]
For such a case you can use logstash. 
For example: http://david.pilato.fr/blog/2016/01/05/understanding-zipfs-law/

**Comment by lbgws2** [comment]
thanks!
