### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by ernestoarbitrio** [dadoonet/fscrawler#228]
after 1 minute i recieve 
```
Error while indexing content from [java.io.FileNotFoundException: /mypath/462EEDC50AA7464EC1257A1C0024EF58.txt (Too many open files), /mypath]
Exception in thread "fs-crawler" java.lang.NullPointerException
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.run(FsCrawlerImpl.java:320)
	at java.lang.Thread.run(Thread.java:745)
```
I'm trying to indexing ~6TB of data
How can i fix this?

**Comment by dadoonet** [comment]
Interesting. It sounds like that streams are not closed.
It's a bug IMO. Will fix soonish.

**Comment by dadoonet** [comment]
@ernestoarbitrio Could you give a try with this SNAPSHOT version? https://oss.sonatype.org/content/repositories/snapshots/fr/pilato/elasticsearch/crawler/fscrawler/2.2-SNAPSHOT/fscrawler-2.2-20160916.155616-19.zip

Thanks a lot!

**Comment by ernestoarbitrio** [comment]
i'll try this afternoon, thanks a lot

**Comment by ernestoarbitrio** [comment]
Good, it seems working now! TY

**Comment by dadoonet** [comment]
Awesome! Thanks for reporting and confirming!
