### ISSUE TITLE
Add test for compressed files

### ISSUE THREAD

**Issue by dadoonet** [dadoonet/fscrawler#230]
The idea is to uncompress the documents available within a ZIP file and index them all.

Coming from https://github.com/elastic/elasticsearch/issues/20510

**Comment by 1049229070** [comment]
Hello, thank you very much for your selfless dedication. I want to ask you a question. Now do you support parsing zip and various compressed files?

**Comment by dadoonet** [comment]
I think you can always index a zip file as one single document. It won't index separately individual files though.
Also it might consume a huge amount of memory.
