### ISSUE TITLE
fscrawler startup fail

### ISSUE THREAD

**Issue by Jiangzhengmin** [dadoonet/fscrawler#232]
![image](https://cloud.githubusercontent.com/assets/20415200/19428810/c4bd7666-947e-11e6-902b-22ed8dee8f4c.png)

how to resolve it?

**Comment by dadoonet** [comment]
Don't paste images please. They are not indexed so no one can really search for the content.

Can you explained:

* what exactly you did from the beginning?
* paste the full logs (formatted with ` please)?
* give the version you are using?

Thanks

**Comment by dadoonet** [comment]
Can you explain what was wrong? It can help other users if they get the same issue.
