### ISSUE TITLE
Index custom properties in pdfs

### ISSUE THREAD

**Issue by deemur** [dadoonet/fscrawler#238]
Hi,

I was able to setup fscrawler and index pdfs from a remote filesystem.
The pdf properties under "Description" tab (open pdf -> File -> Properties -> Description) got indexed. However, the custom properties under the "custom" tab (open pdf -> File -> Properties -> Custom) are not indexed. Is there a way to index them?

Thanks.

**Comment by dadoonet** [comment]
If you can share a document like this I can have a look. But as long as you did not disable [raw metatadata](https://github.com/dadoonet/fscrawler#disabling-raw-metadata), everything Tika is extracting should be there.
May be something to ask to Tika project?

**Comment by deemur** [comment]
Here is a sample pdf with some custom properties - 
[dell-c1760nw_user's guide_en-us.pdf](https://github.com/dadoonet/fscrawler/files/552666/dell-c1760nw_user.s.guide_en-us.pdf)

**Comment by dadoonet** [comment]
Any chance you can provide a sample document which contains custom properties but which is not made under any copyright so I can use it in a test case?

Thanks!

**Comment by dadoonet** [comment]
No further news for now. Closing. Feel free to reopen if you have a document I can reuse to share.

Thanks.
