### ISSUE TITLE
Timezone on _status.json file is UTC based instead of local Timezone

### ISSUE THREAD

**Issue by christopherjm** [dadoonet/fscrawler#245]
This issue might be something that I missed on my side, but every time I start the crawler, the lastrun is 5 hours ahead of my local time

`{
  "name" : "documents",
  "lastrun" : "2016-11-11T15:53:20.474Z",
  "indexed" : 0,
  "deleted" : 0
}`

Where my current time is Nov 11 10:57 AM. In effect, the crawler is not updating because the last run is in the future. Please advise. Thanks!

**Comment by dadoonet** [comment]
Thank you for reporting! I pushed hopefully a fix for 2.2.
If you have any chance to test the latest SNAPSHOT and confirm it fixes the problem that'd be fantastic!

Or reopen if it's not fixed.
