### ISSUE TITLE
SSH does not detect modified files  

### ISSUE THREAD

**Issue by babadofar** [dadoonet/fscrawler#257]
When checking last modified documents on ssh connections, newer documents aren't discovered. 
This is because getMtime returns seconds, not milliseconds, which makes the date calculations wrong for ssh. 
Multiply the result of getMtime with 1000L to get the correct date.

https://epaul.github.io/jsch-documentation/simple.javadoc/com/jcraft/jsch/SftpATTRS.html#getMTime()

https://github.com/dadoonet/fscrawler/blob/20b9a338650ed3a98303922d3fbe1e669a88434b/src/main/java/fr/pilato/elasticsearch/crawler/fs/fileabstractor/FileAbstractorSSH.java#L53

**Comment by dadoonet** [comment]
Thanks a lot! Indeed that was wrong.
