### ISSUE TITLE
indexing remote documents via ssh

### ISSUE THREAD

**Issue by MaxJust** [dadoonet/fscrawler#26]
First of all sorry for my English. 

About issue, I have 3 machines, two elastics nodes and one documents repository.
For example, let elastic nodes have the follow ip 192.168.55.11 (node 1) and 192.168.55.12 (node 2) and the document repository have ip 192.168.55.13 and have folder in root directory with path "/files/"

I download zip of fsriver 0.3.0-SNAPSHOT and extract it into plugin directory on both nodes.
here `ls -l` output one of them:

```sh
elastic/plugins/fsriver# ls -l
-rw-r--r--  1 root  wheel   35107 19 июл 17:09 fsriver-0.3.0-SNAPSHOT.jar
-rw-r--r--  1 root  wheel  229086  7 мар 09:23 jsch-0.1.49.jar
```

after that I stop elastic via `curl -XPOST '192.168.55.11:9200/_cluster/nodes/_shutdown'`

and then again start it via `./bin/elaticsearch` both nodes

In logs I see what fsriver is ok. Plugin loaded and everything is ok:

```
[2013-07-20 17:15:39,558][INFO ][plugins] [Prime] loaded [mapper-attachments, river-fs, analysis-morphology], sites [head]
```

after that I create a test index from the document reposiroty`s machine (192.168.55.13):

```sh
curl -XPUT '192.168.55.11:9200/sshdocs/' -d '{}'
```

got ok answer from elastic and:

```sh
curl -XPUT '192.168.55.11:9200/_river/sshdocs/_meta' -d '{
  "type": "fs",
  "fs": {
    "url": "/files",
    "server": "192.168.55.13",
    "username": "USER",
    "password": "PASS",
    "protocol": "ssh",
    "update_rate": 60000,
    "includes": [ "*.doc" , "*.xls", "*.pdf" ]
  }
}'
```

elastic tell me:

```javascript
{"ok":true,"_index":"_river","_type":"sshdocs","_id":"_meta","_version":1}
```

And then I look to the statistic of index and see 

* size: 495b (890b)
* docs: 0 (0)

index have zero document 

logs have the follow WARN

```
[WARN ][fr.pilato.elasticsearch.river.fs.river.FsRiver] [Sectant] [fs][sshdocs] Error while indexing content from /files
```

PS:
I have elasticSearch 0.90.2
OS FreeBSD 9.1
openjdk-7.25.15 

in configuration of elasticSearch I have disabled `zend.discovery.multicast` option.

**Comment by dadoonet** [comment]
@utk4rsh I'm unsure if this issue is still valid. 
The code changed a lot now it's running on its own and not as a plugin anymore.

I'm closing for now but if you think the issue stills there feel free to send a PR. I'll try some more testing in the future though.
