### ISSUE TITLE
Use path analyzer for directory fields

### ISSUE THREAD

**Issue by trorbyte** [dadoonet/fscrawler#271]
Should the virtual field in doc and folders use a path tokenizer by default?

https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-pathhierarchy-tokenizer.html

**Comment by dadoonet** [comment]
I think it makes sense. Thanks for raising this!

**Comment by trorbyte** [comment]
No worries - thanks for _writing_ this

**Comment by trorbyte** [comment]
I've added a second field **virtual.tree** so that both direct match on the virtual keyword value, or path related queries can be performed. As illustrated in the ElasticSearch: The Definitive Guide book.
