### ISSUE TITLE
content is null when creating the most simple job

### ISSUE THREAD

**Issue by shadiakiki1986** [dadoonet/fscrawler#276]
Hello. Thank you for this package. I'm trying it, but I keep getting `null` in the `content`, even for a plain text file containing plain text `shadi`. Could you give me some pointers on how I can get the content to show up? Other than the plain text file, I'd like to index `.xlsx`, `.xls`, and `.pdf` formats.

Here is my job settings file:
```json
{
  "name" : "sic_list",
  "fs" : {
    "url" : "/data/fscrawler/files",
    "update_rate": "1m",
    "indexed_chars": "100%"
  },
  "elasticsearch" : {
    "index" : "sic_list",
    "type": "doc",
    "nodes" : [
      { "host" : "myhost.com", "port" : 9200 }
    ]
  }
}
```
and here is an excerpt from my `--trace` output
```
10:18:31,678 DEBUG [f.p.e.c.f.u.FsCrawlerUtil] filename = [test.txt], includes = [null], excludes = [null]
10:18:31,679 TRACE [f.p.e.c.f.u.FsCrawlerUtil] no rules
10:18:31,679 DEBUG [f.p.e.c.f.FsCrawlerImpl] [test.txt] can be indexed: [true]
10:18:31,679 DEBUG [f.p.e.c.f.FsCrawlerImpl]   - file: test.txt
10:18:31,680 DEBUG [f.p.e.c.f.FsCrawlerImpl] fetching content from [/data/fscrawler/files],[test.txt]
10:18:31,680 DEBUG [f.p.e.c.f.FsCrawlerImpl] Indexing in ES sic_list, doc, 57e81419ed4fa6aa86d668bb9e28674
10:18:31,681 TRACE [f.p.e.c.f.FsCrawlerImpl] JSon indexed : {
  "content" : null,
  "attachment" : null,
  "meta" : {
    "author" : null,
    "title" : null,
    "date" : null,
    "keywords" : null,
    "raw" : null
  },
  "file" : {
    "content_type" : null,
    "last_modified" : "2017-01-21T10:10:03Z",
    "indexing_date" : "2017-01-21T10:18:31.680Z",
    "filesize" : null,
    "filename" : "test.txt",
    "url" : "file:///data/fscrawler/files/test.txt",
    "indexed_chars" : null,
    "checksum" : null
  },
  "path" : {
    "encoded" : "6113a2c108ffc50c1fd761817d96ca7",
    "root" : "6113a2c108ffc50c1fd761817d96ca7",
    "virtual" : "",
    "real" : "/data/fscrawler/files/test.txt"
  },
  "attributes" : null
}
```
I'm running `fscrawler` from a dockerfile
```
FROM openjdk:alpine
RUN apk add --update openssl
RUN  wget https://repo1.maven.org/maven2/fr/pilato/elasticsearch/crawler/fscrawler/2.1/fscrawler-2.1.zip \
  && unzip fscrawler-2.1.zip
RUN mkdir ~/.fscrawler
WORKDIR ./fscrawler-2.1
ENTRYPOINT cp /data/fscrawler/home/* ~/.fscrawler -r \
        && bin/fscrawler --trace sic_list
```
with the following docker command
```bash
  docker build -t fscrawler build/fscrawler/
  docker run -it --rm --name fscrawler-siclist \
    -v /home/shadi/sic_lists/:/data/fscrawler/files/:ro \
    -v "${PWD}"/home/:/data/fscrawler/home/:ro \
    fscrawler
```
and all the files are readable by the same user launching `fscrawler`

**Comment by dadoonet** [comment]
Hmmm. That's super strange. I mean that the file can be read by FSCrawler but apparently when it parses its content, nothing is coming back.
Can you paste the full logs in case I found something strange in it?

Can you also try with the latest SNAPSHOT: https://oss.sonatype.org/content/repositories/snapshots/fr/pilato/elasticsearch/crawler/fscrawler/2.2-SNAPSHOT/fscrawler-2.2-20170121.085715-101.zip?

BTW Thanks for the Docker recipe. I think we should add this in the documentation as it's super valuable for the end users. If you want to contribute some doc, I'll be happy to review and merge.

**Comment by dadoonet** [comment]
Forgot to say: can you also run the same thing but without Docker so we can see it's a problem in this context only?

**Comment by shadiakiki1986** [comment]
You're welcome! I'll try your suggestions as soon as I can and will let you
know.

**Comment by shadiakiki1986** [comment]
Hello. 

*With docker*
1. [Here](http://paste.ubuntu.com/23851002/) are the full logs using `fscrawler 2.1` from docker. It shows `content: null`
1. [Here](http://paste.ubuntu.com/23850864/) are the full logs using `fscrawler 2.2` snapshot link above from docker. It does not show any `contents` field (nor other fields that used to be null in `2.1` logs)
2. I tried with changing my job setting `store_source` from `false` to `true`, but with the same result. 
4. Using the `--rest` flag in `2.2` throws a `null pointer exception`. Logs [here](http://paste.ubuntu.com/23850886/)

*Without docker*
1. [Here](http://paste.ubuntu.com/23851107) are the full logs using `fscrawler 2.1`. They also show `content: null` just like in docker
2. [Here](http://paste.ubuntu.com/23851114/) are the full logs using `2.2`. They also show no `content` tag just like in docker

**Comment by shadiakiki1986** [comment]
Btw, if you notice, I get an empty meta tag (e.g. line 86 [here](http://paste.ubuntu.com/23851114/)). I tried setting `"raw_metadata" : true` in the settings, but I still get an empty `meta` tag.

**Comment by dadoonet** [comment]
Apparently you already ran fscrawler:

```
08:05:49,727 DEBUG [f.p.e.c.f.FsCrawlerImpl] [test.txt] can be indexed: [true]
08:05:49,727 DEBUG [f.p.e.c.f.FsCrawlerImpl]   - file: test.txt
08:05:49,728 DEBUG [f.p.e.c.f.FsCrawlerImpl]     - not modified: creation date 2017-01-23T07:52:30 , file date 2017-01-23T07:52:30, last scan date 2017-01-23T08:02:01.904
```

Can you either remove `~/.fscrawler/sic_list/_status.json` or run with `--restart` option?

**Comment by dadoonet** [comment]
I'm also suprised by this config:

```json
{
  "name" : "sic_list",
  "fs" : {
    "url" : "/home/shadi/files",
    "update_rate" : "1m",
    "json_support" : false,
    "filename_as_id" : false,
    "add_filesize" : false,
    "remove_deleted" : false,
    "store_source" : true,
    "index_content" : false,
    "indexed_chars" : "100.0%",
    "attributes_support" : false,
    "raw_metadata" : false,
    "xml_support" : false,
    "index_folders" : false,
    "lang_detect" : false
  },
  "elasticsearch" : {
    "nodes" : [ {
      "host" : "myhostname",
      "port" : 9200
    } ],
    "index" : "sic_list",
    "type" : "doc",
    "bulk_size" : 0
  }
}
```

`"bulk_size" : 0`: Why 0 here? Did you change the default value explicitly?

**Comment by shadiakiki1986** [comment]
Hello. About the logs with `not modified`, I must have pasted the wrong pastebin link in my comment. I had already paid attention to removing the `status.json` file. I'll make a new pastebin link and fix my comment. About `bulk_size`, no I don't explicitly set it. In any case, it is a setting related to elasticsearch (as I understand the documentation), and not related to getting the file content, right?

**Comment by dadoonet** [comment]
Yeah you're right but I'm trying to find any clue which might explain this weird thing.

Can you share also your document?

**Comment by shadiakiki1986** [comment]
Please look at the logs [here](https://travis-ci.org/shadiakiki1986/docker-fscrawler/jobs/194695274)

**Comment by dadoonet** [comment]
Can you run something like `cat /root/files/test.txt` from your docker instance so we know what exactly is the content we are supposed to index?

**Comment by shadiakiki1986** [comment]
Check [here](https://travis-ci.org/shadiakiki1986/docker-fscrawler/jobs/194774406)
* non-null contents on [line 859](https://travis-ci.org/shadiakiki1986/docker-fscrawler/jobs/194774406#L859)
* missing contents tag on [line 831](https://travis-ci.org/shadiakiki1986/docker-fscrawler/jobs/194774406#L831)

**Comment by shadiakiki1986** [comment]
Btw, I took the freedom to open a couple of issues, which I saw while testing fscrawler, *separately*. I hope you don't mind :)

**Comment by shadiakiki1986** [comment]
I figured out the problem now. The readme says that `index_content` by default is true, but apparently it's coming up as `false` by default.

**Comment by dadoonet** [comment]
No. It's true by default unless you modify it: https://github.com/dadoonet/fscrawler/blob/master/src/main/java/fr/pilato/elasticsearch/crawler/fs/meta/settings/Fs.java#L62-L62

**Comment by dadoonet** [comment]
Ha! Indeed it's actually true by default but only if you generate the job with FS Crawler.
If you do it manually, it's actually false.

Thanks a lot for finding this nasty bug.

I know there are some others which I'm going to fix now.
