### ISSUE TITLE
`filename_as_id: true` not working?

### ISSUE THREAD

**Issue by shadiakiki1986** [dadoonet/fscrawler#282]
[Here](https://travis-ci.org/shadiakiki1986/docker-fscrawler/jobs/194745566) are logs of a fscrawler 2.2 run on travis
* [line 671](https://travis-ci.org/shadiakiki1986/docker-fscrawler/jobs/194745566#L671) shows `filename_as_id: true`
* [line 862](https://travis-ci.org/shadiakiki1986/docker-fscrawler/jobs/194745566#L862) shows that the ID is not the filename
* [line 884](https://travis-ci.org/shadiakiki1986/docker-fscrawler/jobs/194745566#L884) shows that using the filename as ID to query elasticsearch returns a MISS

**Comment by dadoonet** [comment]
`filename_as_id: true` works only for Json documents or xml documents. See https://github.com/dadoonet/fscrawler#using-filename-as-elasticsearch-_id

That said, I think that it should be users responsability to do that or not. I'm going to change that.
