### ISSUE TITLE
bulksize is 0 regardless of settings

### ISSUE THREAD

**Issue by shadiakiki1986** [dadoonet/fscrawler#283]
The following logs show that I set `bulk_size` in my job settings on [line 897](https://travis-ci.org/shadiakiki1986/docker-fscrawler/jobs/194774406#L897), but it shows up as 0 in the fscrawler trace on [line 674](https://travis-ci.org/shadiakiki1986/docker-fscrawler/jobs/194774406#L674)

**Comment by dadoonet** [comment]
I think you have something wrong on your end but I can not explain it yet.
I added a line in the bulk processor builder:

```java
logger.debug("Creating a bulk processor with size [{}], flush [{}], pipeline [{}]", bulkSize, flushInterval, pipeline);
```

* `bin/fscrawler --config_dir ./tmp test --loop 1 --debug`
* Press y to create the first job
* Modify job `./tmp/test/_settings.json`:

```json
{
  "name" : "test",
  "fs" : {
    "url" : "/tmp/es",
    "update_rate" : "15m",
    "json_support" : false,
    "filename_as_id" : false,
    "add_filesize" : true,
    "remove_deleted" : true,
    "store_source" : false,
    "index_content" : true,
    "attributes_support" : false,
    "raw_metadata" : true,
    "xml_support" : false,
    "index_folders" : true,
    "lang_detect" : false
  },
  "elasticsearch" : {
    "nodes" : [ {
      "host" : "127.0.0.1",
      "port" : 9200,
      "scheme" : "HTTP"
    } ],
    "type" : "doc",
    "bulk_size" : 10,
    "flush_interval" : "15s"
  },
  "rest" : {
    "scheme" : "HTTP",
    "host" : "127.0.0.1",
    "port" : 8080,
    "endpoint" : "fscrawler"
  }
}
```
* Start again with `bin/fscrawler --config_dir ./tmp test --loop 1 --debug`

Here is the log I can see:

```
15:10:28,719 DEBUG [f.p.e.c.f.c.BulkProcessor] Creating a bulk processor with size [10], flush [15s], pipeline [null]
```

So can you test [this latest SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/fr/pilato/elasticsearch/crawler/fscrawler/2.2-SNAPSHOT/fscrawler-2.2-20170124.141629-126.zip) and check if you are seing the same line I have?

**Comment by shadiakiki1986** [comment]
This is really silly. I was using `bulksize` instead of `bulk_size`. (No underscore).
Perhaps it's a good idea to throw an error upon seeing invalid fields in the settings.json file?

**Comment by dadoonet** [comment]
So closing this issue. I agree I could make parsing more strict. I'll think about it.
