### ISSUE TITLE
fscrawler doesn't work on windows

### ISSUE THREAD

**Issue by xsallowed** [dadoonet/fscrawler#289]
when ever i try to fscralwer in windows it gives an error saying:

"The system cannot find the path specified."

Help needed!!!

**Comment by dadoonet** [comment]
Can you try the SNAPSHOT version? There is a link in the readme file?

Is this message appears when you try to launch FSCrawler? Or later in logs?

**Comment by xsallowed** [comment]
I am using 2.0.0 but i tried 2.1 as well and both versions gave the same error.

It appears on the screen immediately i run fscrawler. I think i doesnt even invoke java and i get the error

**Comment by dadoonet** [comment]
Can you try 2.2-SNAPSHOT?

Just want to make sure it still appears in recent version.

**Comment by xsallowed** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; }  Thanks for the info can you forward the link. For SNAPSHOT version


ThanksTS

On Thursday, January 26, 2017, 6:56 PM, David Pilato <notifications@github.com> wrote:


Can you try 2.2-SNAPSHOT?

Just want to make sure it still appears in recent version.

**Comment by dadoonet** [comment]
https://github.com/dadoonet/fscrawler#download-fscrawler (look at the bottom of this section)

**Comment by xsallowed** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; }  Same error I used the 2.2-SNAPSHOT version (the most recent one ) and it is still showing the same error

ThanksTS

On Thursday, January 26, 2017, 6:56 PM, David Pilato <notifications@github.com> wrote:


Can you try 2.2-SNAPSHOT?

Just want to make sure it still appears in recent version.

**Comment by dadoonet** [comment]
Ok thank you!

I now need to start a VM and fix that I guess :)

**Comment by xsallowed** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; }  Oh ok just to give you information I am using fscrawler on windows 7 
Can you suggest that if I don't give it parameters will it give errror? 


ThanksTS

On Thursday, January 26, 2017, 8:23 PM, David Pilato <notifications@github.com> wrote:


Ok thank you!

I now need to start a VM and fix that I guess :)

**Comment by dadoonet** [comment]
I did not reproduce on a Windows VM.

Can you copy here the result of `set` in a cmd shell?

**Comment by ploncker** [comment]
having the same issue on win10 fscrawler2.2 I can send you the output from set, just cant post in public

**Comment by dadoonet** [comment]
@ploncker yes please. david at pilato dot fr

**Comment by xsallowed** [comment]
I am sorry david 
I did not see your earlier response though i was waiting for a solution. I will send you my set output in sometime, in case if ploncker has already sent please suggest the problem and solution

**Comment by dadoonet** [comment]
For now I think you didn't set JAVA_HOME.

Did you?

**Comment by ploncker** [comment]
after setting the JAVA_HOME for version 2.2 I get nothing, it hangs. 
For version 2.1 I'm getting this error:

Exception in thread "main" java.nio.file.NoSuchFileException: C:\Users\usr\.fscrawler\test\_settings.json
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230)
        at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
        at java.nio.file.Files.newOutputStream(Files.java:216)
        at java.nio.file.Files.write(Files.java:3292)
        at fr.pilato.elasticsearch.crawler.fs.meta.MetaFileHandler.writeFile(MetaFileHandler.java:80)
        at fr.pilato.elasticsearch.crawler.fs.meta.settings.FsSettingsFileHandler.write(FsSettingsFileHandler.java:56)
        at fr.pilato.elasticsearch.crawler.fs.FsCrawler.main(FsCrawler.java:181)

**Comment by ploncker** [comment]
Okay, I created the directory and that fixed the problem.

**Comment by ploncker** [comment]
Okay I have Xpack installed which requires a login to elasticsearch. Is there a way to pass a usr and passwd with fscrawler to access elasticsearch?

**Comment by dadoonet** [comment]
Yes there is but there is a bug currently reading the password from the CLI.
I need to fix it ASAP.

https://github.com/dadoonet/fscrawler/issues/312

**Comment by dadoonet** [comment]
Thanks for confirming it was JAVA_HOME. I'll try to detect it in the bat script and document it as well.

**Comment by ploncker** [comment]
Now getting:

Error while indexing content from [java.io.IOException: no active node found. Start an elasticsearch cluster first! Expecting something running at [127.0.0.1:9200]

But ES is up. I can pass curl commands to it, and it responds appropriately

**Comment by dadoonet** [comment]
With xpack?

**Comment by xsallowed** [comment]
This solved my problem !!! feeling embarrassed though, i should have seen that at the first place :P 

JAVA_HOME

**Comment by dadoonet** [comment]
I need to detect or document it. That's why I'm leaving this issue opened.

**Comment by ridzy22** [comment]
I have installed ES 7.17.4 and hence i have downloaded fscrawler es-7 2.9. Now, I am trying to run the following command:
"bin\fscrawler — config_dir ./DS data_science_index — loop 1"
but it shows that the syntax of the command is incorrect; even though everyone is using the same command and the same command is given in the user guide. Could you help me out please. 

Thank you :)
