### ISSUE TITLE
Not ingesting files with tilde ~ character in their name

### ISSUE THREAD

**Issue by trorbyte** [dadoonet/fscrawler#291]
The code currently excludes 'temporary' files that are normally prefixed with a tilde ~ character. However the check uses a String.contains check; when we really should check for filenames starting with ~. I've had several files dropped because they had ~ in the name.

Alternatively should this be a default exclusion policy rather than hardcoded?

**Comment by dadoonet** [comment]
Thanks for reporting.

> However the check uses a String.contains check

Yeah. IIRC I had some temporary files like `myFile.txt~` on some OS.

> Alternatively should this be a default exclusion policy rather than hardcoded?

That's definitely the way to go. Thanks for proposing.
