### ISSUE TITLE
FSCrawler - can it parsing mixed file type

### ISSUE THREAD

**Issue by dgilbert002** [dadoonet/fscrawler#310]
Hi there. 

I have a folder with a number of files i.e. word, powerpoint, excel, pdf, pst and ost files. The type that I have specified at the bottom of the _settings.json is "doc". Would this mean that it will only parse the word documents or anything that it sees as a microsoft office document? 

I work in a forensic environment and would really like to use this to parse/harvest all files on a target's computer that would allow us to prepare to create a forensic image of the target's computer. Alternately, it would also be great if FSCrawler could open EWF (expert witness format) files like EnCase (E01) or DD (raw) images etc and parse the contents into an ES database for large scale investigations.

**Comment by dadoonet** [comment]
> Would this mean that it will only parse the word documents or anything that it sees as a microsoft office document?

No. `type` is only the elasticsearch type name. It does not relate to the type of document which will be parsed.

FSCrawler only exposes what Tika exposes. May be you can check if this is supported, if this need has already been expressed in JIRA and if not, open a JIRA ticket?
