### ISSUE TITLE
elasticsearch.password option is not read

### ISSUE THREAD

**Issue by hlecorche** [dadoonet/fscrawler#312]
elasticsearch.password option is not readed because there is `@JsonIgnore` annotation in `Elasticsearch` class :

https://github.com/dadoonet/fscrawler/blob/master/src/main/java/fr/pilato/elasticsearch/crawler/fs/meta/settings/Elasticsearch.java#L189

**Comment by dadoonet** [comment]
Ha! I have been wondering myself about this some days ago and you're right actually.
Thanks for testing and reporting!
