### ISSUE TITLE
parsing_exception when use remove_deleted on ES 5.x, 6.x

### ISSUE THREAD

**Issue by ggegelya** [dadoonet/fscrawler#315]
Hi. 
While trying to indexing files with fscrawler 2.1 on ES 5.x, got an elastic exception, if remove_deleted option is set to true. 
With debug run, i can see that all files are indexed successfully (with some not important errors and warnings), and then it try to search removed files with wrong query parameter 'field'

Exception caused by code in FsCrawlerImpl on 461 line. It is also can be seen when running with debug mode.

Error text:

`{"error":{"root_cause":[{"type":"parsing_exception","reason":"The field [fields] is no longer supported, please use [stored_fields] to retrieve stored fields or _source filtering if the field is not stored","line":1,"col":11}],"type":"parsing_exception","reason":"The field [fields] is no longer supported, please use [stored_fields] to retrieve stored fields or _source filtering if the field is not stored","line":1,"col":11},"status":400}`

**Comment by dadoonet** [comment]
Did you try with 2.2?

**Comment by dadoonet** [comment]
Closing as no feedback.
Feel free to reopen or comment.
