### ISSUE TITLE
filename_as_id=true leads to deleted files not getting deleted from the index

### ISSUE THREAD

**Issue by shadiakiki1986** [dadoonet/fscrawler#336]
Even though I used `filename_as_id=true`, and I can see in the elasticsearch index that the filename is used in the `_id` field, the logs show that the deletion of the entry from the index still uses the hash instead of the filename as ID, leading to the entry in the index not getting deleted
```
fscrawler_1       | 16:20:34,172 DEBUG [f.p.e.c.f.FsCrawlerImpl] Deleting from ES sic-namecheck, doc, b3ab13166d8b47b2ee6c797aa08992e
fscrawler_1       | 16:20:34,172 DEBUG [f.p.e.c.f.c.BulkProcessor] {"delete":{"_index":"sic-namecheck","_type":"doc","_id":"b3ab13166d8b47b2ee6c797aa08992e"}}
```

Edit: I confirm that when `filename_as_id=false`, the entry is properly deleted from the index

**Comment by dadoonet** [comment]
Thanks for reporting! Much appreciated.

It should be ok now.
