### ISSUE TITLE
Docs not getting deleted from index, when the file is deleted from the folder

### ISSUE THREAD

**Issue by sirgyula** [dadoonet/fscrawler#337]
I'm using the newest fscrawler (2.2) and ElasticSearch (5.2.1).
I've made my config file for fscrawler, set `remove_deleted : true`, but when I'm deleting a file from the watched folder, the index will still contain the deleted file's details in ES, and there is a docs.deleted = 1 for the index.
I've tried `_forcemerge`, but the file is still in the index (but the docs.deleted is now set to 0)

**Comment by dadoonet** [comment]
@sirgyula can you run a full example with fscrawler started with `--debug` option and paste the logs please?

**Comment by sirgyula** [comment]
@dadoonet thanks for the help.
here is a log with debug option.
the crawler is set to 1m schedule. the first run, it indexed the files in the folder, then I've removed `excelxls.xls` file.

[fscrawler_log.txt](https://github.com/dadoonet/fscrawler/files/830123/fscrawler_log.txt)

**Comment by dadoonet** [comment]
So you are using `filename_as_id` option I think, right?
If so this issue should be solved now in 2.3.0-SNAPSHOT with #336

**Comment by sirgyula** [comment]
Yes, I'm using that option.
Right now, trying to run the snapshot, updated log4j, but the still having `NoClassDefFoundError` issues with elasticsearch

**Comment by dadoonet** [comment]
I don't understand the relationship between `NoClassDefFoundError`, log4J and FSCrawler.

I'm closing this issue as it's a duplicates of #336.

**Comment by sirgyula** [comment]
Sorry if I'm being unclear. For the snapshot to work, I had to place the new log4j to the lib/ folder. After this, there is an other error:
Exception in thread "main" java.lang.NoClassDefFoundError: org/elasticsearch/client/ResponseException
    at fr.pilato.elasticsearch.crawler.fs.client.ElasticsearchClientManager.start(ElasticsearchClientManager.java:62)
    at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl.start(FsCrawlerImpl.java:164)
    at fr.pilato.elasticsearch.crawler.fs.FsCrawler.main(FsCrawler.java:233)

**Comment by dadoonet** [comment]
Did you download the snapshot from https://oss.sonatype.org/content/repositories/snapshots/fr/pilato/elasticsearch/crawler/fscrawler/2.3-SNAPSHOT/ ?

**Comment by sirgyula** [comment]
oh gosh, it's working now. I've only downloaded the jar, didn't see the zip first.
Also, the file deletion works now, thanks for the help!
