### ISSUE TITLE
Avoid bulk queue rejection

### ISSUE THREAD

**Issue by babadofar** [dadoonet/fscrawler#339]
There should be some mechanism to avoid the situation where elasticsearch rejects bulk inserts. This happens when elasticsearch is unable to cope with incoming bulk requests, there is an internal bulk queue in elasticsearch with a maximum size of 50.  
One way to do this could be to read out the current bulk queue size before attempting to add a new bulk request. If the bulk queue is approaching maximum, wait for some time before trying again.  The _cat/thread_pool  API can be used to check queue status.

**Comment by dadoonet** [comment]
The other way of doing that as we discussed at elasticON would be to implement a catch/retry mechanism with an exponential backoff policy system.
So basically instead of monitoring bulk queue, catch the failure and retry later but slow down the input part (the crawling part).

**Comment by babadofar** [comment]
:) Nice to meet you in person David! 
Yes, but as far as I remember there were no errors returned from the bulk request, it seemed to me it happened at a later stage inside of the elasticsearch index processing. But of course this only happened in production, I'm not totally clear on the details, it needs to be reproduced in a controlled fashion to see exactly what goes on. If we can catch errors that would be easier .

**Comment by dadoonet** [comment]
I guess we could try to reproduce by setting a ridiculous bulk queue size in elasticsearch node and then overload FSCrawler.
