### ISSUE TITLE
add fscrawler_path to the virtual  and real paths on folders

### ISSUE THREAD

**Issue by trorbyte** [dadoonet/fscrawler#342]
The fscrawler_path was added to the path elements on the doc type but not the real / virtual fields on the folder type. Adding it on the folder type would allow similar path based querying on folder types.

**Comment by dadoonet** [comment]
I think I fixed it with #353 but unsure if this is what you meant.
Could you try the snapshot and close this issue the last implementation solve the feature request you asked for here?

Thanks!

**Comment by dadoonet** [comment]
I'm closing. Assuming the fix is correct.

Thanks for reporting.
