### ISSUE TITLE
Error while indexing content from [path]: entity content is too long [134161442] for the configured buffer limit [104857600]

### ISSUE THREAD

**Issue by candido1212** [dadoonet/fscrawler#345]
Hi, 

I can not resolve this problem, i try to change this:
https://www.elastic.co/guide/en/elasticsearch/reference/current/indexing-buffer.html

but, not resolve.

```
11:15:17,277 DEBUG [f.p.e.c.f.f.FileAbstractor] 1715 local files found
11:19:16,623 WARN  [f.p.e.c.f.FsCrawlerImpl] Error while indexing content from /webphp/testes/elastic/17021513: entity content is too long [134161442] for the configured buffer limit [104857600]
```

**Comment by dadoonet** [comment]
Could it be possible to share your file somewhere?

And also your configuration of the FSCrawler job?

**Comment by candido1212** [comment]
The files I'm indexing, are PDF. And I can not share because they are private.

The configuration file:

```
{
  "name" : "rh",
  "fs" : {
    "url" : "/webphp/testes/elastic/17021513",
    "update_rate" : "10m",
    "excludes" : [ "~*" ],
    "json_support" : false,
    "filename_as_id" : false,
    "add_filesize" : true,
    "remove_deleted" : true,
    "add_as_inner_object" : false,
    "store_source" : false,
    "index_content" : true,
    "attributes_support" : false,
    "raw_metadata" : true,
    "xml_support" : false,
    "index_folders" : true,
    "lang_detect" : false,
    "continue_on_error" : true,
    "indexed_chars" : "1000000",
    "checksum": "SHA-1"
  },
  "elasticsearch" : {
    "nodes" : [ {
      "host" : "10.224.97.236",
      "port" : 9200,
      "scheme" : "HTTP"
    }
     ],
    "type" : "doc",
    "bulk_size" : 100,
    "flush_interval" : "15s"
  },
  "rest" : {
    "scheme" : "HTTP",
    "host" : "127.0.0.1",
    "port" : 8080,
    "endpoint" : "fscrawler"
  }
}
```

**Comment by dadoonet** [comment]
I believe this is caused by the default limit elasticsearch set on the HTTP module: `http.max_content_length` is by default `100mb`.
See https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-http.html

May be try to change this value or reduce the bulk size. Instead of `"bulk_size" : 100`, try with `80`...
Note that I should may be add support for a bulk size limit in bytes instead of only having a limit in number of documents...
