### ISSUE TITLE
New copied files on mounted Cifs-share are not indexed

### ISSUE THREAD

**Issue by TheReal1604** [dadoonet/fscrawler#347]
Hi @dadoonet,

thanks for this great tool, unfortunately I got a "crazy" issue with the crawler, maybe you got an idea. First this is my fscrawler job config:

```
{
  "name" : "crawl_cifsshare",
  "fs" : {
    "url" : "/mnt/cifsshare",
    "update_rate" : "5m",
    "excludes" : [ "~*" ],
    "json_support" : false,
    "filename_as_id" : false,
    "add_filesize" : true,
    "remove_deleted" : true,
    "add_as_inner_object" : false,
    "store_source" : false,
    "index_content" : false,
    "attributes_support" : true,
    "raw_metadata" : true,
    "xml_support" : false,
    "index_folders" : true,
    "lang_detect" : false
  },
  "elasticsearch" : {
    "username" : "fscrawler",
    "password" : "YourCrawlerPassword",
    "nodes" : [ {
      "host" : "127.0.0.1",
      "port" : 9200,
      "scheme" : "HTTP"
    } ],
    "index" : "myindex",
    "type" : "doc",
    "bulk_size" : 100,
    "flush_interval" : "5s"
  },
  "rest" : {
    "scheme" : "HTTP",
    "host" : "127.0.0.1",
    "port" : 8080,
    "endpoint" : "fscrawler"
  }
}
```

I mounted a cifsshare to my local filesystem on `/mnt/cifsshare`. The first indexing runs fine, but if I now !copy! new folders with content to that share, only the new folders are indexed, not the files.

So just say we have the mount point:

`/mnt/cifsshare` 

I copy data from a windows system to the cifsshare via network drive mapping from another host to my ciffsshare. (For Example FolderA)

If i now try an `ls` on `/mnt/cifsshare` I can see all the new folders and files: `/mnt/cifsshare/FolderA` and `mnt/cifsshare/FolderA/fileB`. I have also more folders under `FolderA` (`mnt/cifsshare/FolderA/FolderC/`).

On the terminal all looks fine.. if i now try an additional run with fscrawler, only all new folders get indexed. So I see the following new entries in elasticsearch:

`/mnt/cifsshare/FolderA`
`/mnt/cifsshare/FolderA/FolderC`

But i dont see the files that these folders containing in elasticsearch:

`/mnt/cifsshare/FolderA/fileB`

The funny thing is.. just say `fileB` is an excel file. If I open the excel table and edit it with an microsoft excel from the windows system and save it again in the folder there it was.. (on the linux system `/mnt/cifsshare/FolderA/fileB.xlsx`) It is indexed in the next run of fscrawler.

Do you have any idea what is causing this crazy issue? Or how is the suggested method to crawl cifs / smb shares? I access the cifsshare with the same user as on the windows system. (So in my perspective its not permission related)

**Comment by dadoonet** [comment]
I think it's an issue with dates. It has always been a nightmare depending on the OS.
I definitely need to find a better way to detect changes. If you "touch" the root dir, that might be enough. Unsure though.

I need to dig more.

**Comment by TheReal1604** [comment]
@dadoonet I tested a bit more and if I create a new job and a new index it is indexed correctly.

**Comment by dadoonet** [comment]
Of course. It's the same effect as using the restart option which basically reads again all the content.

**Comment by TheReal1604** [comment]
Ahh, maybe i found the problem with the function that compares that:

https://github.com/dadoonet/fscrawler/blob/848e72bcfcf3fa6921517cba1b6e23962ac9e28b/src/main/java/fr/pilato/elasticsearch/crawler/fs/FsCrawlerImpl.java#L383

You just compare the lastmodifiedtimestamp with the last run timestamp from the fscrawler job to check if it should be scanned? Right?

Maybe its better to have something like a checksum to decide if something has changed in a directory.. or a file? Hmmm. But this could be very cpu intense. 😀

**Comment by TheReal1604** [comment]
Just another idea.. you can compare the creation date of the file like you do it now with the "last modifed" date. The creation date is touched if you copy files from one to another folder (tested this just right now..) so fscrawler can recognize this copied files also.

![image](https://cloud.githubusercontent.com/assets/5877910/24375905/5e92a6a0-133a-11e7-8bfb-ff695597e66f.png)

![image](https://cloud.githubusercontent.com/assets/5877910/24375936/7195372c-133a-11e7-9133-efd8bbc54f65.png)

Its the same file - just copied. The creation date is in the red square and the last modified time is preserved. Is there any other reason why you are comparing the last modified time of a file for this kind of check?

(https://github.com/dadoonet/fscrawler/issues/349)

**Comment by dadoonet** [comment]
IIRC there are some differences between windows/linux and when you copy or move files.

I need to add tests for that I think.

**Comment by kapersoft** [comment]
I had the same problem with copied files did not getting indexed. As a work-around I changed the ~/.fscrawler/demo/_status.json to 
```json
{
  "name" : "demo",
  "lastrun" : "1970-01-01T00:00:00.000",
  "indexed" : 0,
  "deleted" : 0
}
```
And set the file to read-only using `sudo chattr +i ~/.fscrawler/demo/_status.json`.

For me this work-around worked fine. I don't recommend to use this work-around in a large production environment because all files will be updated in the index on every loop!

**Comment by dadoonet** [comment]
I believe that the right fix would be to have different implementations of the crawler depending on the FS type.
I think I can look at it when I'll split the project into modules #367 so I could more easily add new implementations.

**Comment by dadoonet** [comment]
I think that this is related indeed to dates and I just added some documentation about moving files in https://github.com/dadoonet/fscrawler#moving-files-to-a-watched-directory.

Basically I think that after having copied/moved files from another FS you should run a `touch` on those files.

I hope that the next implementation (#399) will fix that though but for now that might be the right workaround.

I'm closing this issue if you don't mind in favor of #399. Thanks all for the detailed reports and workarounds :)
