### ISSUE TITLE
Add creation date of files to the default mappings

### ISSUE THREAD

**Issue by TheReal1604** [dadoonet/fscrawler#349]
Hi @dadoonet,

can you please add the "creation_Date" of a file/folder to the default mappings? Or explain how to do it on myself? I edited already the default mappings - not surprising that it only creates the field in the elasticsearch index and dont fill it. 😬 I dont found a way to see just the output from fscrawler.. is there a way? So maybe it gives more output as is used in the default mapping?

Thanks.

**Comment by dadoonet** [comment]
Indeed. That'd be a nice idea.
I'll think about it

**Comment by TheReal1604** [comment]
This would be really great! I try to build a metadata search machine for our fileserver. This field is nice for historical graphs.

**Comment by dadoonet** [comment]
That has been implemented hopefully with #580

**Comment by TheReal1604** [comment]
@dadoonet awesome, thanks!
