### ISSUE TITLE
Timestamp "last modified" and "indexed time" shifted + 2h

### ISSUE THREAD

**Issue by TheReal1604** [dadoonet/fscrawler#350]
Hi @dadoonet ,

maybe you got an idea.. 

I try to reindex my files every 1h with the following command (via cron)

`<path to>/fscrawler <job_name> --restart --loop 1`

This is working fine, but the last modified timestamp is two hours in the future and the last indexed date is also moved 2 hours in the future.

The time on my ubuntu host seems to be configured okay. `date` give the right time. (28.03.2017 11:55:..)

![image](https://cloud.githubusercontent.com/assets/5877910/24403212/1f45405c-13bc-11e7-825d-bc00cf75c42f.png)

If I look at my fileserver, i found that the file was last modified on 11:55. But the indexed time is 13:55.

Do you have any idea why this is happening? 

EDIT: BTW, the _status.json file has the correct timestamp.

**Comment by dadoonet** [comment]
I think you are looking at this in Kibana. Kibana is using your browser time to apply an offset.
Can you just run a `GET /_search` query and check what are the dates actually stored in elasticsearch?

**Comment by TheReal1604** [comment]
Yes, this is right. But the crazy thing is I set the timezone in kibana already to Europe/berlin ... The result directly from elasticsearch is OK.

**Comment by TheReal1604** [comment]
https://discuss.elastic.co/t/kibana-show-wrong-time-compared-to-the-time-value-indexed-in-elasticsearch/43992

Found this thread in the elasticsearch forum.. maybe this could be my issue. Is there a way to add a timezone field? (or fix this on another way?)

**Comment by dadoonet** [comment]
> Is there a way to add a timezone field?

This is exactly the issue. I'm actually not using any timezone information so elasticsearch supposes it as UTC. Which is not.
That's why I'm keeping your issue opened as I believe I need to add a timezone setting in job configuration and may be try to autodetect it based on what the JVM can tell me.

**Comment by TheReal1604** [comment]
> That's why I'm keeping your issue opened as I believe I need to add a timezone setting in job configuration and may be try to autodetect it based on what the JVM can tell me.

Awesome. Thanks.

**Comment by dadoonet** [comment]
So apparently I did that change (20b9a338650ed3a98303922d3fbe1e669a88434b) on purpose. See #245.

I fixed something but introduced another bug apparently... Need to find a global fix now :)
