### ISSUE TITLE
Two folder entries for the same folder 

### ISSUE THREAD

**Issue by trorbyte** [dadoonet/fscrawler#351]
I'm trying to figure out how the folder entries are represented, in order that I can traverse them via a UI.

I note that two folder entries are created per folder - one relative to its parent and one relative to itself. Is this intentional or a defect? 

```json
"hits": [
      {
        "_index": "timemachine",
        "_type": "folder",
        "_id": "ae8f8f73818eb5f2298ccaf92e70b3",
        "_score": 1.3530767,
        "_source": {
          "encoded": "8083584abf261c9cf4d6f7d62e184e",
          "root": "c79170dd1de552758f2fb3f363a44327",
          "virtual": "/DVDProjects",
          "real": "DVDProjects"
        }
      },
      {
        "_index": "timemachine",
        "_type": "folder",
        "_id": "8083584abf261c9cf4d6f7d62e184e",
        "_score": 0.99057835,
        "_source": {
          "encoded": "c79170dd1de552758f2fb3f363a44327",
          "root": "c79170dd1de552758f2fb3f363a44327",
          "virtual": "/",
          "real": "DVDProjects"
        }
      }, 
```

**Comment by dadoonet** [comment]
Might be a bug indeed.

**Comment by trorbyte** [comment]
I'm using 2.2 build against a 1.7.6 elastic stack

**Comment by dadoonet** [comment]
It's better if you can use the latest SNAPSHOT but I feel like this bug will still there

**Comment by trorbyte** [comment]
I thought you were dropping elastic 1x support post the 2.2 build?

**Comment by dadoonet** [comment]
It's not officially supported anymore but it still works with 1.7. My commit just removed integration tests: https://github.com/dadoonet/fscrawler/commit/b8d5b46b17beee42c47ab5be3a5433aa016da618

**Comment by trorbyte** [comment]
ok I'll see if I get the same issue with SNAPSHOT

**Comment by trorbyte** [comment]
Only one folder at present - but the job is still running

**Comment by dadoonet** [comment]
Great. Please close the issue if at the end you don't see any duplicate anymore.

**Comment by dadoonet** [comment]
I'm closing but feel free to reopen or comment if this is happening again.
