### ISSUE TITLE
fscrawler requests are deprecated by elasticsearch

### ISSUE THREAD

**Issue by xsallowed** [dadoonet/fscrawler#354]
fscrawler : fscrawler-2.3-SNAPSHOT (fscrawler-2.3-20170312.164343-20.zip)
elasticsearch : elasticsearch-5.3.0
I am trying to run fscrawler on my windows computer. Wonder what could be the issue that i am getting following error for my docs:

18:08:09,802 WARN  [o.e.c.RestClient] request [POST http://127.0.0.1:9200/_bulk]  returned 1 warnings: [299 Elasticsearch-5.3.0-3adb13b "Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type ] header." "Mon, 03 Apr 2017 14:08:09 GMT"]

**Comment by dadoonet** [comment]
Thanks! I'm going to fix it in few minutes.
