### ISSUE TITLE
Can we tune index.mapping.total_fields.limit setting on Elastic?

### ISSUE THREAD

**Issue by yonyonson** [dadoonet/fscrawler#356]
I am running Elastic 5.3 with fsCrawler 2.2 and indexing an email archive in RFC822 format. I am runinng out of fields on the index side quite quickly and start getting error messages that are described here: [One of related StackOverflow threads](http://stackoverflow.com/questions/40857060/elasticsearch-bulk-upload-error-with-php-limit-of-total-fields-1000-in-index). Exception reads as `Limit of total fields [1000] in index [email] has been exceeded`.

I am to increase parameter `index.mapping.total_fields.limit` on the index settings as described here: [Elastic Reference](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html#mapping-limit-settings).

Question is: Is it possible to transfer this index setting through fsCrawler config? Basically, does fsCrawler allows passing through custom index settings?

**Comment by dadoonet** [comment]
No but it's quite easy to define an index template in elasticsearch. Then any index created after and matching the index pattern will benefit from it.

Would that work for you ?

**Comment by yonyonson** [comment]
I will do that, it will most likely work :) Many thanks!
