### ISSUE TITLE
un-included/un-indexed files

### ISSUE THREAD

**Issue by swsmit07** [dadoonet/fscrawler#358]
I'm crawling a local file share and the results that end up in my index are far short of the number of files i have within the directory. I don't see any documentation that itemizes specific files only and I've even tried to force adding files via "includes" statements. Is there a limitation, bug, and/or configuration that supports indexing any/all files in a directory?

**Comment by dadoonet** [comment]
What is your FSCrawler config file?
You can run with debug option to see what is happening?

**Comment by swsmit07** [comment]
Great, thank you!  I do see that the crawler throws errors for text/formatting it cannot parse but it also looks like because of that its not making an entry of a file in my index. It also is not showing .png files, checking on other extensions.

**Comment by dadoonet** [comment]
Can you share the logs?

**Comment by dadoonet** [comment]
No further news. I'm closing but feel free to reopen and provide more details.
