### ISSUE TITLE
Index file metadata with not enough read rights on a file

### ISSUE THREAD

**Issue by TheReal1604** [dadoonet/fscrawler#362]
Hi @dadoonet,

we index a mounted cifs share with special permissions, this means the user can only view the metadata of the file but doesnt have the right to read the files content.

I now get an error from the crawler:
`09:33:39,380 WARN  [f.p.e.c.f.FsCrawlerImpl] Error while indexing content from /mnt/cifs/share: /mnt/cifs/share/folder1/excelfile.xlsx (Permission denied)
`
My settings file for this job looks like this:

```
{
  "name" : "crawl_share",
  "fs" : {
    "url" : "/mnt/cifs/share",
    "update_rate" : "2h",
    "excludes" : [ "~*" ],
    "json_support" : false,
    "filename_as_id" : false,
    "add_filesize" : true,
    "remove_deleted" : true,
    "add_as_inner_object" : false,
    "store_source" : false,
    "index_content" : false,
    "attributes_support" : true,
    "raw_metadata" : false,
    "xml_support" : false,
    "index_folders" : true,
    "lang_detect" : false
  },
  "elasticsearch" : {
    "nodes" : [ {
      "host" : "127.0.0.1",
      "port" : 9200,
      "scheme" : "HTTP"
    } ],
    "username" : "myuser",
    "password" : "mypass",
    "index" : "cifsshare",
    "type" : "doc",
    "bulk_size" : 2000,
    "flush_interval" : "20s"
  },
  "rest" : {
    "scheme" : "HTTP",
    "host" : "127.0.0.1",
    "port" : 8080,
    "endpoint" : "fscrawler"
  }
}
```
In my understanding he should not index the content of the file - **"index_content": false** - but he gets an error that he can´t index that content. 

We want to give this user only the rights he need and he doesnt need to read the content of the whole fileserver.

Any idea what is causing this or how we can workaround it?

Thanks in advance!

**Comment by dadoonet** [comment]
I think I should change the message from `Error while indexing content from {}` to `Error while crawling {}`.

I'm going to leave it open so I'll fix the message.

But your problem is actually `/mnt/cifs/share/folder1/excelfile.xlsx (Permission denied)`. Probably the user who is running FSCrawler does not have access to this file?

**Comment by TheReal1604** [comment]
@dadoonet yeah, he has not the permission to read the file, but all the metadata.

We checked the permissions with Get-Childitem and on the linux shell all was looking fine and he can read the metadata:

linux: ls -lisan

`81066 28 -rwxr-xr-x 1 0 0 27108 Jun  5  2015 excelfile.xlsx`

on windows with powershell:

```
Get-Childitem ./excelfile.xlsx | fl *


BaseName          : excelfile
Mode              : -a---
Name              : excelfile.xlsx
Length            : 81066
DirectoryName     : X:\
Directory         : X:\
IsReadOnly        : False
Exists            : True
FullName          : X:\excelfile.xlsx
Extension         : .xlsx
CreationTime      : 05.06.2015 11:45:55
CreationTimeUtc   : 05.06.2015 09:45:55
LastAccessTime    : 21.04.2017 10:47:22
LastAccessTimeUtc : 21.04.2017 08:47:22
LastWriteTime     : 05.06.2015 15:10:16
LastWriteTimeUtc  : 05.06.2015 13:10:16
Attributes        : Archive
```

So the permissions should be fine.

Which access rights the user needs at least?

**Comment by dadoonet** [comment]
Read access is enough I guess.

**Comment by TheReal1604** [comment]
We dont want to give him read access to the content.. just for security reasons. Because we also crawl sensitive data as a cronjob.

**Comment by dadoonet** [comment]
I see. So just collecting file name.

I need to look at it.

**Comment by dadoonet** [comment]
So I think I found the problem and I hopefully fixed it. \o/
Please can you try the latest SNAPSHOT which is available on Sonatype repo (see https://github.com/dadoonet/fscrawler#download-fscrawler for the link), and confirm that it works well for you now?

Thanks!

**Comment by TheReal1604** [comment]
@dadoonet Sry for the late response. With your fix it is working now! \o/

**Comment by dadoonet** [comment]
Awesome! Thanks for confirming!
