### ISSUE TITLE
Content type detection for rest requests is deprecated

### ISSUE THREAD

**Issue by Avec112** [dadoonet/fscrawler#363]
I am testing FSCrawler 2.2 with Elasticsearch 5.3.0 and just want to inform about a warning you might want to fix in the current snapshot.

`[299 Elasticsearch-5.3.0-3adb13b "Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header." "Sat, 22 Apr 2017 09:32:38 GMT"]`

There seems to have been a change in 5.3 since 5.2 from what [this link](https://github.com/olivere/elastic/issues/511) shows.

-Avec

**Comment by dadoonet** [comment]
Thanks for reporting. Actually a duplicate of #354 which has been fixed by updating elasticsearch client (#355).

**Comment by dvikasjain** [comment]
Hi, I am using fscrawler-2.3-20170519.213811-39 and elasticsearch-5.3.2. still getting same error when i run fs crawler.

**Comment by dadoonet** [comment]
@dvikasjain Can you share your FSCrawler and elasticsearch logs please?

That's super strange.

**Comment by dvikasjain** [comment]
[logs.zip](https://github.com/dadoonet/fscrawler/files/1044311/logs.zip)
Please have a look at logs attached.

**Comment by dvikasjain** [comment]
did you find something in logs?

**Comment by dadoonet** [comment]
Did not look yet. Traveling.

**Comment by dadoonet** [comment]
Can you share your FSCrawler logs please?

**Comment by dvikasjain** [comment]
i get this printed when i do "fscrawler testing" in my cmd 
![image](https://cloud.githubusercontent.com/assets/5399437/26782325/a885f296-4a10-11e7-9e7a-88d0d9184ddf.png)

**Comment by dadoonet** [comment]
Can you upgrade your elasticsearch version?

**Comment by dadoonet** [comment]
This has been fixed now with #380
