### ISSUE TITLE
how can fscrawler support chinese document？

### ISSUE THREAD

**Issue by 695172327** [dadoonet/fscrawler#368]
I  uploaded Chinese documents to es using fscrawler.  However, chinese document  encoding error occurred . How can fscrawler support chinese document？THX !

**Comment by dadoonet** [comment]
Can you share:

The logs
One of the documents which is causing the issue?

**Comment by 695172327** [comment]
I solved this problem. The cause of this error is related to the Linux encoding.Thanks！@dadoonet

**Comment by dadoonet** [comment]
Awesome! I think it deserves updating the README file then.
So I'm keeping this open as a "doc" issue.

Feel free to contribute a PR to the documentation if you wish.
I wonder BTW if I can implement some bootstrap checks when FSCrawler starts to have a better detection of that kind of issue.

**Comment by dadoonet** [comment]
I don't really know what has to be done on a Linux level.
I don't want to add documentation which is not clear enough so I'm just going to close the issue.

Feel free to add details about what you did or open a PR.
