### ISSUE TITLE
Char conversion exception on Windows 7

### ISSUE THREAD

**Issue by andresbh** [dadoonet/fscrawler#372]
running fscrawler 2.2 and 2.3 on windows 7 64bit, I get the following error

java.io.IOException: java.io.CharConversionException: Invalid UTF-8 start byte

while going through a couple of xml files. I cant figure out which start byte fscrawler means such that I can get rid of it and test further.

**Comment by dadoonet** [comment]
My guess is that you are hitting the same issue as https://github.com/dadoonet/fscrawler/issues/368#issuecomment-301999897

If so, adapt your JVM settings and try again.

If it works, please close this issue and may be comment what you exactly did to fix it?
Or better, send a PR to update the README for windows users?

**Comment by dadoonet** [comment]
No more feedback so I'm closing. Feel free to reopen if needed.
