### ISSUE TITLE
fscrawler is scanning on current directory

### ISSUE THREAD

**Issue by xsallowed** [dadoonet/fscrawler#391]
Hi,
I am trying to index the entire windows file system through fscrawler. how can i do that? I have tried putting Path as "//" did not work so i used "C:\\" but again it scanned only the path which was used to run the program from.
Thanks

**Comment by dadoonet** [comment]
What are the error messages? Did you try the SNAPSHOT version?

**Comment by xsallowed** [comment]
Yes I am using snapshot version: fscrawler-2.3-20170613.231356-48.
There is no error just that all docs that are indexed are from a folder which i am using to run fscrawler (e.g C:\ELK\fscrawler\xxx). 
Here is my config file


  "name" : "mycomputer",
  "fs" : {
    "url" : "C:\\",
    "update_rate" : "15m",
    "includes" : [ "*.*" ],
    "json_support" : false,
    "filename_as_id" : false,
    "add_filesize" : true,
    "remove_deleted" : true,
    "add_as_inner_object" : false,
    "store_source" : false,
    "index_content" : true,
    "attributes_support" : false,
    "raw_metadata" : true,
    "xml_support" : false,
    "index_folders" : true,
    "lang_detect" : false,
    "continue_on_error" : false,
    "pdf_ocr" : true
  },
  "elasticsearch" : {
    "nodes" : [ {
      "host" : "127.0.0.1",
      "port" : 9200,
      "scheme" : "HTTP"
    } ],
    "bulk_size" : 100,
    "flush_interval" : "5s"
  },
  "rest" : {
    "scheme" : "HTTP",
    "host" : "127.0.0.1",
    "port" : 8080,
    "endpoint" : "fscrawler"
  }
}

**Comment by dadoonet** [comment]
Can you try with /c:// ?

May be run with debug flag?

**Comment by xsallowed** [comment]
Error:

01:12:13,883 WARN  [f.p.e.c.f.FsCrawlerImpl] Error while crawling /C://: String
index out of range: -1
01:12:13,883 WARN  [f.p.e.c.f.FsCrawlerImpl] Full stacktrace
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:1967) ~[?:1.8.0_131]
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.indexDirect
ory(FsCrawlerImpl.java:740) ~[fscrawler-2.3-SNAPSHOT.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.run(FsCrawl
erImpl.java:347) [fscrawler-2.3-SNAPSHOT.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
01:12:13,919 DEBUG [f.p.e.c.f.FsCrawlerImpl] Fs crawler is going to sleep for 15

**Comment by dadoonet** [comment]
Can you run it using C:\ and trace option and paste the logs?

**Comment by xsallowed** [comment]
Managed to scan other folders as well but the issue persist because the program is unable to scan few files that are being used by other processors. So My question is why is the process breaking down instead of working around and scanning other directories. 

Bit Off the topic but is there a way to get hash value of the files within fscrawler data fields?


*******************=======================*********************************===========
13:59:38,199 WARN  [f.p.e.c.f.FsCrawlerImpl] Error while crawling C:\: C:\pagefi
le.sys (The process cannot access the file because it is being used by another p
rocess)
13:59:38,199 WARN  [f.p.e.c.f.FsCrawlerImpl] Full stacktrace
java.io.FileNotFoundException: C:\pagefile.sys (The process cannot access the fi
le because it is being used by another process)
        at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_131]
        at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_131]

        at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_13
1]
        at fr.pilato.elasticsearch.crawler.fs.fileabstractor.FileAbstractorFile.
getInputStream(FileAbstractorFile.java:60) ~[fscrawler-2.3-SNAPSHOT.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRec
ursively(FsCrawlerImpl.java:471) ~[fscrawler-2.3-SNAPSHOT.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.run(FsCrawl
erImpl.java:354) [fscrawler-2.3-SNAPSHOT.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
13:59:38,233 DEBUG [f.p.e.c.f.FsCrawlerImpl] Fs crawler is going to sleep for 15
m
13:59:39,828 DEBUG [f.p.e.c.f.c.BulkProcessor] Going to execute new bulk compose
d of 98 actions

**Comment by dadoonet** [comment]
I opened #396 and #397 to address this.
Going to close your issue then.

> Bit Off the topic but is there a way to get hash value of the files within fscrawler data fields?

You mean? Compute a hash of the binary content?
Like https://github.com/dadoonet/fscrawler#file-checksum ?
