### ISSUE TITLE
Ignore files bigger than X

### ISSUE THREAD

**Issue by dadoonet** [dadoonet/fscrawler#397]
We want to add an option to ignore very very big files, like a 10Gb DivX movie.

We can imagine ignoring totally the file or just index metadata if a file has a size bigger than a given threshold.
I believe that 20Mb could be a good default. It will avoid blowing up FSCrawler memory.

Or may be we can think of implementing a circuit breaker which estimates what memory is available at startup and compute the maximum size based on that?

See also #396 which is somehow related.

**Comment by konovalcev** [comment]
Hello @dadoonet 
This is a very good idea to add this logic to ignore files by size. It will be very helpful to have an option in _settings.json file, where I can set up the size of files, content of which should be extracted. Let's say, that if file is bigger, than 100 MB, content shouldn't be extracted. Is it possible to add this setting to fscrawler?
Thanks.

**Comment by dadoonet** [comment]
@konovalcev It is possible. I just need time to implement it.
I'd first like to get #367 in. 

But I'm very opened to PR :)

**Comment by konovalcev** [comment]
@dadoonet Thanks for your response. Could I ask, when it will be implemented approximately?
Thanks.

**Comment by dadoonet** [comment]
I have absolutely no idea. I’m afraid my schedule won’t allow me anything before the end of this year.

**Comment by konovalcev** [comment]
@dadoonet Hello David.
Ok, thanks for your response. Have a nice day!

**Comment by dadoonet** [comment]
This has been fixed.
