### ISSUE TITLE
No _settings_doc.json

### ISSUE THREAD

**Issue by madergaser** [dadoonet/fscrawler#405]
Hi, you reference this file multiple times in the documentation, but there is no example in the `/resources/fr/.../_default` folder? Could you give an example, or is it the same as found in the large code block [here](https://github.com/dadoonet/fscrawler#creating-your-own-mapping-analyzers)?

**Comment by dadoonet** [comment]
That's a doc issue. `_settings_doc.json` as been replaced by `_settings.json`

**Comment by madergaser** [comment]
So `_settings.json` should be placed in the same `mapping` folder under the job folder?

**Comment by dadoonet** [comment]
If you want to provide index settings and mappings before fscrawler starts the first time for a given job, add `~/.fscrawler/{job_name}/_settings.json` file.

You can copy one example of this file from `~/.fscrawler/_default/_mappings/5/_settings.json`.

Note that if you upgraded from 2.2, you ned to follow the upgrade instructions first.

**Comment by madergaser** [comment]
This is for a completely new index, so the upgrading would not be concerned. I have copy and pasted the inner objects in the example file to the end of `~/.fscrawler/{job_name}/_settings.json`, and added `"analyzer" : "english"` to the `content` mapping. When I start up fscrawler, the mapping is not transferred to elasticsearch. Am I doing something wrong?

Thank you for your quick responses 👍

**Comment by dadoonet** [comment]
Did you remove the index in elasticsearch before starting?

**Comment by madergaser** [comment]
Yes, I have, and when I call `GET /docs/_mapping`, the content object looks like this:

`
"content": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          }
`

**Comment by madergaser** [comment]
Don't know if this is my fault or not, but just inserted the modification of the mapping I needed in a new index and crawled to that index.

**Comment by dadoonet** [comment]
The documentation issue has been fixed with ca36636bcf55334c46a727be7ad84b845957e25a. See #408.

@madergaser Do you still have a problem?
