### ISSUE TITLE
Documentation about user mappings is wrong

### ISSUE THREAD

**Issue by ploncker** [dadoonet/fscrawler#408]
I ma using elastic 5.5, fscrawler 2.3 on windows. I can create an index with the mappings I want. from here:

Creating your own mapping (analyzers)
If you want to define your own index settings and mapping to set analyzers for example, you can either 
1. create the index and push the mapping or 
2. define a ~/.fscrawler/_default/5/_settings_doc.json document which contains the index settings and mappings you wish before starting the FS crawler.

I have tried both
1. creating my index and custom mapping and running fscrawler
In this case fscrawler creates a new index with the same name!!? without the desired mappings
2. just does not seem to read this file. 

I had this working with elastic2.x and fscrawler2.1
How do I implement my own mappings in elastic 5.5 with fscrawler?

**Comment by dadoonet** [comment]
Thanks for being an early adopter :)

Can you describe exactly what you did for:

> creating my index and custom mapping and running fscrawler

But indeed 

> define a `~/.fscrawler/_default/5/_settings_doc.json` is incorrect.

It should have been `~/.fscrawler/_default/5/_settings.json`. I'm going to fix that in documentation. That's a leftover from a change I started initially.
