### ISSUE TITLE
index document not deleted 

### ISSUE THREAD

**Issue by faizalpribadi** [dadoonet/fscrawler#409]
I tried deleting folder from config path `fs.path` but, index document stil can be search on the elasticsearch, fscrawler running `update.rate: 5m` but I dont see any change at all, can anyone explain for this ?

this is my configuration:

```js
{
  "name" : "documents",
  "fs" : {
    "url" : "/Users/faizalpribadi/testing",
    "update_rate" : "5m",
    "includes" : [ "*.pdf", "*.docx", "*.doc", "*.txt" ],
    "excludes" : [ "~*" ],
    "json_support" : false,
    "filename_as_id" : false,
    "add_filesize" : true,
    "remove_deleted" : true,
    "add_as_inner_object" : false,
    "store_source" : false,
    "index_content" : true,
    "attributes_support" : false,
    "raw_metadata" : false,
    "xml_support" : false,
    "index_folders" : true,
    "lang_detect" : false,
    "continue_on_error" : false,
    "pdf_ocr" : false
  },
  "elasticsearch" : {
    "nodes" : [ {
      "host" : "127.0.0.1",
      "port" : 9200,
      "scheme" : "HTTP"
    } ],
    "bulk_size" : 100,
    "flush_interval" : "5s"
  },
  "rest" : {
    "scheme" : "HTTP",
    "host" : "127.0.0.1",
    "port" : 8080,
    "endpoint" : "fscrawler"
  }
}
```

**Comment by dadoonet** [comment]
So you remove a file from `/Users/faizalpribadi/testing`, right?
You are running on MacOS?

Can you try again with `--debug` option?

**Comment by faizalpribadi** [comment]
Sure
<img width="1546" alt="screen shot 2017-07-28 at 2 58 45 pm" src="https://user-images.githubusercontent.com/1262414/28708152-66056a28-73a5-11e7-93c4-568352c3dcc9.png">

**Comment by dadoonet** [comment]
Can you share the logs as text instead of a picture?

Can you tell me which file (filename) you removed?

**Comment by faizalpribadi** [comment]
Im deleted the folder which folder have a 2 file

`/Users/faizalpribadi/testing/four`

`(four folder) -> [ 1.pdf, 2.pdf ]`

**Comment by faizalpribadi** [comment]
So the problem with MacOS , right ?

Im just switched to my docker debian and sure with elasticsearch, fscrawler does not problem at all, when im deleted and move folder or file, :)

**Comment by dadoonet** [comment]
Might be. Thanks for testing on another OS. I'm myself running on MacOS and I thought I had integration tests for this case but I'll try to reproduce and add a test if not existing yet.

Might be related to #379

Note that I'm thinking of replacing my own made watcher code by either #399 or #377 or both.

**Comment by dadoonet** [comment]
In `test_subdirs_very_deep_tree()` test (https://github.com/dadoonet/fscrawler/blob/08a35462329363a2f454e62f92e17cab3c150d25/integration-tests/src/test/java/fr/pilato/elasticsearch/crawler/fs/test/integration/FsCrawlerImplAllParametersIT.java#L738), I'm testing at the end that removing a huge subtree actually removes files in elasticsearch: https://github.com/dadoonet/fscrawler/blob/08a35462329363a2f454e62f92e17cab3c150d25/integration-tests/src/test/java/fr/pilato/elasticsearch/crawler/fs/test/integration/FsCrawlerImplAllParametersIT.java#L818-L823

```java
        // Let's remove the main subdir and wait...
        staticLogger.debug("  --> Removing all dirs from [{}]", mainDir);
        deleteRecursively(mainDir);

        // We expect to have 1 doc now
        countTestHelper(new SearchRequest(getCrawlerName()), 1L, currentTestResourceDir);
```

This test passes correctly on MacOS so I think it should be ok now. I'm closing but feel free to reopen if you can reproduce that with the latest SNAPSHOT. Thanks for reporting with so many details! Much appreciated.
