### ISSUE TITLE
Explosion in number of fields

### ISSUE THREAD

**Issue by Ramon-zaro** [dadoonet/fscrawler#415]
@dadoonet Continuing from here : https://discuss.elastic.co/t/filesearch-solution-using-es-5-5-0/94377/11

fscrawler creates fields dynamically; as it encounters different filetypes the number of fields in an index tends to explode and cross the default 1000 limit.

**Comment by Ramon-zaro** [comment]
I will check if wildcard works in remove and let you know tomorrow. 
no idea how to go about script processor, any pointers would be appreciated.

**Comment by dadoonet** [comment]
Thanks. Better to keep that part of the discussion on discuss IMO.
