### ISSUE TITLE
filename is Garbled when index a file which name contains Chinese characters

### ISSUE THREAD

**Issue by hailisun** [dadoonet/fscrawler#418]
My os is linux. when I indexed a file using command like "curl -F 'file@test中文名称.txt' 'http://localhost:8080/fscrawler/_upload' ",   it returned {"filename":"test????","ok":true,"url":...}; if I use this interface in java ,it returns the same thing.   what can I do to solve this problem?

**Comment by dadoonet** [comment]
Is your console using UTF8?

**Comment by hailisun** [comment]
Yes, I think so.

**Comment by dadoonet** [comment]
Ok. I'll try it locally. Thanks for reporting it!

**Comment by dadoonet** [comment]
I can reproduce it. It actually fails using the REST Upload API but works well when crawling files.
Will try to fix it.

**Comment by hailisun** [comment]
Thank you very much for solved it!
