### ISSUE TITLE
Crawling moved files

### ISSUE THREAD

**Issue by Ramon-zaro** [dadoonet/fscrawler#419]
fscrawler picks up files on the basis of creation date. often those files arrive in its target folder after a lag of day or two. because they are created elsewhere and filesystem does not update creation date for a simple file transfer.
this means the full crawling has to be restarted regularly, which is a pain.

It would be very useful if an option can be added to config to crawl files older than current time. 
say "crawl.files.from" : -2d

**Comment by dadoonet** [comment]
There is a workaround for now.

You can edit manually `_status.json` and change the date inside it.

Your report is somehow related to #399 where I want to change the current "watch" implementation. It might solve the problem of files which are simply moved from one place to another without touching the creation date.

I'm keeping your issue opened.

**Comment by Ramon-zaro** [comment]
is a resolution for this issue on the cards with the next update offscrawler ?

**Comment by dadoonet** [comment]
Ideally people should better "touch" the files they are moving to the scanned directory as I just documented at https://github.com/dadoonet/fscrawler#moving-files-to-a-watched-directory

Crawling with `"crawl.files.from" : -2d` will have the consequence of reindexing again and again the same files during 2 days which I think we should avoid.

Or may be we will need to keep a local list of the files that have been crawled yet but I'd prefer to solve this issue with a Watch like new implementation as per #399. 

I'm closing this one if you don't mind then.
