### ISSUE TITLE
Boosting information more than others

### ISSUE THREAD

**Issue by Wirjun** [dadoonet/fscrawler#426]
Hey, 
is it possible to boost information of a file (e.g. title) to achieve higher score in elasticsearch? If you are searching for a term and it is found in the title then the result will be higher ranked.

Thanks.

**Comment by dadoonet** [comment]
Yes. Just boost at search time.
For example read boost on that page: https://www.elastic.co/guide/en/elasticsearch/reference/5.5/query-dsl-query-string-query.html
