### ISSUE TITLE
can not upload files every upload_rate

### ISSUE THREAD

**Issue by 695172327** [dadoonet/fscrawler#427]
fscrawler 2.3;elasticsearch-5.5.1:
My fscrawler upload_rate is 5m;
New folder will be added in job_name_folder every 5m ,however,my job_name has not changed.

ps:My job name is j_5;
5 files is uploaded to es fscrawler j_5 for the first time.But 5m later ， j_5 has not changed.

**Comment by 695172327** [comment]
Appreciate any help I can get！THX.

**Comment by dadoonet** [comment]
Try with --debug option.

Note that moving files on some OS might cause this. Copying/pasting file should be ok though.

**Comment by 695172327** [comment]
The new path can be indexed in job_folder.Howerver, fs says that  the new files in new path has not be modified..【no modified:creation date xxx,file datexxx 】and i never send them before.

**Comment by dadoonet** [comment]
Did you copy files from one place to another or moved them?

**Comment by 695172327** [comment]
NO.All the files is in the upload path.

**Comment by dadoonet** [comment]
How did you add the files in the "upload" path?

**Comment by 695172327** [comment]
I use samba  upload them from windows to linux.

The modification time under Linux has not changed.When I use the command “touch -m -d XXX xXx filename”  change this modified time to the current time.The problem has been solved!

THX!
