### ISSUE TITLE
indexing namespace by folder name (dynamic indexing)

### ISSUE THREAD

**Issue by faizalpribadi** [dadoonet/fscrawler#428]
is it possible generate indexing by namespace folder like this 

* `folder name for userA  is userA and files inside the folder [files,files,files] = generate index name by name of folder userA`

* `folder name for userB  is userB and files inside the folder [files,files,files] = generate index name by name of folder userB`

this mechanism like a google drive search engine, thanks :)

**Comment by dadoonet** [comment]
I'm afraid I don't understand what you are asking for. Can you explain it in a different way?

But let me give a kind of "answer". You can start multiple fscrawler instances, each of it can run different settings, like index name.

**Comment by dadoonet** [comment]
Closing as no further feedback. Feel free to reopen and add more information if possible.

Thanks!
