### ISSUE TITLE
Exception "entity content is too long"

### ISSUE THREAD

**Issue by konovalcev** [dadoonet/fscrawler#432]
Hello team.
We are trying to crawl all FTP's inside our company. During crawling of one of them, I get exception "entity content is too long". 

![screenshot exception](https://user-images.githubusercontent.com/27678814/30282072-40f34dd8-9725-11e7-9d65-4ea268dc1813.jpg)

I tried did exactly, as mentioned in documentation: either change this limit on elasticsearch side by setting http.max_content_length to a higher value or you can decrease the bulk_size setting to a smaller value. I tried both these ways, it doesn't help. 
I even tried this way:
    "bulk_size" : 1,
    "flush_interval" : "1s"
but it doesn't help.
I've attached screenshot of the end of elasticsearch.yml to share settings of claster for your reference.

![elasticsearch yml](https://user-images.githubusercontent.com/27678814/30281742-4619eca0-9724-11e7-9bc5-774191781932.jpg)

Could you help to understand, how it can be fixed, please?
Thanks.

**Comment by dadoonet** [comment]
Hi @konovalcev. Thanks for reporting.

Would be better to post text instead of images of text though. Better for copy and paste and search :)

I'm surprised that `"bulk_size" : 1,` did not help. It would be to me that the generated document is bigger than 100mb JSON which looks like insane to me. `indexed_chars` only extracts 100 000 characters by default so I'm super surprised this is happening.

Any chance you can reproduce it with a single document?

What is the full fscrawler settings file looking like?

**Comment by konovalcev** [comment]
Hello David.
Thanks for your response and sorry for screenshots.
Indexed_chars is set up as 100%, because we need full content of any document. I'm not sure, how I can reproduce it, because as I understand, crawler sends bulks to elastic, not every document. Do you think, that if document is bigger 100Mb, there is no way to avoid this exception?

**Comment by dadoonet** [comment]
> Do you think, that if document is bigger 100Mb, there is no way to avoid this exception?

That's what I'd like to figure out. But first I'd like to narrow down the issue and eventually reproduce it.
Any chance you could share:

* your fscrawler settings
* One of the big documents which makes that failing

I wonder if you can use the REST Service to simulate what will be a JSON document like? https://github.com/dadoonet/fscrawler#simulate-upload

I now need to check what the REST Client can support in terms of settings. Judging the stacktrace, I feel like that the limit is now on the client side. Wondering if @tlrx has any idea on how to increase the HTTP size limit of the Low Level REST Client?

**Comment by tlrx** [comment]
> I now need to check what the REST Client can support in terms of settings. Judging the stacktrace, I feel like that the limit is now on the client side. Wondering if @tlrx has any idea on how to increase the HTTP size limit of the Low Level REST Client?

Right, the low-level  REST client has a limit on the response body to parse (100mb). See `org.elasticsearch.client.HeapBufferedAsyncResponseConsumer` and [HeapBufferedResponseConsumerFactory](https://github.com/elastic/elasticsearch/blob/706067211ae880bbe4669286ee976552e8a60446/client/rest/src/main/java/org/elasticsearch/client/HttpAsyncResponseConsumerFactory.java#L49-L64). The last one can be passed as an argument of the `RestClient.performRequest()` method.

**Comment by dadoonet** [comment]
Thanks @tlrx. Much appreciated.

This indicates that only the response object has a limit. We should not hit that limit here with on single document in a bulk request.

So @konovalcev, I need to get more details as I wrote previously on what you exactly tried so I can try to reproduce.
Thanks!

**Comment by konovalcev** [comment]
Hello guys.
We did few tests, and it seems, we found out, when exactly it happens.
At first, please, see _settings.json for your reference. Please, don't pay your attention on bulk_size and flush_interval options, because I tried absolutely any parameters, and the values, that you can see - the last values, that I've tried.

[_settings.txt](https://github.com/dadoonet/fscrawler/files/1295593/_settings.txt)

Crawler is stopped and exception is generated in the same folder every time. This folder contains 13 files, 10 of which should be crawled (extensions of other 3 are not included into "includes" section in _settings.json file). You can see this folder below:

![folder screenshot](https://user-images.githubusercontent.com/27678814/30327981-0f93c3f2-97df-11e7-83bc-e7e687f52b6c.jpg)

As you can see, there is one text file bigger then 100mb. But I think problem is not this. This folder is just one of many folders in this ftp resource. I even tried to crawl only this folder separately. The same result. Exception was generated. But.
All 10 files were crawled and were uploaded into elasticsearch. I mean, that this test indice contains 10 documents, as expected. But after metadata of all files were uploaded into elasticsearch, crawler did this as a final step (as per my understanding):

12:59:20,041 DEBUG [f.p.e.c.f.c.ElasticsearchClient] bulk response: BulkResponse
{items=[BulkItemTopLevelResponse{index=BulkItemResponse{failed=false, index='tes
tbigfiles', type='doc', id='5aa7fb87e7cadb77ed7dd4207983d9', opType=null, failur
eMessage='null'}, delete=null}]}
12:59:20,041 DEBUG [f.p.e.c.f.c.BulkProcessor] Executed bulk composed of 1 actio
ns
12:59:20,041 DEBUG [f.p.e.c.f.FsCrawlerImpl] Looking for removed files in [\\ftp
\ftp\somefolder]...
12:59:20,041 TRACE [f.p.e.c.f.FsCrawlerImpl] Querying elasticsearch for files in
 dir [path.root:1eda99317f5f8e7cf839b13f2be57726]
12:59:20,041 DEBUG [f.p.e.c.f.c.ElasticsearchClient] search [testbigfiles], requ
est [SearchRequest{query=path.root:1eda99317f5f8e7cf839b13f2be57726, fields=[_so
urce, file.filename], size=10000}]
13:01:51,719 WARN  [f.p.e.c.f.FsCrawlerImpl] Error while crawling \\ftp\ftp\somefolder: entity content is too long [244764685] for the configured buffer limit [104
857600]
13:01:51,719 WARN  [f.p.e.c.f.FsCrawlerImpl] Full stacktrace
org.apache.http.ContentTooLongException: entity content is too long [244764685]
for the configured buffer limit [104857600]
        at org.elasticsearch.client.HeapBufferedAsyncResponseConsumer.onEntityEn
closed(HeapBufferedAsyncResponseConsumer.java:76) ~[rest-5.5.0.jar:5.5.0]
        at org.apache.http.nio.protocol.AbstractAsyncResponseConsumer.responseRe
ceived(AbstractAsyncResponseConsumer.java:131) ~[httpcore-nio-4.4.5.jar:4.4.5]
        at org.apache.http.impl.nio.client.MainClientExec.responseReceived(MainC
lientExec.java:315) ~[httpasyncclient-4.1.2.jar:4.1.2]
        at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.resp
onseReceived(DefaultClientExchangeHandlerImpl.java:147) ~[httpasyncclient-4.1.2.
jar:4.1.2]
        at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.responseReceive
d(HttpAsyncRequestExecutor.java:303) ~[httpcore-nio-4.4.5.jar:4.4.5]
        at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(De
faultNHttpClientConnection.java:255) ~[httpcore-nio-4.4.5.jar:4.4.5]
        at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(Inter
nalIODispatch.java:81) ~[httpasyncclient-4.1.2.jar:4.1.2]
        at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(Inter
nalIODispatch.java:39) ~[httpasyncclient-4.1.2.jar:4.1.2]
        at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(Abstra
ctIODispatch.java:114) ~[httpcore-nio-4.4.5.jar:4.4.5]
        at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor
.java:162) ~[httpcore-nio-4.4.5.jar:4.4.5]
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(Abstr
actIOReactor.java:337) ~[httpcore-nio-4.4.5.jar:4.4.5]
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(Abst
ractIOReactor.java:315) ~[httpcore-nio-4.4.5.jar:4.4.5]
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIO
Reactor.java:276) ~[httpcore-nio-4.4.5.jar:4.4.5]
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.
java:104) ~[httpcore-nio-4.4.5.jar:4.4.5]
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.
run(AbstractMultiworkerIOReactor.java:588) ~[httpcore-nio-4.4.5.jar:4.4.5]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
13:01:51,813 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler is stopping after 1 run
13:01:51,813 DEBUG [f.p.e.c.f.FsCrawlerImpl] Closing FS crawler [testbigfiles]
13:01:51,813 DEBUG [f.p.e.c.f.FsCrawlerImpl] FS crawler thread is now stopped
13:01:51,813 DEBUG [f.p.e.c.f.FsCrawlerImpl] FS crawler Rest service stopped
13:01:51,813 DEBUG [f.p.e.c.f.c.ElasticsearchClientManager] Closing Elasticsearc
h client manager
13:01:51,813 DEBUG [f.p.e.c.f.c.BulkProcessor] Closing BulkProcessor
13:01:51,813 DEBUG [f.p.e.c.f.c.BulkProcessor] BulkProcessor is now closed
13:01:51,813 DEBUG [f.p.e.c.f.c.BulkProcessor] Closing BulkProcessor
13:01:51,813 DEBUG [f.p.e.c.f.c.BulkProcessor] BulkProcessor is now closed
13:01:51,813 DEBUG [f.p.e.c.f.c.ElasticsearchClient] Closing REST client
13:01:51,813 DEBUG [f.p.e.c.f.c.ElasticsearchClient] REST client closed
13:01:51,813 DEBUG [f.p.e.c.f.FsCrawlerImpl] ES Client Manager stopped
13:01:51,813 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler [testbigfiles] stopped
13:01:51,813 DEBUG [f.p.e.c.f.FsCrawlerImpl] Closing FS crawler [testbigfiles]
13:01:51,813 DEBUG [f.p.e.c.f.FsCrawlerImpl] FS crawler thread is now stopped
13:01:51,829 DEBUG [f.p.e.c.f.FsCrawlerImpl] FS crawler Rest service stopped
PS E:\search\crawlers\fscrawler-2.4-SNAPSHOT\bin>

Not sure, why crawler did this step, but if you pay your attention on this part:

12:59:20,041 DEBUG [f.p.e.c.f.c.ElasticsearchClient] search [testbigfiles], requ
est [SearchRequest{query=path.root:1eda99317f5f8e7cf839b13f2be57726, fields=[_so
urce, file.filename], size=10000}]
13:01:51,719 WARN  [f.p.e.c.f.FsCrawlerImpl] Error while crawling \\ftp\ftp\somefolder: entity content is too long [244764685] for the configured buffer limit [104
857600]

You can see, that crawler sends this query to elasticsearch (after all files were indexed sucessfully):
query=path.root:1eda99317f5f8e7cf839b13f2be57726, fields=[_source, file.filename], size=10000}
waiting for response for 2.31 minutes and generates exception.
Not sure, why crawler wants to get so many data from elasticsearch, that definitely, are bigger than 100mb (244764685 bytes ~ 245mb).
Is there any idea?)
And thanks for your responses!

**Comment by dadoonet** [comment]
Oh! Indeed that's very true. Thanks for the detailled analysis.

Actually, FSCrawler is trying to check if some files have been removed. This is a very bad implementation I must confess and I'm planning to change that but for now I have no choice than doing that check.

https://github.com/dadoonet/fscrawler/blob/master/src/main/java/fr/pilato/elasticsearch/crawler/fs/FsCrawlerImpl.java#L545-L551

This is totally bad. I should only try to look for the `FILE_FILENAME` field but I'm also looking at the `_source` in case someone changed the default mapping for the filename field. 

I will fix that problem as soon as I can.

Thanks a lot!

As a workaround for now, you can try to set `"remove_deleted" : false` and see if it works better...
