### ISSUE TITLE
Multi Threaded?

### ISSUE THREAD

**Issue by jmrichardson** [dadoonet/fscrawler#440]
Hi, is fscrawler multi-threaded?   I can't find reference to this in the documentation.  Thanks

**Comment by dadoonet** [comment]
Not really. There is one single crawling thread.

**Comment by dadoonet** [comment]
Closing as it was only a question. I might though consider revisiting the implementation (#399) and running multiple threads in parallel to speed up the ingestion.

**Comment by ArturFormella** [comment]
It's a pity my server has 56 threads but only one is indexing :(

**Comment by dadoonet** [comment]
> It's a pity my server has 56 threads but only one is indexing :(

Sure. You can in the short term launch multiple instances in parallel.

**Comment by usbhimani** [comment]
@dadoonet : I am doing an implementation with multiple instances of fscralwer and it seems to be ingesting correctly.
