### ISSUE TITLE
"Java heap space" exception

### ISSUE THREAD

**Issue by konovalcev** [dadoonet/fscrawler#442]
Hello team.
We are faced with this exception during crawling some internal ftp resources even if we set up FS_JAVA_OPTS="-Xmx7168m -Xms7168m", for example. It is strange, because we crawl only text documents, some of them certainly can have sizes of hundreds megabytes. But.
As per my understanding, in this case the following options should help:
    "bulk_size" : 100,
    "flush_interval" : "5s"
But it doesn't work even if I set 
    "bulk_size" : 1,
    "flush_interval" : "1s"
As I understand, crawler consolidates some bundle of metadata to send it into elastic and after this crawler should flush memory for the next bundle. Not sure how it works exactly, but why crawler needs so much RAM to store objects?
Is there any way to fix it except obvious option (increasing of RAM), because I believe, that crawler uses too much memory for simple text files even if they are fairly big.
Thanks!

**Comment by dadoonet** [comment]
Not that there is a very nasty bug I fixed recently so it would be great to test the latest snapshot.

**Comment by dadoonet** [comment]
See #437

**Comment by konovalcev** [comment]
@dadoonet Hello David. That issue, that you are referenced to, was created by me. So, I am using exactly this latest snapshot. "Entity content is too long" exception was solved, thanks! But I think, there is another problem with memory leak or something like this, when I get "Java heap space" exception. Do you know scenario, when 8 GB RAM is not enough? What should happens to get this exception?
I can imagine, if I set "indexed_chars" : "-1", when crawler will extract byte by byte (as I understand), but I set "indexed_chars" : "100%", that should extract only text content. I am a bit wondered, why crawler needs so much memory.
Any idea, please?

**Comment by dadoonet** [comment]
> That issue, that you are referenced to, was created by me.

Haha! Sorry! 

> Any idea, please?

Nope. I don't know in details what Tika does behind the scene.
We probably need to take some JVM snapshots while this is running and analyze where all that memory is going...

**Comment by dadoonet** [comment]
I missed that part:

> "indexed_chars" : "100%"

If you do that then the entire document is parsed (but with a stream) and the text content and metadata are then loaded in memory to generate the JSON document.
Not sure yet how this can be optimized.

Might be also similar to #471

**Comment by dadoonet** [comment]
I'm going to close this one in favor of #566.
