### ISSUE TITLE
Adding new fields to document through --rest interface?

### ISSUE THREAD

**Issue by brailateo** [dadoonet/fscrawler#443]
It would be just perfect if we could add not just the "_id" field to the ElasticSearch document but also other fields through the --rest interface!

curl -F "file=@Dorel.pdf" -F "id=dorel314" -F "owner=gelu" -F "otherField=cutare" "http://127.0.0.1:8080/fscrawler/_upload"

Teo

**Comment by dadoonet** [comment]
Interesting idea indeed. 
I think that if possible it would be nice to add support for a full json content which could be merged with the generated content, like:

```sh
curl -F "file=@Dorel.pdf" -F "{\"foo\"=\"bar\"}" "http://127.0.0.1:8080/fscrawler/_upload"
```

**Comment by brailateo** [comment]
Hello @dadoonet ,
with the help of my friend Viorel I'm sending to you the changes for adding a new "tags" field that allows adding a full json to meta.raw information.

Usage:
`$ curl -F "file=@Demo.pdf" -F "tags=@tags.json" "http://127.0.0.1:8080/fscrawler/_upload"`

File "tags.json" content:
```
$ cat tags.json
{"programmer":"Viorel","varsta":"adecvata"}
```

Changes (on 2.5-SNAPSHOT), everything compiled just OK, tested, works perfectly! I hope you will include it!
In UploadAPI.java
```
public UploadResponse post(
  @QueryParam("simulate") String simulate,
  @FormDataParam("id") String id,
  @FormDataParam("tags") InputStream tags, // This is new code for "tags"
  @FormDataParam("file") InputStream filecontent,
  @FormDataParam("file") FormDataContentDisposition d) . . .

...
doc.getPath().setVirtual(filename);
doc.getPath().setReal(filename);
// Path

// THIS IS THE NEW CODE FOR "tags"
if(tags != null) {
    TypeReference<HashMap<String,Object>> typeRef = new TypeReference<HashMap<String,Object>>() {};
    HashMap<String,Object> o = MetaParser.mapper.readValue(tags, typeRef);
    for(Map.Entry<String, Object> e : o.entrySet()) {
        doc.getMeta().addRaw(e.getKey(), String.valueOf(e.getValue()));
    }
}

// Read the file content
TikaDocParser.generate(settings, filecontent, filename, doc, messageDigest, filesize);
```
Best regards,
Teo

**Comment by dadoonet** [comment]
Great! Would you like to contribute a pull request?

**Comment by brailateo** [comment]
I'm not familiar *AT ALL* with git & pulls! :-D
For only 8 lines it would be too hard for me to do it and I'm a too old dog to learn new tricks! ;-)
It's just fine to insert it into your code, make a test and document the new feature in howto, it might help others, too.
Best regards,
Teo
