### ISSUE TITLE
"includes" filetype bug

### ISSUE THREAD

**Issue by Ramon-zaro** [dadoonet/fscrawler#447]
@dadoonet asked me to open an issue here following the discussion at https://discuss.elastic.co/t/filesearch-using-fscrawler/99753/3.

"includes" does not seem to work on multiple items. I have tried the various methods @dadoonet  suggested.

**Comment by dadoonet** [comment]
I looked at the tests like: https://github.com/dadoonet/fscrawler/blob/master/settings/src/test/java/fr/pilato/elasticsearch/crawler/fs/settings/FsSettingsParserTest.java#L161-L168

It reads the following settings:

```json
{
  "name" : "test_parse_settings_fs",
  "fs" : {
    "url" : "/path/to/docs",
    "update_rate" : "5m",
    "includes" : [ "*.doc", "*.xls" ],
    "excludes" : [ "resume.doc" ],
    "json_support" : false,
    "filename_as_id" : true,
    "add_filesize" : true,
    "remove_deleted" : true,
    "add_as_inner_object" : false,
    "store_source" : true,
    "index_content" : true,
    "indexed_chars" : "10000.0",
    "attributes_support" : false,
    "raw_metadata" : true,
    "xml_support" : false,
    "index_folders" : true,
    "lang_detect" : false,
    "continue_on_error" : false,
    "pdf_ocr" : true,
    "ocr" : {
      "language" : "eng"
    }
  },
  "elasticsearch" : {
    "nodes" : [ {
      "host" : "127.0.0.1",
      "port" : 9200,
      "scheme" : "HTTP"
    } ],
    "bulk_size" : 100,
    "flush_interval" : "5s"
  },
  "rest" : {
    "scheme" : "HTTP",
    "host" : "127.0.0.1",
    "port" : 8080,
    "endpoint" : "fscrawler"
  }
}
```

I added more unit tests but I don't see how the problem you described can happen.

Anyway, the right way to configure includes is by using: `"includes" : [ "*.doc", "*.xls" ]`.
If you have a complete setting file which fails, I'll be happy to read it.

**Comment by Ramon-zaro** [comment]
Will do. give me a couple of days.

**Comment by Ramon-zaro** [comment]
I tried this again. Firstly, it didn't throw up any exceptions right away, unlike last time. So there must have been something else I did last time that caused an exception.

however, the run did not index all the documents, only about 1% or so. 
```
{
  "name" : "job_name",
  "fs" : {
    "url" : "/path/to/docs",
    "update_rate" : "5m",
    "includes" : [ "*.doc", "*.docx", "*.pdf", "*.rtf", "*.xls" ],
    "excludes" : [ "~*" ],
    "json_support" : false,
    "filename_as_id" : true,
    "add_filesize" : true,
    "remove_deleted" : true,
    "add_as_inner_object" : false,
    "store_source" : true,
    "index_content" : true,
...
    "raw_metadata" : false,
    "xml_support" : false,
    "index_folders" : false,
    "lang_detect" : false,
    "continue_on_error" : true,
    "pdf_ocr" : false,
    }
  },
....
    } ],
    "index" : "docs",
    "bulk_size" : 100,
    "flush_interval" : "5s",
  },
  "rest" : {
    "scheme" : "HTTP",
    "host" : "127.0.0.1",
    "port" : 8080,
    "endpoint" : "fscrawler"
  }
}
```

**Comment by dadoonet** [comment]
How many documents of those types `[ "*.doc", "*.docx", "*.pdf", "*.rtf", "*.xls" ]` do you have in `/path/to/docs`?
Did you clean before restarting your job with the restart option? See https://github.com/dadoonet/fscrawler#cli-options

**Comment by Ramon-zaro** [comment]
about half a million or thereabouts. nope, this was was a fresh job run.

**Comment by dadoonet** [comment]
What is the output of a `GET your-index/_search` please?
Note that you are using `filename_as_id` option which is using the filename as the `_id` for the document.

So if you have a file named `/mydir/dir1/foo.txt` and another `/mydir/dir2/foo.txt` they will be all indexed as `foo.txt`. Which means that the 2nd one will overwrite the 1st one.

**Comment by dadoonet** [comment]
Closing as no further news on this. Feel free to reopen and add comments if any.
