### ISSUE TITLE
'remove deleted' setting and _status.json file

### ISSUE THREAD

**Issue by Denis4545** [dadoonet/fscrawler#454]
Hello team.
I have couple questions regarding 'remove deleted' parameter and creation status.json file.
My settings file contains "remove_deleted" : true. Therefore, status.json file will be updated after deleting some files. It works perfectly if I deleting only files, not folders. However, if I delete the folder then status.json won't contain updated information about deleted files. As I said I deleted the folder that contains the files. My question is why status.json file doesn't contain updates after deletion of the folder?  
And one more question. I expected the status.json file is created once we launch the crawler. (_Once the crawler is running, it will write status information and statistics in:_) but it doesn't happen. Should I create status.json file manually if crawler has been stopped for any reason (timeout or power crashes, for example)? Should I launch the crawler as usual without any additional keys in this case, or not?
Thanks

**Comment by dadoonet** [comment]
Sorry for the late response.

> However, if I delete the folder then status.json won't contain updated information about deleted files.

That's strange. Normally anytime a file is removed, it should increase the delete counter. It feels like a bug.
Could you reproduce this with latest SNAPSHOT version?
If so, on which OS are you running?

I'm planning to change the implementation. Which should hopefully fix that kind of issues...

**Comment by dadoonet** [comment]
Closing as no further news on this. Feel free to reopen and add comments if any.
