### ISSUE TITLE
Using Fscrawler rest upload is not in sync with the FSCrawler Job

### ISSUE THREAD

**Issue by rkolta** [dadoonet/fscrawler#459]
When I use the Fscrawler rest when a file is uploaded it adds the index to Elastic Search but it is missing the extension and I see that this is an issue that is solved. However when the job runs after 15 min it re-adds this index to Elastic Search, it doesn't see that it was created by the rest client. 
Am I doing something wrong? 
This is how I test it. I create a file on my desk top, cut and paste it in the folder that's tracked. I then call the curl to the rest FSCrawler, which creates the index and sends it to ES but it gets recreated when the job on my machine runs at the 15 m time intervals.

Thank You!

**Comment by suresh-nataraj** [comment]
If you want to run only Rest Service , Use --loop 0 option , So it won't scan file system .

**Comment by dadoonet** [comment]
Thanks @suresh-nataraj. Much appreciated.
