### ISSUE TITLE
Running fscrawler on Win Server 2012

### ISSUE THREAD

**Issue by Ramon-zaro** [dadoonet/fscrawler#462]
I encountered a strange issue while trying to run fscrawler 2.3 on a Win server 2012 machine. 

I am recounting the steps leading upto the error : 
1. installed jdk 8 and set JAVA_HOME
2. extracted and launched ES 5.5 & Kibana. both running fine
3. tried to launch fscrawler from cmd. It gave me "incorrect syntax" error ! I tried fscrawler {job_name} as well with same result !

I am very perplexed, I have this same set-up running fine on another win server2012 machine with no issues whatsoever. what could have gone wrong ? 
please help !

**Comment by dadoonet** [comment]
Hmmm. Interesting.

For sure the batch needs more love for the windows platform (I'm not testing it yet).

Do you think you could try to comment out the lines in https://github.com/dadoonet/fscrawler/blob/master/src/main/scripts/fscrawler.bat and try to find what is the line which is causing that error?

**Comment by Ramon-zaro** [comment]
Hi, looks like it was a java related issue. installed JRE and set Java_home to that and everything worked ! you might want to add that to the installation directions, at least for windows systems.

**Comment by dadoonet** [comment]
Not sure I understand. You said first that you "installed jdk 8 and set JAVA_HOME" but it was not working.
And then you said that "installed JRE and set Java_home to that and everything worked". 

What is the difference? JDK vs JRE? Is that what you meant?

**Comment by Ramon-zaro** [comment]
yup.

**Comment by dadoonet** [comment]
No you need to start multiple instances of FSCrawler

**Comment by dadoonet** [comment]
I'm unsure I can fix anything here. I checked on my end and my `JAVA_HOME` is going to a JDK so JDK should be correct. May be it's a thing with JDK on Windows only?

I'm closing this issue but if you can share where your `JAVA_HOME` was set to (before you switched back to JRE) and what is the content of this dir, that might help to understand.

Thanks. Feel free to reopen if you think the answer is incorrect.
