### ISSUE TITLE
Index based on extracted text

### ISSUE THREAD

**Issue by tomSDL** [dadoonet/fscrawler#463]
Hi David,

It would be a great feature to have index/do not index based on text extracted.

An example would be running a regex to find visa credit card numbers and indexing the document if found.

Thank you.

Tom

**Comment by arvindnrbt** [comment]
Any update on this?

**Comment by dadoonet** [comment]
No sorry.

**Comment by dadoonet** [comment]
This has been implemented. I hope this will help.

**Comment by tomSDL** [comment]
Thank you. I will check it out asap.

Cheers!
