### ISSUE TITLE
_upload the same file through REST

### ISSUE THREAD

**Issue by hanozo** [dadoonet/fscrawler#465]
Hello David,
Is there a way to distinguish between two consecutive _upload requests of the same file?
Currently both responses are: 
"ok": true,
"filename": "/home/hanozo/filename.pdf",
"url: "http://x.x.x.x:9200/strip/doc/fd78fs9sd9f9699sfg9h...."

Thanks, Alon

**Comment by dadoonet** [comment]
So you mean that they should be considered as 2 different documents?

**Comment by hanozo** [comment]
No (:
The first request actually created the document and the second might update the document (i guess).
Is there a way to distinguish between such scenarios while uploading an existing file?  

Thanks for your quick reply.

**Comment by dadoonet** [comment]
I'm afraid I don't understand. 

> The first request actually created the document and the second might update the document

This is what is happening now, right?

> Is there a way to distinguish between such scenarios while uploading an existing file?

This is the thing I don't understand. Sorry. May be my lack of english :) 
Could you explain it differently? Do you want at the end to have 2 different documents or only one or both versions of the same document?

**Comment by hanozo** [comment]
Sorry David, I'll try to clear things out. Having a single document at the end is the desired behavior (as happening now). It's the response i'm curious about.
I looked at the UploadApi and noticed that upload requests are scheduled through BulkProcessor and replied with fixed response which not reflect the actual indexing result (which take place at some later point in time). So in the bottom line, two consecutive _upload requests of the same file will yield the exact same response, preventing the distinction between the actual creation of the document (by the first request) and the second request.

Thank you.

**Comment by shadiakiki1986** [comment]
You can use the `url` field returned by fscrawler returned json to fetch the raw document in elasticsearch. Then in the doc in the index there is a `version` field that gets autoincremented with each upload
