### ISSUE TITLE
Can FS Crawler skip file on error (exception thrown)?

### ISSUE THREAD

**Issue by richard-salac** [dadoonet/fscrawler#470]
Hi,
I am crawling hundreds of thousands of files from 3rd party source. Some of the files are malformed and causing internal exception (sometimes from Tika, sometimes from Woodstox parser etc.). When an exception is thrown, the crawlers stops. Is it possible to configure the crawler to skip files causing an exception an continue instead of stopping? I tried the continue_on_error option but with no luck.

Thanks for an answer.

**Comment by dadoonet** [comment]
I think we should extend what `continue_on_error` is doing today.
I'm marking this as a feature request.
Could you share a failing file that can be reused for tests?

**Comment by richard-salac** [comment]
Thank you. I will look for a testing file and post it.

**Comment by dadoonet** [comment]
Ping @richard-salac. Do you have any file I could use for testing?

**Comment by dadoonet** [comment]
No further news. I'm closing but feel free to share a sample file and reopen.
