### ISSUE TITLE
internal search with ES 5.1 yielding warning and failure to generate `_status.json` file

### ISSUE THREAD

**Issue by shadiakiki1986** [dadoonet/fscrawler#472]
Hello @dadoonet 
From the below logs in the travis builds of docker-fscrawler [line 1589](https://travis-ci.org/shadiakiki1986/docker-fscrawler/builds/322800483#L1589), you can see that upon completion of indexing, fscrawler executes a search on elasticsearch, which fails.

```
DEBUG [f.p.e.c.f.FsCrawlerImpl] Looking for removed files in [/usr/share/fscrawler/data]...
TRACE [f.p.e.c.f.FsCrawlerImpl] Querying elasticsearch for files in dir [path.root:57a5a3aa8c78aaf1a9aee610d0f241]
WARN  [f.p.e.c.f.FsCrawlerImpl] Error while crawling /usr/share/fscrawler/data: Elasticsearch exception [type=illegal_argument_exception, reason=request [/docker-compose/_search] contains unrecognized parameters: [batched_reduce_size], [typed_keys]]
```

On [line 1152](https://travis-ci.org/shadiakiki1986/docker-fscrawler/builds/322800483#L1152), it shows `Using elasticsearch >= 5, so we can use ingest node feature`

The result of this warning is that fscrawler is unable to generate the `_status.json` file, as you can see in [line 1078](https://travis-ci.org/shadiakiki1986/docker-fscrawler/builds/322800483#L1078)

When I looked at the logs of the [travis build of fscrawler](https://travis-ci.org/dadoonet/fscrawler) which passed, I found the following message on [line 1253](https://travis-ci.org/dadoonet/fscrawler/jobs/293590495#L1253): `   > Assumption #1: We only test our internal search stuff for version < 5.0: got: <true>, expected: is <false>`

I suppose this means that the integration tests skip testing the search in this case because ES > 5.0 is running, as shown on [line 1217](https://travis-ci.org/dadoonet/fscrawler/jobs/293590495#L1217) as `version[5.5.1]`

There is another instance of this message at [line 1659](https://travis-ci.org/dadoonet/fscrawler/jobs/293590495#L1659).

Skipping the tests happens in [ElasticsearchClientIT.java#L92](https://github.com/dadoonet/fscrawler/blob/c33e552f5b2988a8298e3892bed01fab48cb85a7/src/test/java/fr/pilato/elasticsearch/crawler/fs/test/integration/ElasticsearchClientIT.java#L92), where you comment `Depending on the version we are using, we need to adapt the test settings (mapping)`. Perhaps instead of skipping the tests, you could have 2 different mappings, one for `ES<5` and one for `ES>=5`?

**Comment by dadoonet** [comment]
What is your elasticsearch version?

I know that the High Level client is incompatible sadly between major versions.
I tried to workaround but might have missed something.

**Comment by shadiakiki1986** [comment]
5.1.2

**Comment by shadiakiki1986** [comment]
Just tested on ES 6.1.1 and didn't face the issue.
Will work on upgrading the ES in the docker-fscrawler travis tests.
Shall I close this issue? Or do you want to keep it open for ES 5.1.2 for example?

**Comment by dadoonet** [comment]
Let's keep it opened for now. I'll check that after holidays  :)

**Comment by shadiakiki1986** [comment]
Enjoy your holidays then :)

**Comment by dadoonet** [comment]
I opened #485 to discuss about some strategies for the future.
If you have any thoughts, I'll be super happy to listen about them. :)

**Comment by dadoonet** [comment]
I have some tests running agains 5.x and 6.x and I can't reproduce the problem anymore with the latest SNAPSHOT. Could you check again if you still have the problem?

This test passes on 5.6:

https://github.com/dadoonet/fscrawler/blob/48bd7f50e0f1d8ac984836c075c3e1e1ebc97e75/integration-tests/src/test/java/fr/pilato/elasticsearch/crawler/fs/test/integration/FsCrawlerTestRemoveDeletedIT.java#L89-L109

**Comment by dadoonet** [comment]
Closing due to lack of feedback. Feel free to reopen or add new comments if any.
