### ISSUE TITLE
FSCrawler not Indexing Files in Subdirectories

### ISSUE THREAD

**Issue by HeliosLHC** [dadoonet/fscrawler#483]
I've read through the documentation and past bug reports and I can't seem to determine whether or not fscrawler appears to be able to index files in sub-directories of inside the root directory passed in. I've tried expanding my regex query from `"includes" : ["*.html"],` to `includes" : ["*"]`, however, fscrawler only indexes individual files in the root directory and the subdirectories themselves and not the files inside them. My --debug and --trace logs indicates fscrawler does scan them and marks them as so `[website.html] can be indexed: [true]` but only the root folder files and subdirectories get processed and sent to elasticsearch. I apologize if this is a stupid question.

OS: Windows 10
JVM: Java 8 u151
FScrawler: version 2.4 and version 2.5-snapshot

My filesystem layout is as so
1. Root Directory: E:/
2. Subdirectories: E:/WebsiteA, E:WebsiteB,...
3. Files in Subdirectories: [WebsiteA.html, Index.html],[WebsiteB.html, Index.html]...
While all three groups are scanned, only group 1 and 2 items are actually processed and sent to elasticsearch.

In my case where no files are in the root directory, only the folders gets indexed into the index localwebsites_folders with the respective folder information such as real and virtual paths.

Log from --trace below
````
17:00:40,445 [36mDEBUG[m [f.p.e.c.f.u.FsCrawlerUtil] filename = [website], includes = [[*.html]], excludes = [null]
17:00:40,445 [36mDEBUG[m [f.p.e.c.f.u.FsCrawlerUtil] filename = [website], excludes = [null]
17:00:40,445 [30mTRACE[m [f.p.e.c.f.u.FsCrawlerUtil] no rules
17:00:40,445 [36mDEBUG[m [f.p.e.c.f.u.FsCrawlerUtil] filename = [website], includes = [[*.html]]
17:00:40,445 [30mTRACE[m [f.p.e.c.f.u.FsCrawlerUtil] regex is [.*?.html]
17:00:40,445 [30mTRACE[m [f.p.e.c.f.u.FsCrawlerUtil] does not match any include pattern
17:00:40,445 [36mDEBUG[m [f.p.e.c.f.u.FsCrawlerUtil] filename = [website], excludes = [null]
17:00:40,445 [30mTRACE[m [f.p.e.c.f.u.FsCrawlerUtil] no rules
17:00:40,445 [36mDEBUG[m [f.p.e.c.f.FsCrawlerImpl] [website] can be indexed: [true]
17:00:40,445 [36mDEBUG[m [f.p.e.c.f.FsCrawlerImpl]   - folder: website
17:00:40,445 [36mDEBUG[m [f.p.e.c.f.FsCrawlerImpl] indexing [E:\website] content
17:00:40,445 [36mDEBUG[m [f.p.e.c.f.f.FileAbstractor] Listing local files from E:\website
17:00:40,445 [30mTRACE[m [f.p.e.c.f.u.FsCrawlerUtil] Determining 'group' is skipped for file [E:\website\website.html] on [windows 10]
17:00:40,446 [30mTRACE[m [f.p.e.c.f.u.FsCrawlerUtil] Determining 'group' is skipped for file [E:\website\index.html] on [windows 10]
17:00:40,446 [36mDEBUG[m [f.p.e.c.f.f.FileAbstractor] 2 local files found
17:00:40,446 [36mDEBUG[m [f.p.e.c.f.u.FsCrawlerUtil] filename = [website.html], includes = [[*.html]], excludes = [null]
17:00:40,446 [36mDEBUG[m [f.p.e.c.f.u.FsCrawlerUtil] filename = [website.html], excludes = [null]
17:00:40,449 [30mTRACE[m [f.p.e.c.f.u.FsCrawlerUtil] no rules
17:00:40,449 [36mDEBUG[m [f.p.e.c.f.u.FsCrawlerUtil] filename = [website.html], includes = [[*.html]]
17:00:40,449 [30mTRACE[m [f.p.e.c.f.u.FsCrawlerUtil] regex is [.*?.html]
17:00:40,449 [30mTRACE[m [f.p.e.c.f.u.FsCrawlerUtil] does match include regex
17:00:40,449 [36mDEBUG[m [f.p.e.c.f.FsCrawlerImpl] [website.html] can be indexed: [true]
17:00:40,449 [36mDEBUG[m [f.p.e.c.f.FsCrawlerImpl]   - file: website.html
17:00:40,449 [36mDEBUG[m [f.p.e.c.f.FsCrawlerImpl]     - not modified: creation date 2017-10-15T15:23:41.022332 , file date 2017-08-12T10:33:26, last scan date 2018-01-02T16:55:11.722
17:00:40,449 [36mDEBUG[m [f.p.e.c.f.u.FsCrawlerUtil] filename = [index.html], includes = [[*.html]], excludes = [null]
17:00:40,449 [36mDEBUG[m [f.p.e.c.f.u.FsCrawlerUtil] filename = [index.html], excludes = [null]
17:00:40,449 [30mTRACE[m [f.p.e.c.f.u.FsCrawlerUtil] no rules
17:00:40,449 [36mDEBUG[m [f.p.e.c.f.u.FsCrawlerUtil] filename = [index.html], includes = [[*.html]]
17:00:40,449 [30mTRACE[m [f.p.e.c.f.u.FsCrawlerUtil] regex is [.*?.html]
17:00:40,449 [30mTRACE[m [f.p.e.c.f.u.FsCrawlerUtil] does match include regex
17:00:40,449 [36mDEBUG[m [f.p.e.c.f.FsCrawlerImpl] [index.html] can be indexed: [true]
17:00:40,449 [36mDEBUG[m [f.p.e.c.f.FsCrawlerImpl]   - file: index.html
17:00:40,449 [36mDEBUG[m [f.p.e.c.f.FsCrawlerImpl]     - not modified: creation date 2017-10-15T13:46:56.347283 , file date 2017-08-12T10:33:26, last scan date 2018-01-02T16:55:11.722
17:00:40,449 [36mDEBUG[m [f.p.e.c.f.FsCrawlerImpl] Looking for removed files in [E:\website]...
17:00:40,449 [30mTRACE[m [f.p.e.c.f.FsCrawlerImpl] Querying elasticsearch for files in dir [path.root:ca1fea9dfbfd7b3e4eb958c0e2d819f]
17:00:40,451 [30mTRACE[m [f.p.e.c.f.FsCrawlerImpl] Response [{"took":0,"timed_out":false,"_shards":{"total":5,"successful":5,"skipped":0,"failed":0},"hits":{"total":0,"max_score":null,"hits":[]}}]
17:00:40,451 [30mTRACE[m [f.p.e.c.f.FsCrawlerImpl] We found: []
```

**Comment by dadoonet** [comment]
You wrote that the subdirs are: `E:/WebsiteA, E:WebsiteB`

But in the logs I can see `indexing [E:\website]`. 

Can you do:

```
E:
cd \
dir
```

and copy the results here please?

**Comment by HeliosLHC** [comment]
Ah, I seems that during my testing, I forgot to remove the `_status.json` file which I presume to have been checked against during the processing. Due to me running it several times in the testing process and resetting only via removing the indices from elasticsearch, I hadn't removed the generated `_status.json` file in each test. As a result, when it came for the full run where I cleared all elasticsearch data and reusing the same files as the previous tests, the existing files in the subdirectories were ignored (possibly due to timestamp data in the _status.json.

# Test Environment:
OS: Windows 10 Pro Build 15063
FSCrawler Snapshot 2.5.0
## Directory Structure w file in root folder:
![image](https://user-images.githubusercontent.com/6173500/34955220-773512b2-f9f1-11e7-8953-77d9972ff7a5.png)

# First Run with no _status.json
[Log](https://pastebin.com/midNTHZP)
## Elasticsearch
```
yellow open   test                gMN3rrqDRUG9ZEnZndSx-A   5   1          7            0     77.3kb         77.3kb
yellow open   test_folder         OEhfKLw8RCihUAet9qmIhQ   5   1          4            0      9.4kb          9.4kb
```
# Subsequent runs with existing _status.json after clearing all Elasticsearch Indices
[Log](https://pastebin.com/pVC2GdAE)
## Elasticsearch
```
yellow open   test                GEcl-Yp8RVy10g4oSJymAQ   5   1          0            0      1.1kb          1.1kb
yellow open   test_folder         eZ98EQyGTSqYHh_ngKNMxQ   5   1          3            0      9.3kb          9.3kb
```

**Comment by dadoonet** [comment]
That's expected indeed. If you clean elasticsearch indices but don't remove the status file, then FSCrawler will "think" that you have already existing documents.

So I believe it is safe to close this issue unless I missed something. In which case, feel free to reopen the issue or leave a comment.
