### ISSUE TITLE
Illegal reflective acces operation (Java 9)

### ISSUE THREAD

**Issue by JohannesZahn** [dadoonet/fscrawler#484]
Hello,

I´m new to the fscrawler and I really appreciate it.

On one Computer with Java8 everything went fine. I switched over to my working Computer with java9 and I got the following error: (Using fscrawler 2.4)

the program continued afterwards. http://mail-archives.apache.org/mod_mbox/tika-user/201709.mbox/%3C1505398341.31602.9.camel@apache.org%3E fyi

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.tika.parser.ParseContext (file:/U:/fscrawler-2.4/lib/tika-core-1.16.jar) to method com.sun.org.apache.xerces.internal.util.SecurityManager.setEntityExpansionLimit(int)
WARNING: Please consider reporting this to the maintainers of org.apache.tika.parser.ParseContext
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by dadoonet** [comment]
Thanks for reporting this! 

Could you try the latest SNAPSHOT as I updated to Tika 1.17 which might have change something?

**Comment by dadoonet** [comment]
I'm running myself all tests against Java 9 ATM and I'm getting sometimes similar messages but not this one specifically.
FWIW I expect Tika (and actually Tika dependencies) to fix the compatibility with Java9.
