### ISSUE TITLE
[discuss] Workaround Elasticsearch High Level client not compatible with 5.x, 2.x

### ISSUE THREAD

**Issue by dadoonet** [dadoonet/fscrawler#485]
So I updated the project to 6.1 client (#476). I ended up bypassing a lot of tests sadly because the HL Rest Client is definitely not compatible from 6.x to 5.x. Which is kind of pain when you just want to do basic things with elasticsearch like 

```json
GET index/_search
{
  "query": {
    "match": {
      "foo":"bar"
    }
  }
}
```

So I believe I have some choices now:

* Create one branch per major version of elasticsearch. I used to do that for some plugins previously but it was kind of pain.
* Revert the usage of the High Level Rest client and only write my own HL Client on top of the Low Level client (as it was before)
* Skip tests for previous versions (that's the current status)
* Create different distributions of the project and the good news is that I now have the infra for doing that as I introduced Maven modules recently with #435. And remove profiles. I'm not sure this will work super well though.

I'm kinda want to experiment the later solution. Note that reverting the HLClient might be also a good choice as for now, the HLClient comes with ton of dependencies I don't really need and that might conflict with Tika deps.

**Comment by shadiakiki1986** [comment]
In the case of the `docker-fscrawler` repo I'm maintaining, it was super easy to migrate from ES 5 to 6. The only deprecation I had to worry about was that a pipeline definition containing the key `inline` became `source`. You could just put up a deprecation notice when ES 5 is detected. Maybe you can bump up the version from 2.5 to 3 to indicate to users updating that there may be breaking changes, just like ES did by bumping from 5 to 6. Do you have users that are not willing/able to update from ES 5 to 6?

**Comment by dadoonet** [comment]
Thanks!

> Do you have users that are not willing/able to update from ES 5 to 6?

By experience on the mailing list, I still can see people using versions like 1.4 (not related specifically to FSCrawler though). But that can be a constraint I can add for sure. I'm just feeling that bad if that constraint is just added because I'm using the HighLevel Rest client and that constraint would not exist if I use my own implementation.

> Maybe you can bump up the version from 2.5 to 3 to indicate to users updating that there may be breaking changes, just like ES did by bumping from 5 to 6.

Yeah. That's an option. And TBH if I go that way, I would probably use `6.0` as the version of FSCrawler to make sure people understand it's compatible with elasticsearch 6.x...

> You could just put up a deprecation notice when ES 5 is detected.

Actually I think that the API I'm using for now in the FSCrawler implementation don't have specific issues with 2.x, 5.x or 6.x. I believe that just integration tests are the pain point because I'm using the `QueryBuilders` of Elasticsearch instead of writing JSon... I can probably workaround that though using `QueryBuilders.wrapperQuery()` instead and provide my query as a JSon. But I fear that some options are passed as URL parameters... o_O
Anyway, I'm going to give this a try ^^^

**Comment by shadiakiki1986** [comment]
Maybe instead of writing your own HL client, you can install as dependencies the ES 6 java client *and* the ES 5 java client. Then you have fscrawler decide which one to use depending on the ES version detected. I'm not experienced with maven, but is it possible to install 2 versions of the same dependency? If not, you could fork each version repository into a separate package and install them as 2 different packages. In that case, you just need to sync the forks with upstream. I'm sure it's much less headache than maintaining 2 versions of clients. Are you talking about https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/index.html ?

**Comment by dadoonet** [comment]
That's indeed the idea of:

> * Create different distributions of the project and the good news is that I now have the infra for doing that as I introduced Maven modules recently with #435. And remove profiles. I'm not sure this will work super well though.

I think it's safer. I can't really replace one lib with another at package time because some classes differ. Like the BulkProcessor ctor which is different in 5.x and 6.x. So I need to create different modules I guess...

**Comment by shadiakiki1986** [comment]
Could you fork both versions into separate packages? I.e. instead of installing BulkProcessor at version 6, you could make your own forks of BulkProcessor5 and BulkProcessor6 and install these two packages

**Comment by shadiakiki1986** [comment]
There seems to be a maven-shade-plugin referenced here https://stackoverflow.com/a/27151367/4126114

**Comment by dadoonet** [comment]
I'm going to close the issue.
I'm not testing anymore against 2.x as this version will be most likely not supported in the future.
6.1 is the latest major version and 5.6 the previous one. I'm going to support only from 5.x from FSCrawler 2.5.

I don't want to add more complexity than what is really needed for now.

I expect that elasticsearch REST Client will become much more stable in the future as elasticsearch team is now splitting the core code to have less and less dependencies. That will hopefully reduce the problems.

**Comment by dadoonet** [comment]
Reading again #472 and as we are using the search method as well in FsCrawlerImpl, we can have incompabilities indeed between the REST Client 6.x with Elasticsearch 5.x.

**Comment by dadoonet** [comment]
Actually this is working fine as we are using a term query which is compatible over the wire for both 5.x and 6.x.
