### ISSUE TITLE
where's my index ?

### ISSUE THREAD

**Issue by neergttocsdivad** [dadoonet/fscrawler#489]
fscrawler seems to be working but I can't find where my index is stored.
I expected to find is in z:/6/hoe but not there.
Any suggestions.

_settings.json
{
  "name" : "hoe",
  "fs" : {
    "url" : "z:/6/History-of-English",
    "update_rate" : "15m",
    "excludes" : [ "~*" ],
    "json_support" : false,
    "filename_as_id" : false,
    "add_filesize" : false,
    "remove_deleted" : false,
    "add_as_inner_object" : false,
    "store_source" : false,
    "index_content" : true,
    "attributes_support" : false,
    "raw_metadata" : false,
    "xml_support" : false,
    "index_folders" : false,
    "lang_detect" : false,
    "continue_on_error" : false,
    "pdf_ocr" : true,
    "ocr" : {
      "language" : "eng"
    }
  },
  "elasticsearch" : {
    "nodes" : [ {
      "host" : "127.0.0.1",
      "port" : 9200,
      "scheme" : "HTTP"
    } ],
    "bulk_size" : 100,
    "flush_interval" : "5s"
  },
  "rest" : {
    "scheme" : "HTTP",
    "host" : "127.0.0.1",
    "port" : 8080,
    "endpoint" : "fscrawler"
  }
}

Output from Terminal
Z:\fscrawler\bin>fscrawler --config_dir z:/6 hoe
10:04:41,881 INFO  [f.p.e.c.f.FsCrawlerImpl] Starting FS crawler
10:04:41,882 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler started in watch mode. It will run unless you stop it with CTRL+C.
10:04:41,903 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler started for [hoe] for [z:/6/History-of-English] every [15m]

**Comment by dadoonet** [comment]
What is the output of a search in elasticsearch?

GET hoe/_search

**Comment by dadoonet** [comment]
No further news. Closing.
