### ISSUE TITLE
Missing ES pipeline shows up in fscrawler logs but REST API returns JSON with `"ok": True`

### ISSUE THREAD

**Issue by shadiakiki1986** [dadoonet/fscrawler#490]
I'm uploading a file with fscrawler REST API.
The fscrawler config references a pipeline to use.
However, the pipeline does not exist in Elasticsearch.
What is happening is that a message is showing up in fscrawler logs about this,
but the `ok` field in the returned JSON is `True`.
Is this the expected behaviour?

Here are the fscrawler logs

```
fscrawler_1       | 10:05:05,766 DEBUG [f.p.e.c.f.r.RestApi] Sending document [bsec-SIC_Access.xlsx] to elasticsearch.
fscrawler_1       | 10:05:09,598 DEBUG [f.p.e.c.f.c.ElasticsearchClientManager] Error caught for [sic-namecheck]/[doc]/[7deafa949fbe59fa917cb4325e7eb59]: ElasticsearchException[Elasticsearch exception [type=illegal_argument_exception, reason=pipeline with id [splitNewlines] does not exist]]
fscrawler_1       | 10:05:09,598 WARN  [f.p.e.c.f.c.ElasticsearchClientManager] Got [1] failures of [1] requests
```

I'm using fscrawler compiled from source from around 3 weeks ago.

Edit: Added first paragraph explaining

**Comment by dadoonet** [comment]
Thanks for reporting. That looks indeed inconsistent. I'm unsure though if I can catch this easily. I'll dig into it.
