### ISSUE TITLE
Tesseract issue (again)

### ISSUE THREAD

**Issue by Ramon-zaro** [dadoonet/fscrawler#495]
Hi David,
as you might remember I am running fscrawler 2.3 on a windows machine to index large number of document files. it is working like a dream. can't thank you enough for this tool !

I could not however get fscrawler to recognize tesseract as the release notes say it should. tesseract runs well enough on its own from command line.

Now, I know you have mentioned earlier you are not familiar with how Tika works under the hood and that you cant help on this issue. Is that still the case ?
If so, could you just tell me which version of tika you are using and how, so that I can ask the right questions to the Tika people ?

**Comment by shadiakiki1986** [comment]
In the logs of the most recent travis build of `docker-fscrawler` [line 3343](https://travis-ci.org/shadiakiki1986/docker-fscrawler/jobs/326720354#L3343), you can see that tesseract parsed out the content of the pdf file properly with fscrawler.

Also, in the same logs, for fscrawler 2.5-SNAPSHOT, here are the related tika dependencies
```
inflating: fscrawler-2.5-SNAPSHOT/lib/tika-core-1.16.jar  
inflating: fscrawler-2.5-SNAPSHOT/lib/tika-parsers-1.16.jar  
inflating: fscrawler-2.5-SNAPSHOT/lib/tika-langdetect-1.16.jar  
```

**Comment by shadiakiki1986** [comment]
Btw maybe if you update from 2.3 to 2.5 it'll fix your problem?
You may also need to update your Elasticsearch installation from 5 to 6.
What Elasticsearch version are you using with fscrawler 2.3?
Pay attention to compatibility between fscrawler 2.5 and older versions of ES < 6

**Comment by dadoonet** [comment]
FSCrawler 2.5 should work with elasticsearch 5.x. Just tests are not working well AFAIK.

**Comment by dadoonet** [comment]
> I could not however get fscrawler to recognize tesseract as the release notes say it should. tesseract runs well enough on its own from command line.

This is strange. I think I should add some options to set exactly the path to tesseract instead of relying only on PATH.

**Comment by Ramon-zaro** [comment]
thanks a lot for the responses. 
I have no problems moving to 6.x and reindexing.  provided 2.5 solves this issue.


setting path exactly should help, I seem to remember reading somewhere about changes in tesseract recenet releases about PATH behaviour.

**Comment by Ramon-zaro** [comment]
Just wanted to report that have continued to face same issues even with latest snapshot of FS 2.5 on an windows machine.

I have set the path to the tesseract executible in the fscrawler settings but still fscrawler gives the message "But Tesseract is not installed so we won't run OCR".

**Comment by dadoonet** [comment]
@Ramon-zaro Could you open a new issue and describe exactly your configuration file in it?
I did not test on Windows so that might be a problem.

**Comment by TajinderSaini** [comment]
Did Tesseract work on Windows with FScrawler? I tried FScrawler 2.5 and 2.6 with ES 6.5 but it is same issue. Any idea?
11:08:41,431 DEBUG [f.p.e.c.f.t.TikaInstance] OCR is activated for PDF documents
11:08:41,446 DEBUG [f.p.e.c.f.t.TikaInstance] But Tesseract is not installed so we won't run OCR.
