### ISSUE TITLE
read arabic text on image

### ISSUE THREAD

**Issue by MoKmaal** [dadoonet/fscrawler#497]
Could I upload images with Arabic text ?

**Comment by dadoonet** [comment]
I don't know if Tesseract supports it.

**Comment by Ramon-zaro** [comment]
you need to download language specific files for tesseract.  no idea about accuracy though.

**Comment by dadoonet** [comment]
Thanks @Ramon-zaro. As it's somewhat documented here: https://github.com/dadoonet/fscrawler#ocr-language I'm closing this then.
