### ISSUE TITLE
Help me out :-) 

### ISSUE THREAD

**Issue by rajamanickam-pr** [dadoonet/fscrawler#499]
How to restrict dir from fscrawler, I have tried with .ignore file ( .ignore file which contains list of restricted folders as per my understanding) its not working. Also i tried with ignore dir name with exclude object that too not working. Can you folks please help me out from this. 

Thanks in advance.

**Comment by dadoonet** [comment]
.ignore was an example in documentation.

It does not mean you must create such a file: https://github.com/dadoonet/fscrawler/blob/master/README.md#includes-and-excludes

You need to define excludes here I think
