### ISSUE TITLE
Add `hocr` option for Tesseract-based OCR

### ISSUE THREAD

**Issue by Mike-Now** [dadoonet/fscrawler#507]
I would like to obtain OCR-ed PDFs with respective bounding boxes paramters for each
text block saved in the output file. Tesseract just needs a single option, 'hocr', to achieve this.
In Apache Tika, one can use the [setOutputType ](https://tika.apache.org/1.17/api/org/apache/tika/parser/ocr/TesseractOCRConfig.html#setOutputType-org.apache.tika.parser.ocr.TesseractOCRConfig.OUTPUT_TYPE-) method.

Can this option be added to fscrawler?

**Comment by Ramon-zaro** [comment]
Hello @Mike-Now, have you managed to run Tesseract with fscrawler ? haven't been able to do so, so far.

**Comment by dadoonet** [comment]
This has been added.
