### ISSUE TITLE
Searching path doesn’t match

### ISSUE THREAD

**Issue by jevertz** [dadoonet/fscrawler#528]
I had trouble to get useful results matching a search term on a file‘s path.
The path tokenizer seems to implement a logic I don’t understand
With a simple pattern tokenizer I got much better results.
Example:
/some/path/humblemumble/to/myfile.txt

I tried all the path... fields, but no luck getting a hit for „humblemumble“.

Am I missing something fundamental here?

Defining another analyzer using a simple_pattern_split tokenizer splitting on „/„, works.

Is this the intended behavior?

Best

Jochen Evertz

**Comment by dadoonet** [comment]
Yes. It was intended. With that you can easily compute number of docs per directory with a terms agg for instance. That said, we could do both.

I'll think about it soon as I'm changing some other mappings atm.

**Comment by dadoonet** [comment]
This has been added now. Sorry for the long delay...
