### ISSUE TITLE
Store source

### ISSUE THREAD

**Issue by JunhyeokYim** [dadoonet/fscrawler#532]
Hello.

I found a bug. Details are below. 

For example, word or excel files.

conf ==>
"store_source" : true
"index_content" : true
"indexed_chars" : "-1"

==> Successfully save the binary attachment.

"store_source" : true
"index_content" : false
"indexed_chars" : "-1"

==> Not save the binary attachment.

It seems like bug. 

please check it.

(This is a my first experience of github.. :) )

**Comment by dadoonet** [comment]
Thanks for opening it. I can definitely reproduce it and I'll come with a fix.
