### ISSUE TITLE
starting automatically 

### ISSUE THREAD

**Issue by asmaElk** [dadoonet/fscrawler#534]
hello 
I want the fscrawler to be started automatically at startup without any user interaction. How can i achieve that ?

**Comment by roselan** [comment]
On windows I used https://nssm.cc/download to create a service for fscrawler, but I don't use it anymore, 

I run a fscrawlerRunner.bat in cmd window. here it's content:

**Comment by dadoonet** [comment]
@roselan Would you like to contribute a documentation PR to add this in the documentation?

**Comment by roselan** [comment]
@dadoonet I feel seriously honoured by your request, but I have absolutly no idea where to start. (I guess by doc you mean the readme.md?).

**Comment by dadoonet** [comment]
Exactly. In the README.md file.

**Comment by asmaElk** [comment]
hello @roselan thank you for replying could you please explain more how to use the fscrawler Runner.bat

**Comment by dadoonet** [comment]
@roselan The documentation changed and I moved to readthedocs now.
So if you'd like to contribute, I'd suggest adding a section in https://github.com/dadoonet/fscrawler/blob/master/docs/source/installation.rst like adding at the end:

```rst
Running as a Service on Windows
-------------------------------

Create a ``fscrawlerRunner.bat`` as:

.. code:: sh

   set JAVA_HOME=c:\Program Files\Java\jdk1.8.0_144
   set FS_JAVA_OPTS=-Xmx2g -Xms2g
   /Elastic/fscrawler/bin/fscrawler.bat --config_dir /Elastic/fscrawler data >> /Elastic/logs/fscrawler.log 2>&1

And ...
```

WDYT?
