### ISSUE TITLE
Feature request : Pause fscrawler run

### ISSUE THREAD

**Issue by Ramon-zaro** [dadoonet/fscrawler#535]
Hi, quite a few times I have felt a need to be able to pause a fscrawler run (for a variety of reasons from performance issues to ) and later continue from where it paused. This is currently not possible since the process has to be manually terminated, which is a messy process as you have no idea where it left off and the run has to be restarted from the beginning. This is a big problem especially for large file collections. 

I was wondering if fscrawler could store its last crawled folder path in _status.json on pausing and pick up from there on continuation.

**Comment by dadoonet** [comment]
I think that's a valid proposal. Thanks for asking!

**Comment by dadoonet** [comment]
I was thinking of this today and it might be hard to implement until we have another implementation based on iNodes or similar things.
If anyone has a cool idea, I'll be happy to hear.

Of course I could store on the FS the full list of files that have been crawled yet and just skip them but I don't think that will be efficient and fast.
Ideas?

**Comment by dadoonet** [comment]
BTW I'm closing it in favor of #493 which was opened previously and covers the same need.
