### ISSUE TITLE
Generate logs in fscrawler

### ISSUE THREAD

**Issue by manoj4321** [dadoonet/fscrawler#536]
Using log4j2 how can logs for fscrawler date wise be generated ??

**Comment by dadoonet** [comment]
I'm afraid I don't understand. Could you share an example of what you are seeing and what you'd like?

**Comment by manoj4321** [comment]
Thanku for quick reply ....I want to generate logs for fscrawler in a .txt file date wise in separate text files......Just like in the case of elasticsearch ....Thanks again

**Comment by dadoonet** [comment]
I see. Sadly the log4j configuration is packaged within the JAR. I need to probably move that configuration to be read from a config directory like `.fscrawler/_config`.

I'll try to think about it.

Thanks for opening this feature request.

**Comment by dadoonet** [comment]
I think that actually [this documentation](https://fscrawler.readthedocs.io/en/latest/admin/logger.html) is describing a way to use an external LOG4 config file which allows whatever modification of the default behavior.

That being said I think we should by default do both: print to console and to a file.

I believe this needs though a way to configure globally FSCrawler, ie a `fscrawler.yml` configuration file so we can define where the logs should be written to.
