### ISSUE TITLE
crawling smb share 

### ISSUE THREAD

**Issue by Ramon-zaro** [dadoonet/fscrawler#546]
Hi @dadoonet,
I tried crawling a smb shared folder from a linux machine; the folder is available in the linux machine at something like "smb://100.200.100.10/sharefolder".

when I put it in _settings url it gives me java.lang exception "no such path exists".
I have tried it with and without the smb, with // instead of / but get the same error.

What am I doing wrong ? I have very little experience with linux so I guess I must be missing something obvious.

**Comment by dadoonet** [comment]
I never tried with samba and I don't know if FSCrawler can works on it.
I guess that the user which is running FSCrawler should have a read access to the whole filesystem.

I believe that this should be mount on the linux filesystem as a "remote" dir so you can access it by using `ls -l /mnt/my_mount_point`. `smb://100.200.100.10/sharefolder` won't work out of the box for sure. For this, we would need another FSCrawler implementation such as we did for SSH and as I'm planning for FTP (#147).

**Comment by JaafarMehdi93** [comment]
you can crawle from smb  shared folder just you have to put the correct url

Le mar. 3 juil. 2018 à 17:25, David Pilato <notifications@github.com> a
écrit :

**Comment by Ramon-zaro** [comment]
okay, so is there any work around ?

@JaafarMehdi93, didn't quite get you there. that url is correct in that it takes me to correct location in filesystem browser. what should the correct url be ?

**Comment by jevertz** [comment]
Would it hurt to mount the remote folder first? I have a similar scenario. I mount the remote folder using cifs-utils and let fscrawler work on the mountpoint.

**Comment by dadoonet** [comment]
@jevertz Does it work for you?

Note for myself: I can may be in the future try to integrate https://github.com/AgNO3/jcifs-ng.

**Comment by ryanRahul5** [comment]
Hi @dadoonet ,

Is there any workaround to directly let fscrawler run through the remote folder without mounting it first ?

**Comment by dadoonet** [comment]
> Hi @dadoonet ,
> 
> Is there any workaround to directly let fscrawler run through the remote folder without mounting it first ?

Not anything I am aware of

**Comment by dadoonet** [comment]
Sounds like that #1203 will bring some support for this...

**Comment by helsonxiao** [comment]
> Sounds like that #1203 will bring some support for this...

Path like `//100.200.100.10/sharefolder` is working on Windows with ssh crawler. But I'm not sure if it works on Linux smb share too.

We're trying to implement a new crawler with smb client(such as `smbj`). Check [this fork](https://github.com/waterstone-company/fscrawler).
