### ISSUE TITLE
I want to get text from file of type DWG

### ISSUE THREAD

**Issue by nileshpasalkar** [dadoonet/fscrawler#556]
I need parser for file of type DWG, want to extract text information from Autocad file. Does this is support through FSCrawler, if so could you please guide me how to achieve this. 

Thanks in advance!

**Comment by dadoonet** [comment]
Did you look at: https://fscrawler.readthedocs.io/en/latest/user/formats.html ?

Specifically this link: http://tika.apache.org/1.18/formats.html#CAD_formats

Which I guess answers your question. It seems to be supported by Tika.
