### ISSUE TITLE
Request: File Permissions

### ISSUE THREAD

**Issue by mgoldman007** [dadoonet/fscrawler#559]
Would like to index the current file permissions of the file that is being index. Can't find a way to do that with the current attribute settings. 

Linux based Operating System, local file system and mounted.

**Comment by dadoonet** [comment]
Would that help? https://fscrawler.readthedocs.io/en/latest/admin/fs/local-fs.html#adding-file-attributes

**Comment by mgoldman007** [comment]
I am not seeing the permissions in 2.4. Is this a new feature in 2.5 that I missed.. ?

Thanks!

**Comment by dadoonet** [comment]
I don't think it has yet file permissions but just user / group.

I think what you want is actually this: https://github.com/dadoonet/fscrawler/issues/464

**Comment by mgoldman007** [comment]
So I have a directory of 5 files and this is a linux cent 7,5 server.. I want to be able to know the file perms of each file

rwxrwxrwx   (777) or something like that..  

Thanks!

**Comment by dadoonet** [comment]
Yeah. Got it. I think it's similar to the other ask.
Note that you can do something like: http://david.pilato.fr/blog/2015/12/10/building-a-directory-map-with-elk/ (but it won't extract text from your files)

**Comment by mgoldman007** [comment]
That may work, just was trying to avoid the "find" command but it may have to work.. Thank you..

**Comment by dadoonet** [comment]
I'm marking this as a feature to support. I'll try to explore that unless you want yourself to contribute.

**Comment by mgoldman007** [comment]
I appreciate it. If I find a way to do it, I will gladly send it over. Thank you very much!

**Comment by dadoonet** [comment]
I started to explore this. Should be doable.

Now wondering what would be the best data structure to represent your need:

```json
{
  "permissions": "rwxrw-r--"
}
```

```json
{
  "permissions": 752
}
```

```json
{
  "permissions": [ "owner_read", "owner_write", "owner_execute",  "group_read", "group_write", "others_read" ]
}
```

```json
{
  "permissions": {
    "owner_read": true,
    "owner_write": true,
    "owner_execute": true,
    "group_read": true,
    "group_write": true,
    "group_execute": false,
    "others_read": true,
    "others_write": false,
    "others_execute": false
  }
}
```

WDYT?

**Comment by mgoldman007** [comment]
Awesome.. Honestly 752 would be fine for us but the break down works too. We are flexible, if I can get the data I can always manipulate it for display.

either:   "permissions": 752 
or
  "permissions": [ "owner_read", "owner_write", "owner_execute",  "group_read", "group_write", "others_read" ]

I think would be best, the rwxrwx may become confusing to search on..

Thank you!

**Comment by dadoonet** [comment]
It has been merged. Could you give a try to the latest SNAPSHOT?

**Comment by mgoldman007** [comment]
Yep, I will grab it first thing Monday morning and try it out.

Thank you!

**Comment by mgoldman007** [comment]
So far everything has been perfect. Thank you
