### ISSUE TITLE
Access Date is not indexed in elasticsearch

### ISSUE THREAD

**Issue by prashu1910** [dadoonet/fscrawler#578]
First of all thank you for developing this awesome crawler. It makes our life much easy. I am trying to generate a report based on last access time of files. So I used FSCrawler to store all information in elasticsearch, but there is no attribute in index for access time of file, although access time is set in files. Is there any way through which I can index that data also? 

![image](https://user-images.githubusercontent.com/23491837/43388371-876f8d7e-9406-11e8-940c-d25153adef7a.png)

**Comment by dadoonet** [comment]
This does not exist yet. I'll look into this.

**Comment by dadoonet** [comment]
Sounds like I can support it. I'm working on a PR ATM. Stay tuned...

**Comment by prashu1910** [comment]
Ok.. thanx..

**Comment by dadoonet** [comment]
@prashu1910 Note that FSCrawler by default is using the last modification date to know if a document should be reindexed or not.
Which means that once a document has been indexed, the access time won't be updated on the next run even though the document has been accessed.

That's something we can optionally support though but that will take more time to implement.
Is that something you need?

I wonder if a project like [Auditbeat](https://www.elastic.co/guide/en/beats/auditbeat/current/auditbeat-module-file_integrity.html) would not be actually better to suit your needs. Could you clarify your use case?

**Comment by prashu1910** [comment]
I am trying to create a dashboard based on the user who accessed the particular type of file in last one week. So basically a snapshot of file system will be mounted and using fscrwaler, we indexes those files in elasticsearch and then unmount the snapshot. So I think access_date field will do the job.
