### ISSUE TITLE
Generate a Docker image

### ISSUE THREAD

**Issue by dadoonet** [dadoonet/fscrawler#586]
We want to provide OOTB a Docker image which can be easily used by our users to start the service.

**Comment by dadoonet** [comment]
Adding a link to https://github.com/moditect/moditect/wiki/Creating-dependency-images in case it helps.

**Comment by cloud1250x4** [comment]
https://github.com/shadiakiki1986/docker-fscrawler

**Comment by chengpengliu** [comment]
> 这可能有帮助
> 
> https://github.com/shadiakiki1986/docker-fscrawler

If the Chinese name of the file is not recognized, the file will be recognized as a folder when pushed to ES, and the file content inside will be recognized as Chinese characters

**Comment by dadoonet** [comment]
@chengpengliu Are you reporting a bug here? If so, can you open a new issue and describe a way to reproduce the problem.

**Comment by dadoonet** [comment]
This has been fixed now.
