### ISSUE TITLE
Issue in FScrawler 2.4 while indexing a drive in windows environment

### ISSUE THREAD

**Issue by Neel-Gagan** [dadoonet/fscrawler#587]
1) I am getting the warining  "Layout tables used in font Avenir-Light are not implemented in PDFBox and will be ignored" while running FSCrawler 2.4 using --username admin switch, but i  am not getting 
  date time of "lastrun" :  and count of   "indexed" : and   "deleted" :  items in the folder i have mapped the crawler in _status.json file under . fscrawler folder.
   kindly guide me how to get this _status.json file updated
   
2) is there any way to determine the name  of files that have been ignored by fscrawler while indexing a particular folder.

3) i am not getting match of count of number of files in a folder and indexed documents in  crawling done by fscrawler on that folder.

**Comment by dadoonet** [comment]
@Neel-Gagan Thanks for trying FSCrawler.
Could you first try the latest SNAPSHOT of FSCrawler 2.5? See https://fscrawler.readthedocs.io/en/latest/installation.html for the link.

About 

> Layout tables used in font Avenir-Light are not implemented in PDFBox and will be ignored

I guess that only table content is ignored. Not the file itself.

> kindly guide me how to get this `_status.json` file updated

Can you share the content of this file for now? Does it exist in the `HOME/.fscrawler` dir?

> is there any way to determine the name of files that have been ignored by fscrawler while indexing a particular folder.

Only files that matches the rules you gave with included/excluded options if you set them.

> i am not getting match of count of number of files in a folder and indexed documents in crawling done by fscrawler on that folder.

What are you getting?

**Comment by Neel-Gagan** [comment]
i am implementing FSCrawler in windows system.
here are the contents of _status.json file.
{
  "name" : "d_drive",
  "lastrun" : "2018-07-30T05:12:13.062",
  "indexed" : 0,
  "deleted" : 0
}

1)  where can i see what are the files(name of files) that have been ignored by the crawler.

2) i have not excluded any file in the rules in_settings.json file.

**Comment by dadoonet** [comment]
You can't. Unless you run it in debug mode

**Comment by Neel-Gagan** [comment]
and what about not getting any status in _status.json file

**Comment by dadoonet** [comment]
It just says that on the last run, no new files have been indexed since last run.

**Comment by Neel-Gagan** [comment]
on first run also it does not show any updation in case i have mapped index to a folder.

**Comment by dadoonet** [comment]
Use the restart option and debug mode.
Also try the 2.5 version and share your logs

**Comment by Neel-Gagan** [comment]
where exactly i get the logs of fscrawler, is it from the command prompt where i run the crawler or somewhere else ?

**Comment by dadoonet** [comment]
https://fscrawler.readthedocs.io/en/fscrawler-2.5/installation.html

**Comment by Neel-Gagan** [comment]
how do i redirect the logs from command prompt to a log file, or do we have a location where the logs of fscrawler are stored ?

**Comment by dadoonet** [comment]
> how do i redirect the logs from command prompt to a log file

I don't know on Windows. On linux you can do something like:

```sh
bin/fscrawler foo > fscrawler.logs
```

> do we have a location where the logs of fscrawler are stored ?

Not yet. Should come at some point with #394

**Comment by dadoonet** [comment]
> does fscrawler indexes files which have modification date earlier than date of run of fscrawler. i had to change the modification date of files to bring the files in to indexing by the FSCrawler.

No. You need to use https://fscrawler.readthedocs.io/en/fscrawler-2.5/admin/cli-options.html#restart or "touch" the file (better) to change its date.

This is the current implementation but this should change in the future. See #399

**Comment by Neel-Gagan** [comment]
Thanks
