### ISSUE TITLE
How _score works?

### ISSUE THREAD

**Issue by instagib111** [dadoonet/fscrawler#591]
Hello,

I'm a new user of FSCrawler and I want to know more aboute _score result.
After a research, _score return a number between which number? (0 < _score < 2)

I want to know this to make a mapping like that  => JS  : let stars = map(_score, 0, 2, 0, 5)

thanks

**Comment by dadoonet** [comment]
`_score` is not directly related to FSCrawler but to Elasticsearch.
You can read this is you want to understand how Lucene/Elasticsearch computes it: https://www.elastic.co/guide/en/elasticsearch/guide/current/scoring-theory.html
