### ISSUE TITLE
xml_support overwriting reoccurring structures

### ISSUE THREAD

**Issue by Wetski** [dadoonet/fscrawler#592]
Hello.

I've been wondering whether the json created from an xml file should be overwriting the reoccurring structures I might have in a file.

Example
```
<dataset>
  <object>
    <id>1</id>
    <name>foo</name>
  </object>
  <object>
    <id>2</id>
    <name>bar</name>
  </object>
</dataset>
```
the created json looks like this:
```
{
  "object" : {
    "id" : 2,
    "name" : "bar"
  }
}
```

Shouldn't the json look more like this:
```
{
  "dataset" : {
    "object": [{
        "id": 1,
        "name": "foo"
      },
      {
        "id": 2,
        "name": "bar"
      }
    ]
  }
}
```

I'm using the fscrawler 2.4 release

**Comment by dadoonet** [comment]
Interesting. I can reproduce this indeed. I need to check how the conversion library is working and if this can be be fixable directly or with a new option like `include_xml_root` or something.

For now, I was more indexing data like:

```xml
<?xml version="1.0"?>
<book id="bk101">
    <author>Gambardella, Matthew</author>
    <title>XML Developer's Guide</title>
    <genre>Computer</genre>
    <price>44.95</price>
    <publish_date>2000-10-01</publish_date>
    <description>An in-depth look at creating applications
        with XML.</description>
</book>
```

Where you just omit the `book` level as this is basically the object type.

**Comment by dadoonet** [comment]
This is caused by https://github.com/FasterXML/jackson-dataformat-xml/issues/205
I can make it work with the provided gist so I might be able to come with a fix.
