### ISSUE TITLE
not complete index file

### ISSUE THREAD

**Issue by mousavi007** [dadoonet/fscrawler#599]
when i index my pdf files with fscrawler just index first 40 page and not complete pdf file
this is _settings.json:
{
  "name" : "job_name",
  "fs" : {
    "url" : "c:\\temp\\rs",
    "update_rate" : "15m",
    "excludes" : [ "*/~*" ],
    "json_support" : false,
    "filename_as_id" : false,
    "add_filesize" : true,
    "remove_deleted" : true,
    "add_as_inner_object" : false,
    "store_source" : false,
    "index_content" : true,
    "attributes_support" : false,
    "raw_metadata" : true,
    "xml_support" : false,
    "index_folders" : true,
    "lang_detect" : false,
    "continue_on_error" : false,
    "pdf_ocr" : true,
    "ocr" : {
      "language" : "eng"
    }
  },
  "elasticsearch" : {
    "nodes" : [ {
      "host" : "127.0.0.1",
      "port" : 9200,
      "scheme" : "HTTP"
    } ],
    "bulk_size" : 1000,
    "flush_interval" : "5s",
    "byte_size" : "100mb"
  },
  "rest" : {
    "scheme" : "HTTP",
    "host" : "127.0.0.1",
    "port" : 8080,
    "endpoint" : "fscrawler"
  }
}

**Comment by dadoonet** [comment]
Read https://fscrawler.readthedocs.io/en/latest/admin/fs/local-fs.html#extracted-characters

That should help.

**Comment by mousavi007** [comment]
thank you
Good luck
