### ISSUE TITLE
Soundex implementation in Fscrawler and Kibana 

### ISSUE THREAD

**Issue by Neel-Gagan** [dadoonet/fscrawler#600]
I am trying to implement Soundex in a field called content field of Fscrawler in kibana.
i am facing issue in mapping the analyser to the content field.saying mapper for [content] conflicts with existing maping.

Can we manipulate the analyser setting of Fscrawler.
can someone guide how to implement  soundex to an existing field of  a index.
can i get a snippet on how to implement dbl_metaphone in a field of existing index in elasticsearch.

**Comment by dadoonet** [comment]
Could you describe what are you doing exactly?

You can always define whatever mapping you want.

It can be by sending a HTTP request manually (PUT index) before starting FSCrawler.
It can be by changing the default mapping FSCrawler is using before starting the job for the first time...

Many options.

One missing option is the support of index templates instead using a PUT index call.

**Comment by Neel-Gagan** [comment]
i had applied FSCralwe to a folder location and got the files into elasticearch, all the files are shouwing in the content filed of the respective index. now i wish to implement soundex in that content field of a index so that i can use soundex in the extracted content of files.

 

Thanks.

Neel Gagan

 

Sent: Thursday, September 13, 2018 at 11:14 AM

**Comment by dadoonet** [comment]
Probably you want to use this: https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-phonetic.html

**Comment by dadoonet** [comment]
I'm closing as this does not sound to me as a feature request or a bug. Feel free to comment or reopen if you do not think the same.
