### ISSUE TITLE
Can not stop FSCrawler while crawling the local FS

### ISSUE THREAD

**Issue by dadoonet** [dadoonet/fscrawler#605]
While doing some manual tests, I can see that sometimes I can not stop FSCrawler.

```
11:32:21,034 WARN  [f.p.e.c.f.c.ElasticsearchClientManager] Got [2] failures of [2] requests
^C11:32:24,062 DEBUG [f.p.e.c.f.FsCrawlerImpl] Closing FS crawler [test]
11:32:24,063 DEBUG [f.p.e.c.f.FsCrawlerImpl] FS crawler thread is still running
```

Code is:

```java
        if (this.fsCrawlerThread != null) {
            while (fsCrawlerThread.isAlive()) {
                // We check that the crawler has been closed effectively
                logger.debug("FS crawler thread is still running");
                Thread.sleep(500);
            }
            logger.debug("FS crawler thread is now stopped");
        }
```

**Comment by dadoonet** [comment]
This can apparently happen when you have a failure while sending data to elasticsearch.

**Comment by dadoonet** [comment]
I did not succeed in reproducing it again...

**Comment by budachst** [comment]
I also cannot stop fscrawler via CTRL-C when it is actually crawling a file system. I seem to be able to reproduce this issue everytime.

I can successfully stop fscrawler when it is in watch mode.

**Comment by dadoonet** [comment]
Oh I see... Could you open a new issue for this? Specifically saying "when crawling documents".

**Comment by dadoonet** [comment]
Sorry ignore me. I'm going to reopen this one.
