### ISSUE TITLE
fscrawler 2.5 incompatible with ES 6.1

### ISSUE THREAD

**Issue by shadiakiki1986** [dadoonet/fscrawler#614]
When running fscrawler 2.5 with elasticsearch 6.1, the following error occurs:

```
{"error":
    {"root_cause":
        [
            {"type": "invalid_type_name_exception",
             "reason":"mapping type name [_doc] can't start with '_'"}
        ],
        "type":"invalid_type_name_exception",
        "reason":"mapping type name [_doc] can't start with '_'"
     },
    "status":400
}
```

as can be seen at https://travis-ci.org/shadiakiki1986/docker-fscrawler/builds/438466956

If this is true, perhaps it is worth documenting in the compatibility matrix?

**Comment by dadoonet** [comment]
Hmmm. That's weird.
Could you try with a more recent version of Elasticsearch? 6.4.1 for example?

**Comment by shadiakiki1986** [comment]
6.4 is fine

**Comment by dadoonet** [comment]
Thanks for confirming.
