### ISSUE TITLE
how may I locate / specify the location of an index in Window 10

### ISSUE THREAD

**Issue by neergttocsdivad** [dadoonet/fscrawler#619]
elasticsearch installed in default location on drive C
kibana located c:\kibana 
documents located in folder on drive Z
fscrawler located on drive V
drive V is where I want the index to be stored, but I can't find it anywhere.

**Comment by neergttocsdivad** [comment]
OK. I just noticed the 'Locations' window in the installation process. However, after I check the 'use a custom installation directory' then set one or more directory locations to mapped folders in my NAS, the installation appears to progress for a while but then displays 'an error occurred during installation'. What am I doing wrong?

**Comment by dadoonet** [comment]
I don't know. This is here an elasticsearch problem, not a FSCrawler one I guess.
Could you ask on discuss.elastic.co instead?

To answer your question, look at path.data setting in elasticsearch documentation.
