### ISSUE TITLE
Difference in actual no of documents and documents crawled by FSCrawler

### ISSUE THREAD

**Issue by Neel-Gagan** [dadoonet/fscrawler#623]
i have my crawler pointed to folder D:\Test folder having 5130 documents wheres when i run FSCrawler 2.4 job on to this folder it shows the indexed documents as 3410. i wish to know why theres is not exact match between the doc count in both.

**Comment by dadoonet** [comment]
Can you share the job setting file ?

**Comment by Neel-Gagan** [comment]
"fs" : {
    "url" : "D://Test",
    "update_rate" : "2m",
    "includes" : [ "*" ],
    "excludes" : [ "~*" ],
    "json_support" : true,
    "add_filesize" : true,
    "remove_deleted" : false,
    "index_content" : true,
    "attributes_support" : true,
    "raw_metadata" : true,
    "xml_support" : false,
    "index_folders" : true,
    "lang_detect" : true,
    "continue_on_error" : true,
    "pdf_ocr" : true,
    "ocr" : {
      "language" : "eng"
    }
  },
  "elasticsearch" : {
    "nodes" : [ {
      "host" : "127.0.0.1",
      "port" : 9200,
      "scheme" : "HTTP"
    } ],
    "bulk_size" : 100,
    "flush_interval" : "5s"
  },
  "rest" : {
    "scheme" : "HTTP",
    "host" : "127.0.0.1",
    "port" : 8080,
    "endpoint" : "fscrawler"
  }

**Comment by dadoonet** [comment]
So you just have json documents in your folder, is that true?

**Comment by dadoonet** [comment]
If you  can share one of the documents that was not indexed, that would help.
I'm going to close for now but feel free to reopen with more information.
