### ISSUE TITLE
Change location of tmp files for tika/tesseract

### ISSUE THREAD

**Issue by budachst** [dadoonet/fscrawler#625]
Is it somehow possible to change the path where tika will put the image file for tesseract to process? Currently, all images files are put under /tmp/apache-tika-[some uuid].tmp.

The issue is, that on my system /tmp is on a rather slow SATA flash dom, which seems to really slowdown tesseract. I have only been able to process 648 files in 4 hrs.

**Comment by dadoonet** [comment]
Awesome. Do you think this is work adding documentation ?

**Comment by budachst** [comment]
Don't know, it's not specific to fscrawler as it's more of a OS-level thingy and people having a similar issue could find it via the search. At least, it's what I am doing everytime, before opening an issue. ;)
