### ISSUE TITLE
Perform OCR for more than one language by fscrawler

### ISSUE THREAD

**Issue by mohsen-zanjani** [dadoonet/fscrawler#626]
It seems fscrawler doesn't have the ability to perform OCR simultaneously (at the same time) for multiple languages (more than one language).

I have also described the problem in the below link:
[Perform OCR for more than one language by fscrawler](https://discuss.elastic.co/t/perform-ocr-for-more-than-one-language-by-fscrawler/156183)

It would be very nice if this feature was added to the fscrawler.
Something like this:

```
"fs" : {
    "ocr" : {
      "language": "eng+fra"
    }
  }
```

OR this:

```
"fs" : {
    "ocr" : {
      "language": "eng"
    },
   "ocr" : {
      "language": "fra"
    }
  }
```

Thanks ...

**Comment by mohsen-zanjani** [comment]
After investigations, I realized that it was possible in Tika to specify multiple languages ​​for OCR.
To do this, simply concatenate the desired languages ​​with the '+' sign.
For example: "eng+fas+fra"

The same can be done in the fscrawler and set as a value for the language attribute.

```
"fs" : {
    "ocr" : {
      "language": "eng+fas+fra"
    }
  }
```

**Comment by dadoonet** [comment]
Thanks! I added some documentation based on your feedback.
