### ISSUE TITLE
Request: provide stop file to exclude folder from crawling

### ISSUE THREAD

**Issue by budachst** [dadoonet/fscrawler#630]
Gnome's Tracker has a useful feature, where the tracker-miner-fs will skip a folder completely if it encounters a special file named .trackerignore in the directory it just entered.

This would help excluding folder containing applications bundles, since those are basically useless for the index of a share, especially on macOS.

**Comment by dadoonet** [comment]
That's a great idea! Thanks!

**Comment by budachst** [comment]
Yeah - great! Thanks!! I will use that right away!
