### ISSUE TITLE
Deleting Jobs

### ISSUE THREAD

**Issue by mtelang** [dadoonet/fscrawler#634]
Hi ,

Is there a API to remove the job? Or should I just remove the folder from \.fscrawler folder?

I tried to do that but I still see my old job name(_crawler_profiles_) in the elastic search logs when I start the search server.

> [2018-11-25T20:22:05,684][INFO ][o.e.c.r.a.AllocationService] [0yKLvbb] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[crawler_profiles][3]] ...]).

**Comment by dadoonet** [comment]
There's no API to remove the job.
Even if there was one, it would never remove data from elasticsearch. That's a way too dangerous to me.
You can remove elasticsearch indices manually. It's easy to do.
