### ISSUE TITLE
Removing '/n' and '/t' when creating json

### ISSUE THREAD

**Issue by mtelang** [dadoonet/fscrawler#635]
**Describe the bug**

I am uploading candidates profiles for a resume screening use case. Whenever profiles are uploaded in Elastic Search, a '/n' and '/t' are appended for each new line/tab in the content. This is an issue because this character can be a suffix to a skill key word which is important to analyze candidate.

**To Reproduce**

1. I have uploaded a sample profile (ABC.docx)
2. Once uploaded to Elastic Search, you can see content like 

> │ Transaction and Third Party Due Diligence │**\n**Day to Day Counsel\n\n\n \nEXPERIENCE\n\nGuardian Industries Corp. (subsidiary of Koch Industries); Auburn Hills, MI\nSenior Counsel, Compliance, Koch Companies Public Sector**\t\t\t\t**    October 2017- Present\nAssistant General Counsel, Global Commercial Compliance & Investigations\t  

**Expected behavior**

I would ideally expect a space (at least for my use case)

**Versions:**
 - OS: Windows 10
 - Version 2.5
 - ES version: 6.4.2

[ABC.docx](https://github.com/dadoonet/fscrawler/files/2613781/ABC.docx)

**Comment by dadoonet** [comment]
This is how Tika is working behind the scene. I did not check if Tika exposes any option to remove those characters but in any case you can define an ingest pipeline to filter out those I think.

Have a look at this processor: https://www.elastic.co/guide/en/elasticsearch/reference/6.5/gsub-processor.html

Let me know if this workaround works for you.
Thanks!

**Comment by dadoonet** [comment]
No further feedback. Closing. Feel free to reopen if you have any other comment/question about this.
