### ISSUE TITLE
fscrawler throws error when using fscrawler in windows 10

### ISSUE THREAD

**Issue by charan549** [dadoonet/fscrawler#636]
**G:\fscrawler-es5-2.6-SNAPSHOT\bin>fscrawler                                                                                                                             no main manifest attribute, in G:\fscrawler-es5-2.6-SNAPSHOT/lib/fscrawler-cli-2.6-SNAPSHOT.jar  **

![fs](https://user-images.githubusercontent.com/45358164/49013391-97e28180-f1a2-11e8-92aa-992676b72ea8.png)
   no main manifest attribute,

fscrawler pdf1.pdf                                                                                                                    no main manifest attribute, in G:\fscrawler-es5-2.6-SNAPSHOT/lib/fscrawler-cli-2.6-SNAPSHOT.jar  

>fscrawler --debug                                                                                                                     no main manifest attribute, in G:\fscrawler-es5-2.6-SNAPSHOT/lib/fscrawler-cli-2.6-SNAPSHOT.jar 

**Versions:**
 - OS: [e.g. Win10]

**Screenshots**

**Comment by dadoonet** [comment]
Yeah that's a bug on Windows that has been fixed by https://github.com/dadoonet/fscrawler/commit/71b2a526021fba4faefad3b39beedd22d792ecb6

I'm surprised the latest SNAPSHOT does not contain this fix though. Let me push a new SNAPSHOT manually.

**Comment by dadoonet** [comment]
Have a look at this one: https://oss.sonatype.org/content/repositories/snapshots/fr/pilato/elasticsearch/crawler/fscrawler-es6/2.6-SNAPSHOT/fscrawler-es6-2.6-20181126.134637-8.zip

HTH
