### ISSUE TITLE
Question: is elasticsearch required for fscrawler to index files?

### ISSUE THREAD

**Issue by vedydev** [dadoonet/fscrawler#640]
Hi,
@dadoonet I'm trying to index files using fscrawler, but it throws an error: cannot connect to elasticsearch:
1. Can fscrawler index files as a stand alone application? without installing and running Elasticsearch simultaneously?
2. If so, do I need to change the settings in fscralwer's settings JSON? What settings need to change?
thanks

Using v 2.5 on debian

**Comment by dadoonet** [comment]
What is the use case? You don't want to index documents?
To answer your question, I don't think it's doable ATM.

**Comment by dadoonet** [comment]
No. You need to have elasticsearch started.
