### ISSUE TITLE
Question: Does the Apache Tika implementation  in fscralwer has all the parsers

### ISSUE THREAD

**Issue by vedydev** [dadoonet/fscrawler#641]
Tika has many parsers as seen here:
https://github.com/apache/tika/tree/master/tika-parsers/src/main/java/org/apache/tika/parser
does fscrawler implementation of Apache Tika has all those parsers?

If not, is there a way for a user to add any missing parsers?

thanks

**Comment by dadoonet** [comment]
Yes. Normally it has everything Tika exposes but some libs must be added manually (read the end of this page: https://fscrawler.readthedocs.io/en/fscrawler-2.5/)
