### ISSUE TITLE
Python spec to submit additional tags

### ISSUE THREAD

**Issue by hjohanns** [dadoonet/fscrawler#651]
**Could not find how to pass tags through Python**
I want to reproduce the example on the additional tags documented in the docs, but with python
My code is
`tagdata = {
		#'path': {"real":'"'+args.infiles+'"', "virtual":'"'+args.infiles+'"'},
		"external": {
			"baseDir": "Doc",
		}
	}`
(I commented the path values to simplify the scenario. args.infiles would contain the full path to the file)
and then I submit via
`		r=requests.post(restUrl, files={'file': f}, data={'tags':tagdata})`
But the error at execution in fscrawler --debug is:
```
02:39:12,084 ERROR [f.p.e.c.f.r.RestApi] Error parsing tags
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'external': was expecting ('true', 'false' or 'null')
 at [Source: (org.jvnet.mimepull.DataHead$ReadMultiStream); line: 1, column: 17]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804) ~[jackson-core-2.9.7.jar:2.9.7]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:679) ~[jackson-core-2
```

**Versions:**
 - OS: Linux
 - Version 2.6

There is a good chance it is my code, but I cannot spot the error. Thanks for any help, hj

**Comment by dadoonet** [comment]
Could you try with curl first to make sure it's not a bug in FSCrawler?

Then I'm not a Python dev so I can't help. Not sure if someone from the community can help? May be ask on stackoverflow?

**Comment by hjohanns** [comment]
David,
thanks for your suggestion. I tried the curl, and it worked, so it is not a FSCrawler bug. I suspected it anyway. Insisting I found this piece of code to work (Python 3):

    import requests
    import json
    import mmap

	tagdata = {
		"path": {"real":filePath, "virtual":filePath},
		"external": {
			"someKey": someValue,
		}
	}
	mm = mmap.mmap(-1, 1024)
	mm.write(json.dumps(tagdata).encode('utf8'))
	mm.seek(0)
	with open(filePath, 'rb') as f:
		multiFiles= [
			('file', (filename, f)),
			('tags', ('tags', mm))]
		r=requests.post(restUrl, files=multiFiles)

I attach it for the sake of comments and other users.
Thanks for your help! hj

**Comment by dadoonet** [comment]
Thanks for sharing the solution !
