### ISSUE TITLE
Cannot search content with Thai language

### ISSUE THREAD

**Issue by nont65** [dadoonet/fscrawler#652]
I tried to Query Some Text in PDF File but It can't found.

```
GET test/_search
```

**Result**

```json
{
  "took" : 11,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 5,
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "test",
        "_type" : "_doc",
        "_id" : "91d5986be795ca245254f1596d0a9b",
        "_score" : 1.0,
        "_source" : {
          "content" : """

 1 

แบบสอบถาม  General  Health  Questionnaire   ฉบับภาษาไทย 
( Thai GHQ 12 – 28 – 30 – 60 ) 

 
แบบสอบถาม General Health Questionnaire  ฉบับภาษาไทย 

(Thai GHQ) 
  ...
```

```
GET test/_search
{
  "query" : {
    "match": {
      "content": "สอบถาม"
    }
  }
}
```

**Result**
```json
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 0,
    "max_score" : null,
    "hits" : [ ]
  }
}
```

**Comment by dadoonet** [comment]
Did you set a Thai analyzer for your `content` field?
I mean that you need to find first what is the right mapping you need (without FSCrawler) and once you have found it, apply it within the context of FSCrawler.

This part of the documentation might be relevant for this last step. See https://fscrawler.readthedocs.io/en/fscrawler-2.5/admin/fs/elasticsearch.html#creating-your-own-mapping-analyzers

**Comment by nont65** [comment]
> Did you set a Thai analyzer for your `content` field?
> I mean that you need to find first what is the right mapping you need (without FSCrawler) and once you have found it, apply it within the context of FSCrawler.
> 
> This part of the documentation might be relevant for this last step. See https://fscrawler.readthedocs.io/en/fscrawler-2.5/admin/fs/elasticsearch.html#creating-your-own-mapping-analyzers

I have already set it.
`{
  "settings": {
    "index.mapping.total_fields.limit": 2000,
    "analysis": {
      "analyzer": {
        "fscrawler_path": {
          "tokenizer": "fscrawler_path"
        }
      },
      "tokenizer": {
        "fscrawler_path": {
          "type": "path_hierarchy"
        }
      }
    }
  },
  "mappings": {
    "_doc": {
      "dynamic_templates": [
        {
          "raw_as_text": {
            "path_match": "meta.raw.*",
            "mapping": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            }
          }
        }
      ],
      "properties": {
        "attachment": {
          "type": "binary",
          "doc_values": false
        },
        "attributes": {
          "properties": {
            "group": {
              "type": "keyword"
            },
            "owner": {
              "type": "keyword"
            }
          }
        },
        "content": {
          "type": "text",
          "analyzer": "Thai"
        },
        "file": {
          "properties": {
            "content_type": {
              "type": "keyword"
            },
            "filename": {
              "type": "keyword",
              "store": true
            },
            "extension": {
              "type": "keyword"
            },
            "filesize": {
              "type": "long"
            },
            "indexed_chars": {
              "type": "long"
            },
            "indexing_date": {
              "type": "date",
              "format": "dateOptionalTime"
            },
            "created": {
              "type": "date",
              "format": "dateOptionalTime"
            },
            "last_modified": {
              "type": "date",
              "format": "dateOptionalTime"
            },
            "last_accessed": {
              "type": "date",
              "format": "dateOptionalTime"
            },
            "checksum": {
              "type": "keyword"
            },
            "url": {
              "type": "keyword",
              "index": false
            }
          }
        },
        "meta": {
          "properties": {
            "author": {
              "type": "text"
            },
            "date": {
              "type": "date",
              "format": "dateOptionalTime"
            },
            "keywords": {
              "type": "text"
            },
            "title": {
              "type": "text"
            },
            "language": {
              "type": "keyword"
            },
            "format": {
              "type": "text"
            },
            "identifier": {
              "type": "text"
            },
            "contributor": {
              "type": "text"
            },
            "coverage": {
              "type": "text"
            },
            "modifier": {
              "type": "text"
            },
            "creator_tool": {
              "type": "keyword"
            },
            "publisher": {
              "type": "text"
            },
            "relation": {
              "type": "text"
            },
            "rights": {
              "type": "text"
            },
            "source": {
              "type": "text"
            },
            "type": {
              "type": "text"
            },
            "description": {
              "type": "text"
            },
            "created": {
              "type": "date",
              "format": "dateOptionalTime"
            },
            "print_date": {
              "type": "date",
              "format": "dateOptionalTime"
            },
            "metadata_date": {
              "type": "date",
              "format": "dateOptionalTime"
            },
            "latitude": {
              "type": "text"
            },
            "longitude": {
              "type": "text"
            },
            "altitude": {
              "type": "text"
            },
            "rating": {
              "type": "byte"
            },
            "comments": {
              "type": "text"
            }
          }
        },
        "path": {
          "properties": {
            "real": {
              "type": "keyword",
              "fields": {
                "tree": {
                  "type": "text",
                  "analyzer": "fscrawler_path",
                  "fielddata": true
                },
                "fulltext": {
                  "type": "text"
                }
              }
            },
            "root": {
              "type": "keyword"
            },
            "virtual": {
              "type": "keyword",
              "fields": {
                "tree": {
                  "type": "text",
                  "analyzer": "fscrawler_path",
                  "fielddata": true
                },
                "fulltext": {
                  "type": "text"
                }
              }
            }
          }
        }
      }
    }
  }
}
`

**Comment by nont65** [comment]
I'm not sure why I run GET test/_mappings in Kibana. It's show like this
```json
...
        "content" : {
            "type" : "text"
         },
...
```

**Comment by dadoonet** [comment]
It's not applied because your index probably already exist when you start FSCrawler.

Delete the index first.

Then I'm surprised that `Thai` is a valid analyzer name. I'd expect something in lowercase like `thai`.

**Comment by nont65** [comment]
> It's not applied because your index probably already exist when you start FSCrawler.
> 
> Delete the index first.
> 
> Then I'm surprised that `Thai` is a valid analyzer name. I'd expect something in lowercase like `thai`.

Ok, It's work. Thank you very much.
