### ISSUE TITLE
Enable CORS policy on FSCrawler REST client

### ISSUE THREAD

**Issue by carlosnumber9** [dadoonet/fscrawler#654]
I'm trying to create an Angular 7 web app where I can add PDF contents directly into a Elasticsearch service. I created the file uploader in the app and I started a FSCrawler REST client to send the file requests. But when I try it, the web browser pops out this in console:

"Access to XMLHttpRequest at 'http://127.0.0.1:8080/fscrawler' from origin 'http://localhost:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource."

I tried previously to make some opps directly on the Elasticsearch client (creating an index e.g) and I enabled the CORS in my Elasticsearch so it worked. But even with that done, this FSCrawler request doesn't work. 
Anyone can help me please? thx

**Comment by dadoonet** [comment]
I have no idea of what needs to be done on FSCrawler side. Probably some code to add.

If you have any idea please tell here. If you do Java programming, PR are welcomed 😉

**Comment by carlosnumber9** [comment]
What I had to do to enable CORS for Elasticsearch is to add these lines into the yml config file:

http.cors.enabled : true
http.cors.allow-origin : "*"
http.cors.allow-credentials : true

Maybe it's possible to add something like that for FSCrawler?

**Comment by dadoonet** [comment]
No. That's what I need to figure out.

**Comment by dadoonet** [comment]
Yeah. See https://www.elastic.co/guide/en/elasticsearch/plugins/master/ingest-attachment.html

**Comment by dadoonet** [comment]
@carlosnumber9 Do you have a project or some source code I can use to reproduce your issue and make sure I can find a fix for it?

**Comment by dadoonet** [comment]
Ping @carlosnumber9. Any help you could provide to move your request forward?
