### ISSUE TITLE
How to run Rest service in the background

### ISSUE THREAD

**Issue by vasttian** [dadoonet/fscrawler#656]
How to run [Rest](https://fscrawler.readthedocs.io/en/fscrawler-2.5/admin/fs/rest.html) service in the background?

is `--silent` ? 

Thx.

**Comment by dadoonet** [comment]
On which platform?

**Comment by vasttian** [comment]
sorry,
it's `CentOS Linux release 7.3.1611 (Core)`

**Comment by vasttian** [comment]
hi @dadoonet ,

Is there any way?

**Comment by dadoonet** [comment]
I believe that if you run FSCrawler with `&` it will run it in the background, isn't it?

**Comment by vasttian** [comment]
Yep,
It works fine.
Thx.
