### ISSUE TITLE
Bring 2.6 version to Maven Central repository

### ISSUE THREAD

**Issue by fbaligand** [dadoonet/fscrawler#667]
Currently, fscrawler 2.6 is not available on Maven Central repository: 
https://repo1.maven.org/maven2/fr/pilato/elasticsearch/crawler/fscrawler/

Could you publish fscrawler 2.6 on Maven Central repository?

Fabien

**Comment by dadoonet** [comment]
Could you check this page? 
https://fscrawler.readthedocs.io/en/fscrawler-2.6/installation.html

I know there's an issue elsewhere in documentation though

**Comment by fbaligand** [comment]
Perfect!
Sorry, I missed that I can choose version on readthedocs documentation!

It answers my need => I close the issue!

**Comment by dadoonet** [comment]
@fbaligand I fixed the links from the SNAPSHOT documentation. Thanks for reporting!

**Comment by fbaligand** [comment]
Okay!
So finally my issue was useful! :)
Thanks for the doc fix!
