### ISSUE TITLE
Indexing shtml content

### ISSUE THREAD

**Issue by cloud1250x4** [dadoonet/fscrawler#672]
I'm trying to index shtml files and it's working great.. except for one thing..

It doesn't index the file content... It indexes it as a base64 attachment...

Step to reproduce:

-Rename a text file as .shtml
-Use fscrawler to index it

config file:
```
{
  "name" : "fscrawler_job",
  "fs" : {
    "url" : "/tmp/es",
    "update_rate" : "15m",
    "json_support" : false,
    "filename_as_id" : false,
    "add_filesize" : true,
    "remove_deleted" : true,
    "add_as_inner_object" : false,
    "store_source" : true,
    "index_content" : true,
    "attributes_support" : false,
    "raw_metadata" : true,
    "xml_support" : false,
    "index_folders" : true,
    "lang_detect" : false,
    "continue_on_error" : false,
    "pdf_ocr" : true,
    "ocr" : {
      "language" : "eng"
    }
  },
  "elasticsearch" : {
    "nodes" : [ {
      "host" : "elasticsearch",
      "port" : 9200,
      "scheme" : "HTTP"
    } ],
    "bulk_size" : 100,
    "flush_interval" : "5s",
    "byte_size" : "10mb"
  },
  "rest" : {
    "scheme" : "HTTP",
    "host" : "127.0.0.1",
    "port" : 8080,
    "endpoint" : "fscrawler"
  }
}
```

**Comment by cloud1250x4** [comment]
```
{
  "name" : "fscrawler_job",
  "fs" : {
    "url" : "/tmp/es",
    "update_rate" : "15m",
    "json_support" : false,
    "filename_as_id" : false,
    "add_filesize" : true,
    "remove_deleted" : true,
    "add_as_inner_object" : false,
    "store_source" : true,
    "index_content" : true,
    "attributes_support" : false,
    "raw_metadata" : true,
    "xml_support" : false,
    "index_folders" : true,
    "lang_detect" : false,
    "continue_on_error" : false,
    "pdf_ocr" : true,
    "ocr" : {
      "language" : "eng"
    }
  },
  "elasticsearch" : {
    "nodes" : [ {
      "host" : "elasticsearch",
      "port" : 9200,
      "scheme" : "HTTP"
    } ],
    "bulk_size" : 100,
    "flush_interval" : "5s",
    "byte_size" : "10mb"
  },
  "rest" : {
    "scheme" : "HTTP",
    "host" : "127.0.0.1",
    "port" : 8080,
    "endpoint" : "fscrawler"
  }
}
```

**Comment by dadoonet** [comment]
Could you give an example of a document which is in elasticsearch ?

**Comment by cloud1250x4** [comment]
Okay, I think I know what's going on here.. 

Some of the files I'm trying to index doesn't have Content-encoding apparently..

![screen shot 2019-01-31 at 1 55 13 pm](https://user-images.githubusercontent.com/2974803/52077849-f8ee5300-255f-11e9-9a59-77477eb9f079.png)
![screen shot 2019-01-31 at 1 54 57 pm](https://user-images.githubusercontent.com/2974803/52077853-fb50ad00-255f-11e9-9a3c-28e27c3d8e0a.png)

Any way I can solve this directly with fscrawler?

**Comment by dadoonet** [comment]
I don't understand. The example your shared (please share the raw response instead of images next time) shows that lot of thing have been extracted. So I don't understand what your "problem" is. Could you describe more?

**Comment by cloud1250x4** [comment]
In the first picture, under source, it's missing the content field.. 
Probably because it's "can't" read the file.

I couldn't reproduce it with my test file.. that's why I didn't send the raw response

**Comment by dadoonet** [comment]
I see. You could just try this file which is failing and launch FSCrawler with `--trace` option.

**Comment by cloud1250x4** [comment]
Here what is says with the trace option : 

```
fscrawler_1      | 20:04:33,492 INFO  [f.p.e.c.f.FsCrawlerImpl] Starting FS crawler
fscrawler_1      | 20:04:33,494 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler started in watch mode. It will run unless you stop it with CTRL+C.
fscrawler_1      | 20:04:34,166 WARN  [o.e.c.RestClient] request [PUT http://elasticsearch:9200/fscrawler_job] returned 1 warnings: [299 Elasticsearch-6.5.1-8c58350 "the default number of shards will change from [5] to [1] in 7.0.0; if you wish to continue using the default of [5] shards, you must manage this on the create index request or with an index template" "Thu, 31 Jan 2019 20:04:33 GMT"]
fscrawler_1      | 20:04:34,211 INFO  [f.p.e.c.f.FsParserAbstract] FS crawler started for [fscrawler_job] for [/tmp/es] every [15m]
fscrawler_1      | 20:04:34,568 WARN  [o.a.t.p.PDFParser] J2KImageReader not loaded. JPEG2000 files will not be processed.
fscrawler_1      | See https://pdfbox.apache.org/2.0/dependencies.html#jai-image-io
fscrawler_1      | for optional dependencies.
fscrawler_1      | 
```


I've started from scratch with only one document.

`{"_index":"fscrawler_job","_type":"_doc","_id":"26dd35f4bc771a5ec7145d6c084b3bf","_score":1.0,"_source":{"attachment”:”removed”,”meta":{"raw":{"X-Parsed-By":"org.apache.tika.parser.DefaultParser","resourceName":"index.shtml","Content-Type":"application/xml"}},"file":{"extension":"shtml","content_type":"application/xml","created":"2019-01-31T20:09:32.000+0000","last_modified":"2019-01-31T20:09:32.000+0000","last_accessed":"2019-01-31T20:09:33.000+0000","indexing_date":"2019-01-31T20:10:13.717+0000","filesize":16502,"filename":"index.shtml","url":"file:///tmp/es/index.shtml"},"path":{"root":"824b64ab42d4b63cda6e747e2b80e5","virtual":"/index.shtml","real":"/tmp/es/index.shtml"}}}
`

**Comment by dadoonet** [comment]
Hmmm. There is no trace here. Could you start again with `--debug`?

**Comment by cloud1250x4** [comment]
Here we go sorry first time I did it wrong...

https://gist.github.com/cloud1250x4/e6e6992daf04a27c476a9c000334ae5b

**Comment by cloud1250x4** [comment]
I'll try and see if I can reproduce this with a file that I can actually share..

**Comment by dadoonet** [comment]
I'm closing the issue as I don't feel it's a FSCrawler issue. If your document is well formed, then you can [open an issue in Tika project](https://issues.apache.org/jira/browse/TIKA).
That being said I think that when Tika is failing that way we should have an option not to index the document and also log warn about this file.

**Comment by cloud1250x4** [comment]
Hm okay.. when I open the document and resave it.. everything is fine.. Probably some encoding problem..

Sadly.. I have over 10000 files like this.. I really wonder what that other person did..

**Comment by dadoonet** [comment]
Could you share one of those files ?
