### ISSUE TITLE
Tika meta.raw attributes

### ISSUE THREAD

**Issue by slowfranklin** [dadoonet/fscrawler#688]
Hi folks,

I'm trying to get a list of all possible meta.raw.* attributes that may end up in the index. Can anyone provide some pointers?

I'm aware of stuff like [Metadata](https://tika.apache.org/1.20/api/org/apache/tika/metadata/Metadata.html) and [TikaCoreProperties](https://tika.apache.org/1.20/api/org/apache/tika/metadata/TikaCoreProperties.html), but that's missing a lot.

I'm dreaming of something as comprehensive as the [Nepomuk Ontology](https://developer.gnome.org/ontology/unstable/). :-)

Anyone? Thanks!
-slow

**Comment by dadoonet** [comment]
Unless you disabled raw meta data you should get everything. See https://fscrawler.readthedocs.io/en/latest/admin/fs/local-fs.html

**Comment by dadoonet** [comment]
I misread. So I don't know that list.

**Comment by dadoonet** [comment]
The only list I'm maintaining is https://fscrawler.readthedocs.io/en/latest/admin/fs/elasticsearch.html#generated-fields

**Comment by slowfranklin** [comment]
@dadoonet, yes I was aware of [https://fscrawler.readthedocs.io/en/latest/admin/fs/elasticsearch.html#generated-fields](https://fscrawler.readthedocs.io/en/latest/admin/fs/elasticsearch.html#generated-fields) and it's a good starting point, thanks!
I'm also not disabling raw.metadata, quite the contrary. :-) I'm implement a mapping from Apple's Spotlight Metadata attributes to the fscrawler generated ones, including stuff that may be part of meta.raw. The mapping will be used in Samba's implementation of a Spotlight search server to map from Apple's Spotlight query language to REST, targetting the metadata extracted from filesystems with fscrawler.

**Comment by dadoonet** [comment]
> I'm implement a mapping from Apple's Spotlight Metadata attributes to the fscrawler generated ones, including stuff that may be part of meta.raw.

I'm curious on how you are doing that. Anything you can share around this?

**Comment by slowfranklin** [comment]
Apple's documentation on their Spotlight metadata attributes can be found [here](https://developer.apple.com/library/archive/documentation/CoreServices/Reference/MetadataAttributesRef/Reference/CommonAttrs.html#//apple_ref/doc/uid/TP40001694-SW1).

Samba only supports a small subset of this in a mapping to the Nepomuk Ontology. Source can be found here: [Samba Spotlight RPC server mappings](https://git.samba.org/?p=samba.git;a=blob;f=source3/rpc_server/mdssvc/sparql_mapping.c;h=c71c7a55131101a84190ce51d8ad949c8cf49d05;hb=refs/heads/master).

**Comment by dadoonet** [comment]
Ok thanks.
Is there anything I can do? I'm afraid I can't but don't want to close the issue without asking :)

I believe that most of the answer should be implemented in Tika project...

**Comment by slowfranklin** [comment]
Guess so, bet let me ask one question before closing the ticket. This might help me move along in the right direction. :)
Where exactly is meta.raw coming from? And: is it stored unmodified?

**Comment by dadoonet** [comment]
`meta.raw` is the meta data extracted from Tika without any modification. As it comes back from any file.

But then, Tika is doing some reconciliation and say for example that `dc:title`, `title`, `foo:Title` have the same meaning. Tika then puts that data inside the [Title metadata field](https://tika.apache.org/1.20/api/org/apache/tika/metadata/TikaCoreProperties.html#TITLE) which I put in `meta.title` json field.

Makes sense?

**Comment by slowfranklin** [comment]
Yes, thanks. I just wonder why there doesn't seem to be any concise Tika documentation. Looks like  the [Tikia sources](https://github.com/apache/tika/tree/master/tika-core/src/main/java/org/apache/tika/metadata) are the only available reference.

Oh, and *big* thanks for fscrawler!
