### ISSUE TITLE
OCR without pdf_ocr

### ISSUE THREAD

**Issue by Newmski** [dadoonet/fscrawler#691]
When pdf_ocr is set to false no OCR occurs for any files including images.  This seems to be by design https://github.com/dadoonet/fscrawler/issues/410.

Would it be possible to enable OCR for images but not for PDFs, e.g. 

```
"pdf_ocr": false,
"ocr": {
  "enabled": true
}
```

The documentation seems to suggest that this is the case but when I set pdf_ocr to false the images stop being processed.

https://fscrawler.readthedocs.io/en/fscrawler-2.6/user/tips.html?highlight=images

**Comment by dadoonet** [comment]
Thanks for reporting!

Definitely a bug. I'll come with a PR with your suggestion and another one to move the `pdf_ocr` setting under the `ocr` object.
