### ISSUE TITLE
Set file.content_type to text/directory for directories as per RFC 2425

### ISSUE THREAD

**Issue by slowfranklin** [dadoonet/fscrawler#712]
Hi!

Would it be possible to assign MIME type text/directory for directories when directory indexing is enabled?

For my use case I have to use the same index for files and directories, which means I have no way to restrict searches to directories after the fact.

Suppose a user wants to search for "all directories whose name starts with foo". This is currently not really possible.

Fwiw, my use case is using fscrawler/Elasticsearch as backend for macOS Spotlight in Samba.

Thanks!

**Comment by dadoonet** [comment]
That's doable I think. That said when I'll remove the folder index in the future I need to think about it and index directories as files with no content and the proper content-type.

**Comment by dadoonet** [comment]
> For my use case I have to use the same index for files and directories, which means I have no way to restrict searches to directories after the fact.
> 
> Suppose a user wants to search for "all directories whose name starts with foo". This is currently not really possible.
> 
> Fwiw, my use case is using fscrawler/Elasticsearch as backend for macOS Spotlight in Samba.

I think I just added support for this with #1209 and #1210. 

> Would it be possible to assign MIME type text/directory for directories when directory indexing is enabled?

I need to add this now :)

**Comment by slowfranklin** [comment]
A bit late, but anyway: thanks a lot for implementing this! :)

**Comment by dadoonet** [comment]
Better later than never 😉

**Comment by slowfranklin** [comment]
Fwiw, searching directories by name and filtering by type now works out-of-the box:
`mdsearch -U slow%x localhost spotlight' kMDItemFSName=="dir*"&&kMDItemContentType=="9"'`
(mdsearch is a Samba CLI tool that can be used to run macOS Spotlight queries against any SMB server)
