### ISSUE TITLE
Impmplementation of Autocomplete and NLP Feature in FScrawler

### ISSUE THREAD

**Issue by Neel-Gagan** [dadoonet/fscrawler#721]
Elasticsearch Version : 6.4.3
Kibana Version 6.4.3
Fscrawler Version 2.4.

how can i implement Autocomplete and NLP feature in Fscrawler Mapping files, i am crawling on unstructured data dump containing  docx.pdf. jpge, xlsx etc files.

**Comment by dadoonet** [comment]
As this is not specifically a question regarding FSCrawler but elasticsearch itself, could you please ask it in discuss.elastic.co ?

Thanks
