### ISSUE TITLE
status.json file not getting updated

### ISSUE THREAD

**Issue by Neel-Gagan** [dadoonet/fscrawler#722]
Elasticsearch 6.4.3
Fscrawler 2.4

status.json file is not getting updated even though indexing is being done through fscrawler 2.5.

{
"name" : "autocomp",
"lastrun" : "2019-05-08T11:56.42.517",
"indexed" : 8,
"deleted" ; 0
}
i have tested by adding a new file, the new file is crawled but the lastrun in status file is not getting updated. any suggestion on how to rectify this issue.

**Comment by dadoonet** [comment]
Could you try with 2.6 or 27-SNAPSHOT?

**Comment by dadoonet** [comment]
No news on this. I think it's ok when the job is complete.
If the job fails, then this file is not written.
