### ISSUE TITLE
Add Elastic Workplace Search connector

### ISSUE THREAD

**Issue by dadoonet** [dadoonet/fscrawler#723]
Let's connect to as well to https://swiftype.com/documentation/enterprise-search/api/custom-sources

**Comment by AncKal94** [comment]
Can we use workplace search along with fscrawler?
Our basic task is Document ranking based on query.

**Comment by dadoonet** [comment]
@AncKal94 Not yet. This is issue is still opened.

**Comment by seanstory** [comment]
I'd had a similar idea! I've built a few things that might be of use:

- [Workplace Search: Java](https://github.com/seanstory/workplace-search-java), a JVM client and SDK for workplace search. 
- [Custom API Source Archetype](https://github.com/seanstory/custom-source-archetype), building off the above, a Maven Archetype designed towards bootstrapping JVM-based Custom Sources for Workplace Search
- [Filesystem Custom API Source](https://github.com/seanstory/filesystem-workplace-search-source), building off _both_ the above, a naive implementation of a filesystem crawler. I would LOVE to see your much more robust crawler supplant it, and would happily help out if you'd like :)

**Comment by dadoonet** [comment]
Amazing @seanstory. I was expecting a JAVA client for workplace search server. That was the main missing piece to make this feature happen in FSCrawler. 
I can hopefully start working on this soon 😊

Any idea if your code will become "official" at some point or moved to elastic repo?

**Comment by seanstory** [comment]
> I was expecting a JAVA client for workplace search server.

Me too! 😆 That wasn't how I'd planned to spend the first half of my spacetime. And be forewarned - it's got a lot of TODOs lingering - I pretty much only built the features I needed, plus low-hanging fruit.

> Any idea if your code will become "official" at some point or moved to elastic repo?

I don't know. I've got a brief call scheduled with my manager (@goodroot) next week to talk about "next steps" for my spacetime work. Long-term, I expect we'll add more official language clients for Enterprise Search, but @jonasll would be the one to ask there.

**Comment by dadoonet** [comment]
Note to self, I will probably have to switch to a [Docker Compose maven plugin](https://github.com/dkanejs/docker-compose-maven-plugin) instead of using Fabric8 plugin.
