### ISSUE TITLE
Issue  with Deleted in _status.json file of fscrawler

### ISSUE THREAD

**Issue by Neel-Gagan** [dadoonet/fscrawler#724]
Elasticsearch 6.4.3
Fscrawler 2.4

is deleted in _status.json file actually deletes the indexed content from elasticsearch ? 

{
"name" : "autocomp",
"lastrun" : "2019-05-16T11:56.42.517",
"indexed" : 8,
"deleted" ; 10
}
i am not able to find the content which was indexed in past is it because of this deleted: 10 in fscrawler. kindly suggest.

**Comment by dadoonet** [comment]
If you remove a file from the watches folder, then it's removed from elasticsearch.

**Comment by dadoonet** [comment]
No more feedback. Closing.

Feel free to reopen or add more comments. Thanks.
