### ISSUE TITLE
Add option to ignore symlinks

### ISSUE THREAD

**Issue by budachst** [dadoonet/fscrawler#752]
**Is your feature request related to a problem? Please describe.**

macOS bundle formats, especially for applications, often contain "looping symlinks", which cause fscrawler to try to follow those links, until it hits some kind of error like "too many symlinks". This significantly hinders crawling through a volume, which has quite a number of old-style macOS apps on it.

This looks like this then…

```
22:31:30,171 WARN  [f.p.e.c.f.f.FsCrawlerUtil] Failed to determine 'owner' of /tr1206570Data/it-services/Programmkerne zur Freigabe/iDVD.app/Contents/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/Current/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/Current/Frameworks/DVDBase.framework/Versions/Current/Frameworks/DSPFoundation.framework/Versions/Current: /tr1206570Data/it-services/Programmkerne zur Freigabe/iDVD.app/Contents/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/Current/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/A/Frameworks/DVDBase.framework/Versions/Current/Frameworks/DVDBase.framework/Versions/Current/Frameworks/DSPFoundation.framework/Versions/Current: Zu viele Ebenen aus symbolischen Links
```

**Describe the solution you'd like**

Provide a control which lets fscrawler simply ignore and/or skip symlinks entirely.

**Describe alternatives you've considered**

The only option would be to remove these kind of bundle folders.

**Comment by dadoonet** [comment]
@budachst Thanks for the report and the proposal. I implemented it with #754. Let's wait for CI to be green and I'll merge the change so you can test it soon.

**Comment by budachst** [comment]
@dadoonet Great - this will be a huge help crawling unknown and uncertain terrain!

**Comment by dadoonet** [comment]
@budachst Could you try the latest SNAPSHOT available at https://oss.sonatype.org/content/repositories/snapshots/fr/pilato/elasticsearch/crawler/fscrawler-es7/2.7-SNAPSHOT/ (supposing you are using elasticsearch 7.x).

**Comment by budachst** [comment]
Hi @dadoonet  - actually, I am running the latest 2.6 SNAPSHOT, since I am running against ES 6.8. I will update you asap.

**Comment by dadoonet** [comment]
Do you mean 2.7? And by latest do you mean the one that has been built some minutes/hours ago?

**Comment by budachst** [comment]
Sorry, tried to save some time and got carried away, while typing… ;) I am running this version: fscrawler-es6-2.7-20190528.081956-40.zip, which I just downloaded.

**Comment by budachst** [comment]
In order to check, wheter or not Links are being indexed/accessed, what should I query the index for - I can't seem to find anything to use for my query.

**Comment by dadoonet** [comment]
If you have a file which is a symlink it should not be indexed at all.

**Comment by budachst** [comment]
He he… up to know, I couldn't find any symlinked-item in the index, but all these symlinks inside these macOS app bundles are xml files, so they probably havent't been indexed anyway. However, folder symlink also hasn't made it into the index.

I will perform some more specific tests, though, but this looks already good.

**Comment by budachst** [comment]
Ehh… ok, I have this little test and tried the above version 6-2.7-20190528.081956-40:

```
-rw-rw----+   1 root JVM\it-staff       64  3. Jun 14:00 index_text.txt
lrwxrwxrwx    1 root JVM\it-staff       14  3. Jun 14:00 text_index.txt -> index_text.txt
```

However, both files are returned when searching that particular index:

```
GET it-services/_search
{
  "size" : 100,
  "query": {
      "wildcard":{
        "path.real": "*text_index*"
                }
          }   
}
```

Result:

```
{
  "took" : 3,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "it-services",
        "_type" : "_doc",
        "_id" : "ee164338a71fad8a887d76e5721b7c7c",
        "_score" : 1.0,
        "_source" : {
          "content" : """
Dies ist das Haus vom Nikolaus. Und nebenan vom Weihnachtsmann!


""",
          "meta" : {
            "raw" : {
              "X-Parsed-By" : "org.apache.tika.parser.DefaultParser",
              "Content-Encoding" : "ISO-8859-1",
              "resourceName" : "text_index.txt",
              "Content-Type" : "text/plain; charset=ISO-8859-1"
            }
          },
          "file" : {
            "extension" : "txt",
            "content_type" : "text/plain; charset=ISO-8859-1",
            "created" : "2019-06-03T12:00:19.477+0000",
            "last_modified" : "2019-06-03T12:00:19.477+0000",
            "last_accessed" : "2019-06-03T12:33:53.860+0000",
            "indexing_date" : "2019-06-03T12:58:52.277+0000",
            "filesize" : 64,
            "filename" : "text_index.txt",
            "url" : "file:///tr1206570Data/it-services/text_index.txt"
          },
          "path" : {
            "root" : "304410b24058b2b8c22e439ca177466c",
            "virtual" : "/text_index.txt",
            "real" : "/tr1206570Data/it-services/text_index.txt"
          }
        }
      }
    ]
  }
}
```

So, the symlinked file also made it into the index.

**Comment by dadoonet** [comment]
What is your FSCrawler settings file for this job?

**Comment by budachst** [comment]
I do run this jobfile:

```
---
name: "tr1206570_it-services"
fs:
  url: "/tr1206570Data/it-services"
  update_rate: "500m"
  excludes:
  - "*/~*"
  - "*/.AppleDB"
  - "*/_Snapshots"
  includes:
  - "*.txt"
  json_support: false
  filename_as_id: false
  add_filesize: true
  remove_deleted: true
  add_as_inner_object: false
  store_source: false
  index_content: true
  attributes_support: false
  raw_metadata: true
  xml_support: false
  index_folders: true
  lang_detect: false
  continue_on_error: false
  follow_symlinks: false
ocr:
  enabled: false
  language: "de"
elasticsearch:
  nodes:
  - url: "http://xxx.xxx.xxx.xxx:9200"
  index: "it-services"
  index_folder: "it-services"
  bulk_size : 1000
  flush_interval: "5s"
  byte_size: "10mb"
```

**Comment by dadoonet** [comment]
Hmmm. This looks good. I don't understand why it differs [from the integration tests](https://github.com/dadoonet/fscrawler/blob/master/integration-tests/it-common/src/main/java/fr/pilato/elasticsearch/crawler/fs/test/integration/FsCrawlerTestFollowSymlinksIT.java#L34-L48). I'll give a look later.

**Comment by budachst** [comment]
Sure - just ping me and I will try again.

**Comment by dadoonet** [comment]
@budachst I did not reproduce it:

```sh
$ ll work/
total 8
-rw-r--r--  1 dpilato  staff  4 Jun  4 15:38 test.txt
lrwxr-xr-x  1 dpilato  staff  8 Jun  4 15:38 new_test.txt -> test.txt
```

Running with those settings:

```yaml
---
name: "test"
fs:
  url: "/path/to/work"
  update_rate: "15m"
  excludes:
  - "*/~*"
  ocr:
    enabled: false
  follow_symlinks: false
elasticsearch:
  nodes:
  - url: "http://127.0.0.1:9200"
  bulk_size: 10
  flush_interval: "1s"
```

Running with:

```sh
bin/fscrawler --config_dir ./config test --debug
```

This gave:

```
15:39:03,133 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [2/_settings.json] already exists
15:39:03,136 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [2/_settings_folder.json] already exists
15:39:03,136 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [5/_settings.json] already exists
15:39:03,136 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [5/_settings_folder.json] already exists
15:39:03,136 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [6/_settings.json] already exists
15:39:03,136 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [6/_settings_folder.json] already exists
15:39:03,137 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [7/_settings.json] already exists
15:39:03,137 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [7/_settings_folder.json] already exists
15:39:03,138 DEBUG [f.p.e.c.f.c.FsCrawlerCli] Starting job [test]...
15:39:03,492 DEBUG [f.p.e.c.f.c.ElasticsearchClientUtil] Trying to find a client version 7
15:39:04,351 INFO  [f.p.e.c.f.c.v.ElasticsearchClientV7] Elasticsearch Client for version 7.x connected to a node running version 7.1.0
15:39:04,471 INFO  [f.p.e.c.f.FsCrawlerImpl] Starting FS crawler
15:39:04,471 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler started in watch mode. It will run unless you stop it with CTRL+C.
15:39:04,488 DEBUG [f.p.e.c.f.c.v.ElasticsearchClientV7] FS crawler connected to an elasticsearch [7.1.0] node.
15:39:04,493 DEBUG [f.p.e.c.f.c.v.ElasticsearchClientV7] create index [test]
15:39:05,171 DEBUG [f.p.e.c.f.c.v.ElasticsearchClientV7] wait for yellow health on index [test]
15:39:05,199 DEBUG [f.p.e.c.f.c.v.ElasticsearchClientV7] create index [test_folder]
15:39:05,411 DEBUG [f.p.e.c.f.c.v.ElasticsearchClientV7] wait for yellow health on index [test_folder]
15:39:05,423 DEBUG [f.p.e.c.f.FsParserAbstract] creating fs crawler thread [test] for [/Users/dpilato/Documents/Elasticsearch/dev/fscrawler/distribution/es7/target/fscrawler-es7-2.7-SNAPSHOT/work] every [15m]
15:39:05,424 INFO  [f.p.e.c.f.FsParserAbstract] FS crawler started for [test] for [/Users/dpilato/Documents/Elasticsearch/dev/fscrawler/distribution/es7/target/fscrawler-es7-2.7-SNAPSHOT/work] every [15m]
15:39:05,424 DEBUG [f.p.e.c.f.FsParserAbstract] Fs crawler thread [test] is now running. Run #1...
15:39:05,435 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] computeVirtualPathName(/Users/dpilato/Documents/Elasticsearch/dev/fscrawler/distribution/es7/target/fscrawler-es7-2.7-SNAPSHOT/work, /Users/dpilato/Documents/Elasticsearch/dev/fscrawler/distribution/es7/target/fscrawler-es7-2.7-SNAPSHOT/work) = /
15:39:05,442 DEBUG [f.p.e.c.f.FsParserAbstract] Indexing test_folder/3a64d62c648cdce6967a975e9f52ad5c?pipeline=null
15:39:05,450 DEBUG [f.p.e.c.f.FsParserAbstract] indexing [/Users/dpilato/Documents/Elasticsearch/dev/fscrawler/distribution/es7/target/fscrawler-es7-2.7-SNAPSHOT/work] content
15:39:05,450 DEBUG [f.p.e.c.f.c.f.FileAbstractorFile] Listing local files from /Users/dpilato/Documents/Elasticsearch/dev/fscrawler/distribution/es7/target/fscrawler-es7-2.7-SNAPSHOT/work
15:39:05,471 DEBUG [f.p.e.c.f.c.f.FileAbstractorFile] 1 local files found
15:39:05,473 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] computeVirtualPathName(/Users/dpilato/Documents/Elasticsearch/dev/fscrawler/distribution/es7/target/fscrawler-es7-2.7-SNAPSHOT/work, /Users/dpilato/Documents/Elasticsearch/dev/fscrawler/distribution/es7/target/fscrawler-es7-2.7-SNAPSHOT/work/test.txt) = /test.txt
15:39:05,474 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] directory = [false], filename = [/test.txt], includes = [null], excludes = [[*/~*]]
15:39:05,475 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] filename = [/test.txt], excludes = [[*/~*]]
15:39:05,475 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] filename = [/test.txt], includes = [null]
15:39:05,475 DEBUG [f.p.e.c.f.FsParserAbstract] [/test.txt] can be indexed: [true]
15:39:05,475 DEBUG [f.p.e.c.f.FsParserAbstract]   - file: /test.txt
15:39:05,476 DEBUG [f.p.e.c.f.FsParserAbstract] fetching content from [/Users/dpilato/Documents/Elasticsearch/dev/fscrawler/distribution/es7/target/fscrawler-es7-2.7-SNAPSHOT/work],[test.txt]
15:39:05,479 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] computeVirtualPathName(/Users/dpilato/Documents/Elasticsearch/dev/fscrawler/distribution/es7/target/fscrawler-es7-2.7-SNAPSHOT/work, /Users/dpilato/Documents/Elasticsearch/dev/fscrawler/distribution/es7/target/fscrawler-es7-2.7-SNAPSHOT/work/test.txt) = /test.txt
15:39:05,536 DEBUG [f.p.e.c.f.t.TikaInstance] OCR is disabled. Even though it's detected, it must be disabled explicitly
15:39:06,363 WARN  [o.a.t.p.PDFParser] J2KImageReader not loaded. JPEG2000 files will not be processed.
See https://pdfbox.apache.org/2.0/dependencies.html#jai-image-io
for optional dependencies.

15:39:06,823 DEBUG [f.p.e.c.f.FsParserAbstract] Indexing test/9c223b9c52acd6d2b996b78ad8bc6627?pipeline=null
15:39:06,824 DEBUG [f.p.e.c.f.FsParserAbstract] Looking for removed files in [/Users/dpilato/Documents/Elasticsearch/dev/fscrawler/distribution/es7/target/fscrawler-es7-2.7-SNAPSHOT/work]...
15:39:06,888 DEBUG [f.p.e.c.f.FsParserAbstract] Looking for removed directories in [/Users/dpilato/Documents/Elasticsearch/dev/fscrawler/distribution/es7/target/fscrawler-es7-2.7-SNAPSHOT/work]...
15:39:06,912 DEBUG [f.p.e.c.f.FsParserAbstract] Fs crawler is going to sleep for 15m
```

When I'm looking at created data:

```sh
curl localhost:9200/_cat/indices/test?v
```

I'm getting:

```
health status index uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   test  c9NXfZIPTai20XvQnfdy4w   1   1          1            0      9.9kb          9.9kb
```

Everything looks good to me.
I wonder if the version you have is the same as mine.

**Comment by budachst** [comment]
Whoa… probably my bad… I simply didn't get that the newer versions are way down below on the SNAPSHOT site. Let me download really the latest build and try again.

Best,
Stephan

----- Ursprüngliche Mail -----
Von: "David Pilato" <notifications@github.com>
An: "dadoonet/fscrawler" <fscrawler@noreply.github.com>
CC: "budachst" <stephan.budach@jvm.de>, "Mention" <mention@noreply.github.com>
Gesendet: Dienstag, 4. Juni 2019 15:45:24
Betreff: Re: [dadoonet/fscrawler] Add option to ignore symlinks (#752)



@budachst I did not reproduce it: 
$ ll work/
total 8
-rw-r--r--  1 dpilato  staff  4 Jun  4 15:38 test.txt
lrwxr-xr-x  1 dpilato  staff  8 Jun  4 15:38 new_test.txt - > test.txt 

Running with those settings: 
--- name : " test " fs : url : " /path/to/work " update_rate : " 15m " excludes :
  - " */~* " ocr : enabled : false follow_symlinks : false elasticsearch : nodes :
  - url : " http://127.0.0.1:9200 " bulk_size : 10 flush_interval : " 1s " 

Running with: 
bin/fscrawler --config_dir ./config test --debug 

This gave: 15:39:03,133 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [2/_settings.json] already exists
15:39:03,136 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [2/_settings_folder.json] already exists
15:39:03,136 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [5/_settings.json] already exists
15:39:03,136 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [5/_settings_folder.json] already exists
15:39:03,136 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [6/_settings.json] already exists
15:39:03,136 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [6/_settings_folder.json] already exists
15:39:03,137 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [7/_settings.json] already exists
15:39:03,137 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [7/_settings_folder.json] already exists
15:39:03,138 DEBUG [f.p.e.c.f.c.FsCrawlerCli] Starting job [test]...
15:39:03,492 DEBUG [f.p.e.c.f.c.ElasticsearchClientUtil] Trying to find a client version 7
15:39:04,351 INFO  [f.p.e.c.f.c.v.ElasticsearchClientV7] Elasticsearch Client for version 7.x connected to a node running version 7.1.0
15:39:04,471 INFO  [f.p.e.c.f.FsCrawlerImpl] Starting FS crawler
15:39:04,471 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler started in watch mode. It will run unless you stop it with CTRL+C.
15:39:04,488 DEBUG [f.p.e.c.f.c.v.ElasticsearchClientV7] FS crawler connected to an elasticsearch [7.1.0] node.
15:39:04,493 DEBUG [f.p.e.c.f.c.v.ElasticsearchClientV7] create index [test]
15:39:05,171 DEBUG [f.p.e.c.f.c.v.ElasticsearchClientV7] wait for yellow health on index [test]
15:39:05,199 DEBUG [f.p.e.c.f.c.v.ElasticsearchClientV7] create index [test_folder]
15:39:05,411 DEBUG [f.p.e.c.f.c.v.ElasticsearchClientV7] wait for yellow health on index [test_folder]
15:39:05,423 DEBUG [f.p.e.c.f.FsParserAbstract] creating fs crawler thread [test] for [/Users/dpilato/Documents/Elasticsearch/dev/fscrawler/distribution/es7/target/fscrawler-es7-2.7-SNAPSHOT/work] every [15m]
15:39:05,424 INFO  [f.p.e.c.f.FsParserAbstract] FS crawler started for [test] for [/Users/dpilato/Documents/Elasticsearch/dev/fscrawler/distribution/es7/target/fscrawler-es7-2.7-SNAPSHOT/work] every [15m]
15:39:05,424 DEBUG [f.p.e.c.f.FsParserAbstract] Fs crawler thread [test] is now running. Run #1...
15:39:05,435 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] computeVirtualPathName(/Users/dpilato/Documents/Elasticsearch/dev/fscrawler/distribution/es7/target/fscrawler-es7-2.7-SNAPSHOT/work, /Users/dpilato/Documents/Elasticsearch/dev/fscrawler/distribution/es7/target/fscrawler-es7-2.7-SNAPSHOT/work) = /
15:39:05,442 DEBUG [f.p.e.c.f.FsParserAbstract] Indexing test_folder/3a64d62c648cdce6967a975e9f52ad5c?pipeline=null
15:39:05,450 DEBUG [f.p.e.c.f.FsParserAbstract] indexing [/Users/dpilato/Documents/Elasticsearch/dev/fscrawler/distribution/es7/target/fscrawler-es7-2.7-SNAPSHOT/work] content
15:39:05,450 DEBUG [f.p.e.c.f.c.f.FileAbstractorFile] Listing local files from /Users/dpilato/Documents/Elasticsearch/dev/fscrawler/distribution/es7/target/fscrawler-es7-2.7-SNAPSHOT/work
15:39:05,471 DEBUG [f.p.e.c.f.c.f.FileAbstractorFile] 1 local files found
15:39:05,473 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] computeVirtualPathName(/Users/dpilato/Documents/Elasticsearch/dev/fscrawler/distribution/es7/target/fscrawler-es7-2.7-SNAPSHOT/work, /Users/dpilato/Documents/Elasticsearch/dev/fscrawler/distribution/es7/target/fscrawler-es7-2.7-SNAPSHOT/work/test.txt) = /test.txt
15:39:05,474 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] directory = [false], filename = [/test.txt], includes = [null], excludes = [[*/~*]]
15:39:05,475 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] filename = [/test.txt], excludes = [[*/~*]]
15:39:05,475 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] filename = [/test.txt], includes = [null]
15:39:05,475 DEBUG [f.p.e.c.f.FsParserAbstract] [/test.txt] can be indexed: [true]
15:39:05,475 DEBUG [f.p.e.c.f.FsParserAbstract]   - file: /test.txt
15:39:05,476 DEBUG [f.p.e.c.f.FsParserAbstract] fetching content from [/Users/dpilato/Documents/Elasticsearch/dev/fscrawler/distribution/es7/target/fscrawler-es7-2.7-SNAPSHOT/work],[test.txt]
15:39:05,479 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] computeVirtualPathName(/Users/dpilato/Documents/Elasticsearch/dev/fscrawler/distribution/es7/target/fscrawler-es7-2.7-SNAPSHOT/work, /Users/dpilato/Documents/Elasticsearch/dev/fscrawler/distribution/es7/target/fscrawler-es7-2.7-SNAPSHOT/work/test.txt) = /test.txt
15:39:05,536 DEBUG [f.p.e.c.f.t.TikaInstance] OCR is disabled. Even though it's detected, it must be disabled explicitly
15:39:06,363 WARN  [o.a.t.p.PDFParser] J2KImageReader not loaded. JPEG2000 files will not be processed.
See https://pdfbox.apache.org/2.0/dependencies.html#jai-image-io
for optional dependencies.

15:39:06,823 DEBUG [f.p.e.c.f.FsParserAbstract] Indexing test/9c223b9c52acd6d2b996b78ad8bc6627?pipeline=null
15:39:06,824 DEBUG [f.p.e.c.f.FsParserAbstract] Looking for removed files in [/Users/dpilato/Documents/Elasticsearch/dev/fscrawler/distribution/es7/target/fscrawler-es7-2.7-SNAPSHOT/work]...
15:39:06,888 DEBUG [f.p.e.c.f.FsParserAbstract] Looking for removed directories in [/Users/dpilato/Documents/Elasticsearch/dev/fscrawler/distribution/es7/target/fscrawler-es7-2.7-SNAPSHOT/work]...
15:39:06,912 DEBUG [f.p.e.c.f.FsParserAbstract] Fs crawler is going to sleep for 15m 

When I'm looking at created data: 
curl localhost:9200/_cat/indices/test ? v 

I'm getting: health status index uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   test  c9NXfZIPTai20XvQnfdy4w   1   1          1            0      9.9kb          9.9kb 

Everything looks good to me. 
I wonder if the version you have is the same as mine. 

— 
You are receiving this because you were mentioned. 
Reply to this email directly, view it on GitHub , or mute the thread . Web Bug from https://github.com/notifications/beacon/ACNWRNDCHE2XOXZGFRDXVJDPYZWXJA5CNFSM4HR53RTKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODW4TSDY.gif[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/dadoonet/fscrawler/issues/752?email_source=notifications\u0026email_token=ACNWRNBEP5QHWDQ6INTLDCDPYZWXJA5CNFSM4HR53RTKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODW4TSDY#issuecomment-498678031", "url": "https://github.com/dadoonet/fscrawler/issues/752?email_source=notifications\u0026email_token=ACNWRNBEP5QHWDQ6INTLDCDPYZWXJA5CNFSM4HR53RTKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODW4TSDY#issuecomment-498678031", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ] 

-- 

Krebs's 3 Basic Rules for Online Safety 
1st - "If you didn't go looking for it, don't install it!" 
2nd - "If you installed it, update it." 
3rd - "If you no longer need it, remove it." 
http://krebsonsecurity.com/2011/05/krebss-3-basic-rules-for-online-safety 


Stephan Budach 
Head of IT 
Jung von Matt AG 
Glashüttenstraße 79 
D-20357 Hamburg 


Tel: +49 40-4321-1353 
Fax: +49 40-4321-1114 
E-Mail: stephan.budach@jvm.de 
Internet: http://www.jvm.com 
WebEx: https://jvm.webex.com/meet/stephan.budach 

Vorstand: Dr. Peter Figge 
Vorsitzender des Aufsichtsrates: Dr. Jochen Gutbrod 
AG HH HRB 72893 



Jung von Matt investiert in die Kreativen von morgen: JvM-Academy. 
http://jvm-academy.org
