### ISSUE TITLE
Does FScrawler is not able to index more than 100000 characters?

### ISSUE THREAD

**Issue by Neel-Gagan** [dadoonet/fscrawler#761]
Fscrawler version: 2.5
ES v: 6.4.2
I am not able to scan more than one Lakh characters in a text file. when i tried with one lakh characters it does indexing and if i increase it by one character to one Lakh plus one. the message crawler gives is : request entity is too large.

In settings file i included: 
_settings.json
"indexed_chars" : "-1"

**Comment by dadoonet** [comment]
Isn't the same problem you described in https://github.com/dadoonet/fscrawler/issues/755?

**Comment by Neel-Gagan** [comment]
yes its same , but here i raised this issue specific to limit of one lakh character but in #755 the error includes both request entity too large and ElasticsearchException [type=illegal_argument_exception,reason rejecting mapping to [bulk_data_search] as the final mapping would have more than 1 type.

**Comment by dadoonet** [comment]
> request entity is too large.

The reason is that elasticsearch by default does not allow more than 100mb http requests.
You need to change `http.max_content_length` setting if you want to send very big chunks of data. See https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-http.html
