### ISSUE TITLE
Issue with JPEG and FScrawler

### ISSUE THREAD

**Issue by Neel-Gagan** [dadoonet/fscrawler#763]
Fscrawler2.6 is not able to read the content of  JPEG files which shows meta.raw.compresstion type : Baseline where the JPEG Files which show meta.raw.compresstion type : Progressive Huffman. the content is read completely. 
Is there any way to read the content of JPEG files scanned with Baseline compression technique as most of my files are having compression type baseline.

**Comment by dadoonet** [comment]
Could you share a document?

**Comment by Jasmeet2011** [comment]
Tried in Es 7.1.1. It works, no error!
However, difficult to migrate to new version of ES and FS. Can anything be done with the existing version

**Comment by dadoonet** [comment]
No more feedback so I'm closing. Feel free to reopen and share more details like a document. Thanks.
