### ISSUE TITLE
Not recognising new folder mentioned in _settings.yaml file

### ISSUE THREAD

**Issue by arshanvit** [dadoonet/fscrawler#766]
I am running **fscrawler-es7-2.7-20190603.102041-33** and created a job in it as follows:

`fscrawler job_name`

in `_settings.yaml` file,when i am changing value of `fs.url` to custom path in windows and running again same command.
It is giving as :
```

13:09:07,253 WARN  [f.p.e.c.f.c.FsCrawlerCli] job [job_name] does not exist
13:09:07,257 INFO  [f.p.e.c.f.c.FsCrawlerCli] Do you want to create it (Y/N)?
```

is something i am missing

**Comment by dadoonet** [comment]
What does your `_settings.yaml` is looking like?
What is the content of `~/.fscrawler/` directory? `~` on windows is the User home dir.

**Comment by dadoonet** [comment]
No more details. Closing. Feel free to reopen and add more information. Thanks!
