### ISSUE TITLE
Support for skipping already indexed files

### ISSUE THREAD

**Issue by yassinelazaar** [dadoonet/fscrawler#778]
Perhaps Im missing something in the configuration but is there an option to skip crawling files if they are already indexed?

**Comment by dadoonet** [comment]
If the date of the file does not change, then on the next run, the file won't be indexed again.

**Comment by yassinelazaar** [comment]
Hey @dadoonet,
Immensely thankful for your work and kudos for reaching out.

Im having some consistency issues Im trying to solve:
Im running FScrawler from withing a container using cli on a set of unchanged files for the sake of testing. After the each crawl/index is finished, the container is shutdown. The first run (non existing index) takes about 6 minutes. The second run takes lot longer and everything gets re-crawled. Im trying to investigate why. The file date is checked upon the index?

**Comment by dadoonet** [comment]
I believe that's because the status file we are using to store the date of the last run is wiped out when you stop the container may be.
But may be you could share your Dockerfile?

**Comment by yassinelazaar** [comment]
I'm explicitly deleting the jobs and creating new ones with each run (along with the status.json).
Perhaps this is the issue. Will test it in a bit.
but the status does not conserve dates on each file but just the last time the job was run:
`{
  "name" : "job_0",
  "lastrun" : "2019-07-07T01:46:22.716",
  "indexed" : 89,
  "deleted" : 0
}`

**Comment by dadoonet** [comment]
That's true. This is how it works today.

**Comment by yassinelazaar** [comment]
Ok i got it working again by keeping the all crawler related files.
When i remove all the files on one sub-directory that I intend to crawl and then run fscrawler, the files do get deleted from the index and the status show the right number of deleted files.
But when I undo the deletion of those file and re-run the crawler again nothing gets re-indexed. Do you have an Idea why?
Here is the status:
`{
  "name" : "job_654e1d7be84f2e2cc53c090a4044ca1a",
  "lastrun" : "2019-07-07T23:46:21.784",
  "indexed" : 0,
  "deleted" : 0
}`

**Comment by dadoonet** [comment]
When you undo, the files are back with the same dates as before. If instead you copy and paste from another directory then all files will have a newer modification date and should be indexed again.

**Comment by yassinelazaar** [comment]
I see. Thanks for the quick response.

**Comment by yassinelazaar** [comment]
Sorry, I unintentionally closed the ticket. 
Anyway to counter that behaviour?

**Comment by dadoonet** [comment]
Yeah. With https://github.com/dadoonet/fscrawler/issues/399
