### ISSUE TITLE
Fatal error received while running the crawler

### ISSUE THREAD

**Issue by tianyale** [dadoonet/fscrawler#780]
A Problem has been encountered  when fscrawler start and connect Elasticsearch.
I dont't know what data  fscrawler write to Elasticsearch.

Can you give some advice ? thanks you !

ClassCastException[java.util.ArrayList cannot be cast to java.util.Map]

**Versions:**
win10 

![image](https://user-images.githubusercontent.com/15666939/60790847-02c25500-a195-11e9-96b6-87032bc24cfa.png)

relevant: 
https://github.com/ongr-io/ElasticsearchBundle/issues/467

**Comment by dadoonet** [comment]
Please don't post images of code as it's harder to read or to search. Instead paste logs and format them with the `<>` icon.

Please also share the whole details like your FSCrawler version, your elasticsearch version, your FSCrawler job settings file and may be elasticsearch logs.

**Comment by tianyale** [comment]
thanks you ~ 
I have solved the problem by modifying the elasticsearch version.

now  version:
elasticsearch-6.8.1 (before elasticsearch-6.4.3)
fscrawler-es6-2.7

**Comment by CircuitGuy** [comment]
Sorry to re-open a closed issue, but a list of known working versions might help.

Ran into this same issue and still haven't found a fix.

I'm running jdk-15.0.2, ElasticSearch 6.8.13 and fscrawler es6-2.6.

If I could kindly ask @dadoonet, what version of Java and Elasticsearch were you running for your latest stable release (es6-2.6)?

**Comment by dadoonet** [comment]
Hey! The stable version is actually the latest snapshot. I'm hoping to release it soon but no ETA. Lot of works on going.

could you please use the 2.7 instead?

**Comment by CircuitGuy** [comment]
@dadoonet  Yeah... I tried that first. Since I've never seen this running, I don't know how to start. Happy to start another issue if you want, but with latest I get this:
`ERROR StatusLogger Reconfiguration failed: No configuration found for '73d16e93' at 'null' in 'null'`

jdk-15.0.2
Elasticsearch-6.8.10
Latest fscrawler-es7-2.7-SNAPSHOT  (fscrawler-es7-2.7-20210121.084108-154)

**Comment by dadoonet** [comment]
For 6.x you need to use fscrawler-es6-2.7-SNAPSHOT instead.

**Comment by CircuitGuy** [comment]
Doh. Forgot to update my .bat. Still the same error though... against elasticsearch-7.10.2

My testing .bat:
`set JAVA_HOME="%cd%\jdk-15.0.2"
set FS_JAVA_OPTS=-Xmx2g -Xms2g

start "Elastic Search" cmd /k .\elasticsearch-7.10.2\bin\elasticsearch.bat
start "Kibana" cmd /k .\kibana-7.10.2-windows-x86_64\bin\kibana.bat
timeout /t 60
start "FS Crawler" cmd /k .\fscrawler-es7-2.7-SNAPSHOT\bin\fscrawler.bat nas
pause`

and get (from fscrawler)
`ERROR StatusLogger Reconfiguration failed: No configuration found for '73d16e93' at 'null' in 'null'`
