### ISSUE TITLE
All folders are not getting indexed

### ISSUE THREAD

**Issue by mchari** [dadoonet/fscrawler#804]
<!name: "indexpresto"
fs:
  url: "/Users/madabhuc/Documents/IR/presto/sites/PRESTO/PRESTODocuments"
  update_rate: "15m"
  includes:
  - "*/*.pdf"
  excludes:
  - "*/~*"
  - ".DS_Store"
  json_support: false
  filename_as_id: false
  add_filesize: true
  remove_deleted: true
  add_as_inner_object: false
  store_source: false
  index_content: true
  attributes_support: false
  raw_metadata: false
  xml_support: false
  index_folders: false
  lang_detect: false
  continue_on_error: false
  ocr:
    language: "eng"
    enabled: true
    pdf_strategy: "ocr_and_text"
  follow_symlinks: false
elasticsearch:
  nodes:
  - url: "http://127.0.0.1:9200"
  bulk_size: 100
  flush_interval: "5s"
  byte_size: "10mb"
  index: "docs"
  index_folder: "folders">

The above is my settings.yaml. I am using **fscrawler-es7-2.7-SNAPSHOT --loop 1 --restart**
The _status.json file shows 
{
  "name" : "indexpresto",
  "lastrun" : "2019-09-05T09:35:37.873",
  "indexed" : 28,
  "deleted" : 0
}
which is the correct number of pdf files in the folders.

under the folder specified with fs.url, I have 2 folders:
Folder A (29 Mb) : 3 folders +  2 pdf files : total of 21 pdf files
Folder B(2.7 Mb) :  1 folder + 1 pdf file : total of 7 pdf files

Yet when I do a curl -XGET http://127.0.0.1:9200/indexpresto/_search?pretty=true,
I see info only for 10 files : for only the 2 pdf files under folder A and 8 pdf files  in one of the folders under Folder A.

Not sure why there is a discrepancy between _status.json result and the curl command to list all the documents in that index.

**To Reproduce**

**Expected behavior**

**Versions:**
 - OS: MacOS HighSierra
 - Version 10.13.6

**Screenshots**

**Comment by dadoonet** [comment]
Try:

```
curl -XGET http://127.0.0.1:9200/indexpresto/_search?pretty=true&size=100
```

**Comment by mchari** [comment]
Thanks , it works !
I am however unable to redirect the output to a file or pipe it to a file. Any insight ? 
I could confirm that it was working by painfully scrolling thro' the output on the terminal.

**Comment by dadoonet** [comment]
You mean? The output of the curl command?
