### ISSUE TITLE
Tesseract not working on scanned pdf

### ISSUE THREAD

**Issue by mgogh** [dadoonet/fscrawler#808]
Hi,

**My bug**

I'm trying to index scanned pdf using tesseract as you describe, but it's seems something goes wrong on my configuration. My pdf are indexed but there is no "content" field analyzed by Tesseract.

**To Reproduce**
Here is my configuration:

> 
      "fs" : {
           "url" : "/home/USER/test",
           "update_rate" : "15m",
           "excludes" : [ "*/~*" ],
           "json_support" : false,
           "filename_as_id" : false,
           "add_filesize" : true,
           "remove_deleted" : true,
           "add_as_inner_object" : false,
           "store_source" : false,
           "index_content" : true,
           "attributes_support" : false,
           "raw_metadata" : true,
           "xml_support" : false,
           "index_folders" : true,
           "lang_detect" : true,
           "continue_on_error" : true,
           "pdf_ocr": true,
           "ocr" : {
                "language": "en+fra",
                "path": "/usr/bin/tesseract",
                "data_path": "/home/USER/tesseract/lang"
           }
      }

I have on my folder:
- a scanned pdf
- a png

**Expected behavior**

I expect to have a "content" field on each hit for the png and the pdf but it is only working on the png file.

**Versions:**
 - Elasticsearch version 6.4
 - Fscrawler version 2.6

Is there anything wrong on my configuration ? Cause it's actually working on the png file.

Regards.

**Comment by dadoonet** [comment]
Could you try with the latest 2.7-SNAPSHOT?

**Comment by mgogh** [comment]
Hi,

Thanks for your response.

I try with the last SNAPSHOT but I have an error:

fscrawler-es6-2.7-SNAPSHOT/bin/fscrawler --config_dir config/ ocr-test
Exception in thread "main" java.lang.NumberFormatException: Infinite or NaN
        at java.math.BigDecimal.<init>(BigDecimal.java:898)
        at java.math.BigDecimal.<init>(BigDecimal.java:875)
        at fr.pilato.elasticsearch.crawler.fs.cli.BootstrapChecks.computePercentage(BootstrapChecks.java:61)
        at fr.pilato.elasticsearch.crawler.fs.cli.BootstrapChecks.checkJvm(BootstrapChecks.java:57)
        at fr.pilato.elasticsearch.crawler.fs.cli.BootstrapChecks.check(BootstrapChecks.java:40)
        at fr.pilato.elasticsearch.crawler.fs.cli.FsCrawlerCli.main(FsCrawlerCli.java:141)

Do you have any idea ?

Regards.

________________________________
De : David Pilato <notifications@github.com>
Envoyé : mardi 10 septembre 2019 14:49
À : dadoonet/fscrawler <fscrawler@noreply.github.com>
Cc : GOURLAY MAXIME <maxime.gourlay@anteagroup.com>; Author <author@noreply.github.com>
Objet : Re: [dadoonet/fscrawler] Tesseract not working on scanned pdf (#808)


Could you try with the latest 2.7-SNAPSHOT?

**Comment by dadoonet** [comment]
Yeah. You need to create a new configuration file from scratch I think.

**Comment by mgogh** [comment]
I get the same error trying to launch the command with a new configuration:

fscrawler-es6-2.7-SNAPSHOT/bin/fscrawler --debug new-job
Exception in thread "main" java.lang.NumberFormatException: Infinite or NaN
        at java.math.BigDecimal.<init>(BigDecimal.java:898)
        at java.math.BigDecimal.<init>(BigDecimal.java:875)
        at fr.pilato.elasticsearch.crawler.fs.cli.BootstrapChecks.computePercentage(BootstrapChecks.java:61)
        at fr.pilato.elasticsearch.crawler.fs.cli.BootstrapChecks.checkJvm(BootstrapChecks.java:57)
        at fr.pilato.elasticsearch.crawler.fs.cli.BootstrapChecks.check(BootstrapChecks.java:40)
        at fr.pilato.elasticsearch.crawler.fs.cli.FsCrawlerCli.main(FsCrawlerCli.java:141)

**Comment by dadoonet** [comment]
What are the settings for this new job?

**Comment by mgogh** [comment]
For now, there is no settings for the new job cause the following command return directly the error.
It doesn't propose me to create the new job (as usually when it's new https://fscrawler.readthedocs.io/en/latest/user/getting_started.html).

**Comment by dadoonet** [comment]
Most likely that's because you have existing jobs in the default folder. Could you empty it?

**Comment by mgogh** [comment]
Same error. I delete the default folder "~/.fscrawler/"
Launch the command:
fscrawler-es6-2.7-SNAPSHOT/bin/fscrawler job-test
   Exception in thread "main" java.lang.NumberFormatException: Infinite or NaN
        at java.math.BigDecimal.<init>(BigDecimal.java:898)
        at java.math.BigDecimal.<init>(BigDecimal.java:875)
        at fr.pilato.elasticsearch.crawler.fs.cli.BootstrapChecks.computePercentage(BootstrapChecks.java:61)
        at fr.pilato.elasticsearch.crawler.fs.cli.BootstrapChecks.checkJvm(BootstrapChecks.java:57)
        at fr.pilato.elasticsearch.crawler.fs.cli.BootstrapChecks.check(BootstrapChecks.java:40)
        at fr.pilato.elasticsearch.crawler.fs.cli.FsCrawlerCli.main(FsCrawlerCli.java:141)

Same error if I create an empty configuration folder and try to used it.

**Comment by dadoonet** [comment]
Which file did you download exactly?

**Comment by mgogh** [comment]
I download this file:
fscrawler-es6-2.7-20190829.115432-56.zip

But I just saw that there is a new SNAPSHOT for today (fscrawler-es6-2.7-20190910.132007-57.zip) should I download it and try ?

**Comment by dadoonet** [comment]
Should not change anything as only a dependency has been updated. I need to try to reproduce.

**Comment by fabiomoratti** [comment]
I have the exact same problem with the following sapshot: fscrawler-es7-2.7-20190919.103939-47, starting with an empty job. Any tests I can perform to help pinpont the problem?
Thanks.

**Comment by dadoonet** [comment]
I tried to reproduce on MacOS:

```sh
wget https://oss.sonatype.org/content/repositories/snapshots/fr/pilato/elasticsearch/crawler/fscrawler-es7/2.7-SNAPSHOT/fscrawler-es7-2.7-20190927.070712-49.zip
unzip fscrawler-es7-2.7-20190927.070712-49.zip
cd fscrawler-es7-2.7-SNAPSHOT/
bin/fscrawler --config_dir test test
```

Gave:

```
10:50:19,483 INFO  [f.p.e.c.f.c.BootstrapChecks] Memory [Free/Total=Percent]: HEAP [195.8mb/4gb=4.78%], RAM [21.4mb/16gb=0.13%], Swap [1.6gb/3gb=53.67%].
10:50:19,512 WARN  [f.p.e.c.f.c.FsCrawlerCli] job [test] does not exist
10:50:19,513 INFO  [f.p.e.c.f.c.FsCrawlerCli] Do you want to create it (Y/N)?
Y
10:50:22,256 INFO  [f.p.e.c.f.c.FsCrawlerCli] Settings have been created in [./test/test/_settings.yaml]. Please review and edit before relaunch
```

Then I ran:

```sh
bin/fscrawler --config_dir test test
```

And got:

```
10:50:59,111 INFO  [f.p.e.c.f.c.BootstrapChecks] Memory [Free/Total=Percent]: HEAP [195.7mb/4gb=4.78%], RAM [37.8mb/16gb=0.23%], Swap [1.6gb/3gb=53.67%].
10:51:00,201 INFO  [f.p.e.c.f.c.v.ElasticsearchClientV7] Elasticsearch Client for version 7.x connected to a node running version 7.3.2
10:51:00,300 INFO  [f.p.e.c.f.FsCrawlerImpl] Starting FS crawler
10:51:00,300 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler started in watch mode. It will run unless you stop it with CTRL+C.
10:51:00,933 INFO  [f.p.e.c.f.FsParserAbstract] FS crawler started for [test] for [/tmp/es] every [15m]
10:51:00,935 WARN  [f.p.e.c.f.FsParserAbstract] Error while crawling /tmp/es: /tmp/es doesn't exists.
```

Which is ok.

What is your OS? Could you run with `--trace` option? I feel like the recent changes I introduced with #776 is the source of the problem...

**Comment by dadoonet** [comment]
Yeah. So this line is the trouble... I guess that on some Os one value is 0 or something else...

```
        return new Percentage((new BigDecimal(((double) current.getBytes())/(double) max.getBytes()*100)).setScale(2, BigDecimal.ROUND_HALF_EVEN).doubleValue(), true);
```

**Comment by dadoonet** [comment]
Yeah. So I'm able to reproduce.
Some OS are reporting a `0` value. I need to check this when computing a percentage.
Here is a test case I will add as well:

```java
BootstrapChecks.computePercentage(ByteSizeValue.parseBytesSizeValue("0b"), ByteSizeValue.parseBytesSizeValue("0b"));
```

**Comment by dadoonet** [comment]
I fixed the problem hopefully with #819. Please allow some minutes to have the new version published on Sonatype.
Then could you test again the original problem with this new version?

**Comment by fabiomoratti** [comment]
Hello, I confirm that the problem is fixed using the lastes version (fscrawler-es7-2.7-20190927.095849-50.zip).
Just for completeness my OS is Ubuntu server 18.04.
Thank you very much for your support.

**Comment by dadoonet** [comment]
Thanks for giving a closure.
Happy that it worked!

**Comment by mgogh** [comment]
Hello,

Thank you for the correction. I cannot test the version you give me cause I'm using Elasticsearch V6.
Did you fix the issue also for fscrawlker-es6-* ?

Regards,
Maxime
________________________________
De : Fabio Moratti <notifications@github.com>
Envoyé : dimanche 6 octobre 2019 17:16
À : dadoonet/fscrawler <fscrawler@noreply.github.com>
Cc : GOURLAY MAXIME <maxime.gourlay@anteagroup.com>; Author <author@noreply.github.com>
Objet : Re: [dadoonet/fscrawler] Tesseract not working on scanned pdf (#808)


Hello, I confirm that the problem is fixed using the lastes version (fscrawler-es7-2.7-20190927.095849-50.zip).
Just for completeness my OS is Ubuntu server 18.04.
Thank you very much for your support.

**Comment by dadoonet** [comment]
There are also downloads available for es6.
