### ISSUE TITLE
FS Crawler needs a path_prefix attribute in Elasticsearch section of _settings.json

### ISSUE THREAD

**Issue by dansfelix** [dadoonet/fscrawler#816]
Hi Pilato,

Our infra team created a internal organization in Elasticsearch server: project areas by project codes. In our organization, all projects are identified  by a 4 char code, like clgp or disc. 

Because of this, infra team created folders in ELS side so as to organize stuff. A project can only create indexes in its particular folder. For ex, project clgp can only create index in https://elasticsearch-dev.mycompany.com/clgp/

I'd like to suggest a new **path_prefix** attribute in the elasticsearch section of _settings.json file:

```
"elasticsearch" : {
    "nodes" : [ {
      "url" : "https://elasticsearch-dsv.mycompany.com"
    } ],
    "bulk_size" : 100,
    "flush_interval" : "5s",
    "byte_size"   : "10mb",
    **"path_prefix" : "clgp",**
    "username"    : "clgp-all",
	"password"    : "xxxxxxx",
	"index"       : "clgp-docs",
	"index_folder": "clgp-folders"
  },
 
This simple feature would be great to FS Crawler in Enterprise scenarios.
```

**Comment by dadoonet** [comment]
I don't understand how that would work. Does it mean that the index name will change to `clgp-clgp-docs`?

Could you clarify how this setting should be used?

**Comment by dansfelix** [comment]
Here works this way:

DEV Instance: https://elasticsearch-dev.mycompany.com.br:443/clgp/clgp-docs/_search?pretty

PRD Instance: https://elasticsearch-prd.mycompany.com.br:443/clgp/clgp-docs/_search?pretty

It's mandatory, ruled by infra team. Any project only can write data to its own folder.

Thanks for reply.

**Comment by dadoonet** [comment]
I see. Behind a reverse proxy it could be needed.

The RestClient allows that so I can add the support for it:

```java
 RestClientBuilder builder = RestClient.builder(hosts.toArray(new HttpHost[hosts.size()]))
    .setPathPrefix("prefix");
```

I'll look at it unless you'd like to contribute the code?

**Comment by dansfelix** [comment]
I prefer you implement this feature.

Our Java specialist left department, so it is hard to me contribute the code. 

He named the attribute as path_prefix here.

Thanks a lot for help

**Comment by dadoonet** [comment]
@dansfelix Any chance you could test the #907 patch and tell me if this works for you?

**Comment by dadoonet** [comment]
The documentation about it is available here: https://fscrawler.readthedocs.io/en/pr-path_prefix/admin/fs/elasticsearch.html#path-prefix

**Comment by dansfelix** [comment]
I could not test it because I'am now running other projects. But we are using FS Crawler for 3 data lake projects here. One of them has 14 Tb of windows folders content for ingestion! Our main problem is stopping the process when network does not respond for a while, so we always need to begin everything again. In other issue, we talked about implement a retry mechanism.

The feature path_prefix in the product is very welcome, thaks a lot! 
Sorry about late reply. We were in holydays for brazilian Carnival.

**Comment by dadoonet** [comment]
> Sorry about late reply. We were in holydays for brazilian Carnival.

Hehe! Enjoy! 😉
