### ISSUE TITLE
Links in docs for fscrawler 2.7 not working

### ISSUE THREAD

**Issue by geekyogurt** [dadoonet/fscrawler#824]
The links given in the documentation for fscrawler 2.7 are not working. I am using elastic search 7.3.2 and no other fscrawler version is compatible with this version of elastic search.

**Comment by dadoonet** [comment]
Thanks for reporting. Sounds like an access problem on Sonatype. I'll check this.

**Comment by dadoonet** [comment]
I asked on [Twitter](https://twitter.com/dadoonet/status/1180033854196854786)... Let's see if something happens. cc @sonatype

**Comment by dadoonet** [comment]
The problem is fixed now. Thanks for reporting.
