### ISSUE TITLE
indexing pages in a document

### ISSUE THREAD

**Issue by mchari** [dadoonet/fscrawler#829]
Hi,
   I am using fscrawler to index several pdf documents. Once indexed, I am able to find the most relevant document for a query.
 Is there any way to index all the pages in each pdf file, and be able to find relevant page(s) within the retrieved document ?
Thanks,
Chari

**Comment by dadoonet** [comment]
There's not yet. See https://github.com/dadoonet/fscrawler/issues/767 which describes the same feature request.
