### ISSUE TITLE
FS Crawler freezes when crawling a 0 byte TXT file

### ISSUE THREAD

**Issue by dansfelix** [dadoonet/fscrawler#834]
Hello all,

I'm trying to use FS Crawler 2.6 in a Windows Server machine to index a huge number of files in my company. It's a very large Windows folders tree in a network drive: 14,92 Tb size, 7,2M files in 2,3M folders. Data are in a remote filer, in the same data center.

I realized that FS Crawler stops responding at some point of the process. Even if running in TRACE mode, there is no response, it only freezes. 

After using CONTROL + C command, I navigate in the error stack to find the original problem: a 0 byte TXT file caused the exception. 

Think it is easy to fix in the next versions.

Thank you

**Comment by den-kip** [comment]
Has this issue been fixed?

**Comment by dadoonet** [comment]
No. Wanna contribute a patch?
