### ISSUE TITLE
Termvectors from FSCrawler 

### ISSUE THREAD

**Issue by Ramon-zaro** [dadoonet/fscrawler#837]
Hi David @dadoonet 
I should make it clear that this is less of a feature request and more of a clarification.

I had a requirement of retreiving the TF-IDF values of terms in a document from a ES index. 
Please correct me if I am wrong but ES doesn't provide tf-idf directly so I thought of exposing the term vectors (term_statistics in particular) for a particular file in ES index crawled by FScrawler. I could then calculate the TF-IDF from that result.
Accordingly I added  'term_vectors':'yes' to the content field of the _settings file of the appropriate ES version I am using. It ran without throwing up errors and index was created. So far so good.

However, when I tried to retrieve the term vectos in kibana by document ID the result is clearly wrong and it is showing this result for every term in a document
```
 "term_vectors": {
        "content": {            
            "terms": {
                "term1": {
                    "doc_freq": 1,
                    "term_freq": 1,              
                    "ttf": 1
                },
.
.
.
```
Am I doing something wrong here ?

the only explanation I could come up with is that fscrawler's native analyzer does not create term vectors. I did try to debug it to find out what analyzers FS is using under the hood but I could not.
Could you please elaborate a little on what analyzers are used in FSC ?
Also, Is there a way to tweak the analyzer to add components I need ?
thanks a lot.

**Comment by dadoonet** [comment]
Did you check if your mapping/settings have been applied correctly?

**Comment by Ramon-zaro** [comment]
Hi David @dadoonet , sorry for the late reply. 
yes, I did set term_statistics to true if that's what you mean.

even otherwise, if you could tell me what to do in order to modify fscrawler's analyzer that would be a great help !

**Comment by dadoonet** [comment]
>  if you could tell me what to do in order to modify fscrawler's analyzer that would be a great help !

You can either create manually the index with your mapping and settings and then run FSCrawler. FSCrawler will skip the index creation as it already exists.
You can create your own mapping in FSCrawler job dir: 

* Globally: https://fscrawler.readthedocs.io/en/latest/admin/fs/elasticsearch.html#creating-your-own-mapping-analyzers
* Per job: https://fscrawler.readthedocs.io/en/latest/admin/fs/elasticsearch.html#define-explicit-mapping-settings-per-job

HTH

**Comment by dadoonet** [comment]
I hope my comments helped. I'm closing.
