### ISSUE TITLE
fscrawler rewriting entire document

### ISSUE THREAD

**Issue by AlonKapi** [dadoonet/fscrawler#841]
Hi, I'm using fscrawler with elastic search in such a way that fscrawler indexes documents from json files and then in my program I do some calculations and update a field directly from elastic search using the update API.

Now I also have a program that runs over the json files and updates another field directly in them.

Problem is when the file is updated, fscrawler overwrite the entire document in elastic search and then the calculation value in the field that I updated directly is deleted.

Is there an option to make fscrawler not overwrite the entire document and only update a single field?

Note that the fields are in a nested object like so:
`"mappings": {
  "_doc": {
    "properties": {
      "object": {
        "type": "nested",
        "properties": {
          "field_that_I_update_in_elasticsearch": {
            "type": "keyword"
          },
          "field_that_I_update_in_file": {
            "type": "keyword"
          }
          ... more fields
        }
      }
    }
  }
}`

**Comment by dadoonet** [comment]
@AlonKapi There is no such option today.

**Comment by shahariaazam** [comment]
I guess `fscrawler` only parse content and add few extra meta info. But so far I know it doesn't involve in making any change in the content. And it shouldn't.

**Comment by AlonKapi** [comment]
@dadoonet We solved the issue by using 2 indexes, but it'd have been better if fscrawler could "ignore" some fields or only update the field that changed.

**Comment by dadoonet** [comment]
@AlonKapi I have no idea on how to support such a feature.
Can't you send the document again to the same "pipeline" and compute again what is needed?
Can't you use Ingest Pipeline feature to make that run on elasticsearch side?

If the data is coming from another index, then may be you will be able to use the enrich processor which is coming in elasticsearch 7.5?

**Comment by dadoonet** [comment]
No more discussion is happening here. I'm closing but feel free to add your comments or reopen.

**Comment by dminovski0** [comment]
I have documents with multiple fields. Some of the fields can be updated directly with `PUT <index-id>/_doc/<doc-id>`. But, few of them need data that is in specific PDFs for every document. There is a PDF for each of those fields.

FSCrawler is run as a REST service, and the PDFs are sent to it with the parameters `index=<elastic-index>` and `id=<doc-id>`.  
If there is a document with a particular ID that already contains some data in the fields, FSCrawler sending the output from the PDF to that ID overwrites the entire document. Can this be avoided?

In one of the posts above, a user solved this by using multiple indices. Perhaps the PDFs can be indexed in different indices, and then the data copied to the main index while matching the documents by ID?
The data always gets parsed to a field named `content`. There are some suggestions to use ingest pipelines. Is there an option to specify them as a parameter when the PDF is sent?
