### ISSUE TITLE
java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: 复件 navLogo.gif

### ISSUE THREAD

**Issue by shahariaazam** [dadoonet/fscrawler#843]
`fscrawler` stopped after throwing this exception. But in my configuration I set `fs.continue_on_error`.

I am running fscrawler on a very very large file base. Like 39M files. And I don't know, sometimes in somewhere there can be a invalid character in file name.

But for that reason my fscrawler shouldn't complete stopped. It should ignore it. Need to discuss about this here.

**Comment by dadoonet** [comment]
Closed by #847
