### ISSUE TITLE
Unicode - large number of files

### ISSUE THREAD

**Issue by sohailmerchant** [dadoonet/fscrawler#848]
Hi

I am trying to index large number of files and wondering if it's supports unicode?  These files are mainly txt files in Arabic and Persian language with some markdown tags.   Some of these files could be between 50 to 100MB in sizes.

I wasn't able to index for some reasons.

Thanks
Sohail

**Comment by dadoonet** [comment]
Any error message ?

**Comment by sohailmerchant** [comment]
Thanks David for a prompt response. I had some 'hard failure' type errors, I tried it few times so wanted to make sure that there is no restriction/limitation on unicode or text with other languages?  I will try again tonight and report the outcome with log/settings.

**Comment by dadoonet** [comment]
I don't think i heard about such issues in the past.

**Comment by sohailmerchant** [comment]
I was successfully able to run the test with unicode/arabic/persian text files. For some reaons I was getting an error before.  I will do a test with 10K files now.  Thanks David.
