### ISSUE TITLE
Issue in Indexing using FSCrawler

### ISSUE THREAD

**Issue by Neel-Gagan** [dadoonet/fscrawler#850]
Fscrawler 2.6
ES 6.8.0
While running crawler on a folder the status file is getting updated and the log file of crawler show scanning of folders which contain several files, but the index in Kibana does not show any content of files scanned inside the crawled folder.
why is the file count not increasing even though the crawler is scanning the files ? 

```
16:41:50,006 DEBUG [f.p.e.c.f.c.FileAbstractor] 2 local files found
16:41:50,006 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] computeVirtualPathName(E:\Server, E:\Server Data\zip\Back_up_\app.xml) = /Server Data/zip/Back_up_/app.xml
16:41:50,006 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] directory = [false], filename = [/Server Data/zip/Back_up_/app.xml], includes = [null], excludes = [[*/~*]]
16:41:50,006 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] filename = [/Server Data/zip/Back_up_/app.xml], excludes = [[*/~*]]
16:41:50,006 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] filename = [/Server Data/zip/Back_up_/app.xml], includes = [null]
16:41:50,006 DEBUG [f.p.e.c.f.FsParserAbstract] [/Server Data/zip/Back_up_/app.xml] can be indexed: [true]
16:41:50,007 DEBUG [f.p.e.c.f.FsParserAbstract]   - file: /Server Data/zip/Back_up_/app.xml
16:41:50,007 DEBUG [f.p.e.c.f.FsParserAbstract]     - not modified: creation date 2019-10-16T11:36:15.729565 , file date 1980-01-01T00:00, last scan date 2019-11-18T16:38:15.242
```

**Comment by dadoonet** [comment]
@Neel-Gagan Could you try with 2.7-SNAPSHOT?

> but the index in Kibana does not show any content of files scanned inside the crawled folder.

Try with the `--restart` option. It will force to reindex data again.
May be that will help.

**Comment by dadoonet** [comment]
No feedback on this one. I'm closing. Feel free to add new comments.
