### ISSUE TITLE
mapping fields required when indexing documents

### ISSUE THREAD

**Issue by mchari** [dadoonet/fscrawler#852]
I am using fscrawler to index documents and it works fine.

I am trying to understand what mapping fields are provided when indexing a document.
I see the mapping description in _default/7/mapping.json. My question is : 
what are the fields that are provided explicitly when indexing a document, e.g,
If I use es.index(index,body = <text>), ES will just return the content when querying.
How does all the other info , e.g, meta, file, path fields get returned ? 
Does the body at index time in es.index() need to contain all that info ?

**Comment by dadoonet** [comment]
I'm not sure I'm understanding your question.
FSCrawler generates a JSON document containing lot of fields including content, document metadata, file metadata based on different sources like the file that has been crawled and its content as well (using Apache Tika behind the scene).

Not sure if that was your question though.

I'm closing for now as I don't see any bug or feature request but feel free to reopen or comment again.

**Comment by mchari** [comment]
That was the question.
Yes, I understand that all the metadata that I want to see in the query results needs to be provided at index time.
Thanks.
