### ISSUE TITLE
Bug Syntax error in fscrawler file, to init fscrawler

### ISSUE THREAD

**Issue by CarlosRCDev** [dadoonet/fscrawler#860]
IN: fscrawler/distribution/src/main/scripts/fscrawler

Syntax error: Unterminated quoted string

LINE PROBLEM: JAVA_OPTS="$JAVA_OPTS -Dsun.jnu.encoding=UTF-8
FIX: JAVA_OPTS="$JAVA_OPTS -Dsun.jnu.encoding=UTF-8"

**Versions:**
 - OS: Ubuntu
 - Version: fscrawler-es7-2.7-SNAPSHOT

**Comment by dadoonet** [comment]
Thanks for reporting. That's indeed a bug.
I'll fix it soonish.

**Comment by dadoonet** [comment]
I pushed e35c8e5 which should fix that. Let's wait for the next build to appear.
Thanks a lot for reporting!
