### ISSUE TITLE
json string to Nested type

### ISSUE THREAD

**Issue by arham92** [dadoonet/fscrawler#882]
i have json string like `"Tags": [{"Tag":"Ford"}, {"Tag":"BMW"}, {"Tag":"Fiat"}]`. 

How i can map this data to my index nested type field using ingest pipeline? 

Following is my index setting 

```
PUT my_index
{
  "settings": {
    "number_of_shards": 1
  },
  "mappings": {
    "dynamic": false,
    "properties": {
      "Tags":
       {
        "type": "nested",
        "properties": { 
          "Tag":  { "type": "keyword" }}
      }
    }
  }
}
```

**Comment by arham92** [comment]
i have json string like "Tags": [{"Tag":"Ford"}, {"Tag":"BMW"}, {"Tag":"Fiat"}]. How i can map this data to my index nested type field using ingest pipeline 
Following is my index setting 
put my_index
{
  "settings": {
    "number_of_shards": 1
  },
  "mappings": {
    "dynamic": false,
    "properties": {
      "Tags":
       {
        "type": "nested",
        "properties": { 
          "Tag":  { "type": "keyword" }}
      }
    
    }
  }
}

**Comment by dadoonet** [comment]
I don't think your question is related to FSCrawler project.
So I'm closing.

If you have questions regarding elasticsearch, please ask your question on https://discuss.elastic.co
