### ISSUE TITLE
Issue in Crawling files across two domains

### ISSUE THREAD

**Issue by Neel-Gagan** [dadoonet/fscrawler#891]
ES version 6.8
FScrawler Version 2.6

i am crawling a folder from a remote system which is a domain abc.in
[test.txt](https://github.com/dadoonet/fscrawler/files/4075469/test.txt)
. 
my Elasticsearch and FSCrawler is running on a different domain (xyz.in). 

although i am able to ping the system where the folder resides and SSH connection is also successful. still i am getting the error: \\ip addresss\crawl is not accessible.

what needs to be done to access the folder of abc.in domain from es running on abc.in.

**Comment by dadoonet** [comment]
Can you SSH from machine which runs FSCrawler to machine which holds your documents?

**Comment by Neel-Gagan** [comment]
Yes ssh connection is successful. as shown in the prompt of fscralwler.

**Comment by dadoonet** [comment]
I believe that once you are connected you can't run

    cd \\128.15.4.24\\crawl

Right?

**Comment by Neel-Gagan** [comment]
what i need to pass on in the url filed of _settings.json then ?

**Comment by dadoonet** [comment]
The path to your files once you are connected.

**Comment by Neel-Gagan** [comment]
that is what i am doing  i have set "url" : "\\128.15.4.24\\crawl",
and 
"server" : {
	"hostname" : "abcd-comp.abc.in",
	"port" : 22,
	"username" : "abc.in/user1",
	"password" : "password@1234",
	"protocol" : "ssh"
  },

as mentioned in my test file i have uploaded.

how can i access this folder then when it is showing \128.15.4.24\crawl does not exists. although ssh connection is successful.

**Comment by dadoonet** [comment]
Can you run:

    ssh abcd-comp.abc.in
    cd  \128.15.4.24\crawl
    ls

If you can't, there's no way that FSCrawler can as it performs similar commands

**Comment by dadoonet** [comment]
No further news. I'm closing. My guess is a wrong configuration of the job.
