### ISSUE TITLE
java.lang.NoSuchMethodError: parsing some Word files

### ISSUE THREAD

**Issue by mwaltersbmc** [dadoonet/fscrawler#895]
I'm using fscrawler 2.7 to index a collection of several thousand files on a Linux system but have several Word documents which fail with this error when run

13:09:08,850 WARN  [f.p.e.c.f.t.TikaDocParser] Failed to extract [100000] characters of text for [/tmp/test/SR_9000_20170706_CU_ALL_Readme.docx]  -> org.apache.poi.hwmf.record.HwmfRecord.getRecordType()Lorg/apache/poi/hwmf/record/HwmfRecordType;

The --debug output has a stack trace which starts with

13:09:08,850 DEBUG [f.p.e.c.f.t.TikaDocParser] Failed to extract [100000] characters of text for [/tmp/test/SR_9000_20170706_CU_ALL_Readme.docx]
java.lang.NoSuchMethodError: org.apache.poi.hwmf.record.HwmfRecord.getRecordType()Lorg/apache/poi/hwmf/record/HwmfRecordType;

The full debug output is attached, along with the .docx file and job config.

I'm running bin/fscrawler --trace --restart --loop 1 test

The error reproduces every time and looks like this known Tika issue 
https://issues.apache.org/jira/browse/TIKA-2904 that is supposed to be fixed in 1.22.

I ran the same file directly with Tika 1.22 and 1.23 and it parses without error and outputs the contents.

java -jar  tika-app-1.22.jar -T /tmp/test/SR_9000_20170706_CU_ALL_Readme.docx

Using
fscrawler-es7-2.7-20200122.065827-76.zip
CentOS Linux release 7.7.1908 (Core)
 java -version
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)
ES 7.5.1

Thank you for your work on fscrawler.
[NoSuchMethodError.zip](https://github.com/dadoonet/fscrawler/files/4103282/NoSuchMethodError.zip)

**Comment by dadoonet** [comment]
I'm sorry I did not look into this previously and thank you for reporting the issue with so much details.
It's the same error as described lately at #899 

See ****
