### ISSUE TITLE
How to achieve accurate searching for documents containing multiple languages?

### ISSUE THREAD

**Issue by nissansz** [dadoonet/fscrawler#936]
How to achieve accurate searching for documents containing multiple languages?

**Comment by dadoonet** [comment]
Hey


This is not really related to FSCrawler which only gathers content. But it's related to elasticsearch and how to deal with multiple languages.
I believe you would find more answers at discuss.elastic.co.

Some things which might help:

* https://greg.blog/2013/05/01/three-principles-for-multilingal-indexing-in-elasticsearch/
* https://www.elastic.co/guide/en/elasticsearch/guide/current/language-intro.html

FSCrawler might be able to detect the language. There are some ideas around this as well at https://fscrawler.readthedocs.io/en/latest/admin/fs/local-fs.html.
