### ISSUE TITLE
Folder index is not getting delete on delete of folder

### ISSUE THREAD

**Issue by ajain1209** [dadoonet/fscrawler#95]
As you know  FS river creates indexes of folders and files.
Suppose i mentioned URL: /var/tmp/ while creating river.there are 3 sub folders(aa bb cc) inside "tmp".
FS River will create 4 total documents. 
1.tmp
2.aa
3.bb
4.cc

if i delete cc sub folder then index of cc directory is not getting removed.
Please suggest ASAP.

**Comment by albertsun** [comment]
I think I'm seeing this issue as well. I'm on OS X 10.9.6 with Elasticsearch 1.3.2 installed via Homebrew and fsriver version 1.3.1

**Comment by ajain1209** [comment]
I am using Elasticsearch 1.1.0

**Comment by dadoonet** [comment]
Can you try it again with fscrawler 2.0.0 which has just been released?

**Comment by dadoonet** [comment]
Just tested and it does not work indeed (tested on a mac).
