### ISSUE TITLE
files lost

### ISSUE THREAD

**Issue by bluebell1990** [dadoonet/fscrawler#978]
My file is in EML format. When I scan more than 2,000 files, I may lose dozens of them. What are the possible reasons

**Comment by dadoonet** [comment]
Did you see anything in logs?
What are the config files and the logs?
Which version are you running ?

**Comment by bluebell1990** [comment]
Dear sir:
long time no see this project， the version is fscrawler-es7-2.7－SNAPSHOT ，we used it to crawl emails to elasticsearch&nbsp; everyday，and sometimes some emails lost ，then I try to crawl the lost email the second time ，it works，no fail logs show。
&nbsp; I sent you a test email contains the qq ***@***.*** ，please delete the information，it's in file&nbsp; FsCrawlerImplAllDocumentsIT.java， test.eml，TikaDocParserTest.java ，because my companion is troubled by some guys who saw the source code ，thank you very much。
I still use the project ，Thank you very much for your help。

---Original---
From: "David ***@***.***&gt;
Date: Sat, Jan 30, 2021 14:33 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [dadoonet/fscrawler] files lost (#978)




 
Did you see anything in logs?
 What are the config files and the logs?
 Which version are you running ?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
 
---Original---
From: "David ***@***.***&gt;
Date: Sat, Jan 30, 2021 14:33 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [dadoonet/fscrawler] files lost (#978)




 
Did you see anything in logs?
 What are the config files and the logs?
 Which version are you running ?

**Comment by dadoonet** [comment]
So you want to revert #954 (from what you provided at #948). I'll do this.

**Comment by dadoonet** [comment]
Done with #1115
