### ISSUE TITLE
OCR doesn't work

### ISSUE THREAD

**Issue by zydisney** [dadoonet/fscrawler#980]
I'm using fscrawler 2.7, Tesseract-OCR 5.0 on Windows 10

My fscrawler configured as:
```
  ocr:
    language: "eng+chi_sim+chi_tra"
    path: "C:\\Program Files\\Tesseract-OCR\\tesseract.exe"
    data_path: "C:\\Program Files\\Tesseract-OCR\\tessdata"
    output_type: "txt"
    enabled: true
    pdf_strategy: "auto"
  follow_symlinks: false
```
Console output as:
```
09:38:11,316 INFO  [f.p.e.c.f.c.BootstrapChecks] Memory [Free/Total=Percent]: HEAP [71.3mb/1.9gb=3.53%], RAM [2.2gb/7.9gb=27.86%], Swap [4.3gb/17.6gb=24.84%].
09:38:11,866 INFO  [f.p.e.c.f.c.v.ElasticsearchClientV7] Elasticsearch Client for version 7.x connected to a node running version 7.8.0
09:38:11,911 INFO  [f.p.e.c.f.FsCrawlerImpl] Starting FS crawler
09:38:11,911 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler started in watch mode. It will run unless you stop it with CTRL+C.
09:38:12,053 INFO  [f.p.e.c.f.FsParserAbstract] FS crawler started for [ocr3] for [C:\TESTFILE\] every [15m]
09:38:12,402 WARN  [o.a.t.p.PDFParser] J2KImageReader not loaded. JPEG2000 files will not be processed.
See https://pdfbox.apache.org/2.0/dependencies.html#jai-image-io
for optional dependencies.

09:38:13,719 INFO  [o.a.p.p.f.PDCIDFontType2] OpenType Layout tables used in font CIDFont+F1 are not implemented in PDFBox and will be ignored
09:38:13,811 INFO  [o.a.p.p.f.PDCIDFontType2] OpenType Layout tables used in font CIDFont+F2 are not implemented in PDFBox and will be ignored
09:38:13,877 INFO  [o.a.p.p.f.PDCIDFontType2] OpenType Layout tables used in font CIDFont+F1 are not implemented in PDFBox and will be ignored
09:38:13,949 INFO  [o.a.p.p.f.PDCIDFontType2] OpenType Layout tables used in font CIDFont+F2 are not implemented in PDFBox and will be ignored
09:38:14,010 INFO  [o.a.p.p.f.PDCIDFontType2] OpenType Layout tables used in font CIDFont+F3 are not implemented in PDFBox and will be ignored
09:38:18,615 INFO  [o.a.p.p.f.PDCIDFontType2] OpenType Layout tables used in font CIDFont+F1 are not implemented in PDFBox and will be ignored
09:38:18,705 INFO  [o.a.p.p.f.PDCIDFontType2] OpenType Layout tables used in font CIDFont+F2 are not implemented in PDFBox and will be ignored
```
The output in the Elasticsearch for `png` file  show nothing with the content.
```
...
"_source":{
    "meta":{},
    "file":{"
        extension":"png",
    "content_type":"image/png",
...
```

The output in the Elasticsearch for `pdf` file  show `\n\n` in the content

```
"hits":[{"_index":"ocr3",
    "_type":"_doc",
    "_id":"10e67595fa21117b7dcea63d9fc1756",
    "_score":4.5699587,
    "_source":{
        **"content":"\n\n",**
        "meta":{"author":"AaronYZhu",
            "title":"Annotation 2020-07-14 085015.png",
            "date":"2020-07-13T17:01:56.000+0000","format":"application/pdf; 
...
        "filename":"SCAN.pdf",
...
```

but when I use Tesseract in command line it works properly with the file. Please tell me how to deal with this problem

**Comment by dadoonet** [comment]
Hi

I wonder if on windows you should use:

    path: "/Program Files/Tesseract-OCR/tesseract.exe"
    data_path: "/Program Files/Tesseract-OCR/tessdata"

Or use a dir name which does not contain a space. My old windows time memory tells me to use something like `progra~1` alias as the dir name instead of `Program Files`.

Is FSCrawler also running from the `c:` drive?

Last workaround could be to add the Tesseract dir in the windows system PATH and reopen a new cmd window and start again FSCrawler without the path and data_path settings.

**Comment by zydisney** [comment]
I've installed the tesseract directly on `c:` and configure fscrawler as below, but doesn't work 
```
path: "/Tesseract-OCR/tesseract.exe"
data_path: "/Tesseract-OCR/tessdata"
```

Then I tried add PATH `C:\Tesseract-OCR`  to Windows and remove `path` and `data_path` configuration from fscrawler and it works! I think you may add such information to fscrawler's document. 
Thank you so much : ) !

**Comment by dadoonet** [comment]
I thought it was explained and clear enough at https://fscrawler.readthedocs.io/en/latest/user/ocr.html#ocr-path

May be we should add a recommendation for windows users to use the PATH?

**Comment by zydisney** [comment]
> 
> 
> I thought it was explained and clear enough at https://fscrawler.readthedocs.io/en/latest/user/ocr.html#ocr-path
> 
> May be we should add a recommendation for windows users to use the PATH?

Yes, I think we should add a recommendation for Windows user to configure the PATH. Since, I saw lots people have the same issue.

**Comment by dadoonet** [comment]
Would you like to open a PR for this?
