### ISSUE TITLE
maven fsriver build

### ISSUE THREAD

**Issue by sasidhar79** [dadoonet/fscrawler#99]
Hi 

I tried to build the 1.4.0 snapshot using 

mvn clean install
plugin --install fsriver \ 
       --url file:target/releases/fsriver-X.X.X-SNAPSHOT.zip

instructions from your website and I am getting this error
[ERROR] Failed to execute goal com.carrotsearch.randomizedtesting:junit4-maven-plugin:2.0.14:junit4 (tests) on project fsriver: Execution tests of goal com.carrotsearch.randomizedtesting:junit4-maven-plugin:2.0.14:junit4 failed: /home/sbetha/fsriver-es-1.4/target/junit4-ant-764895382365685372.xml:16: There were test failures: 5 suites, 17 tests, 1 suite-level error, 12 errors -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

Please help

thank u

sasi

**Comment by ilkermutlu** [comment]
I'm having the same error.

When I run it with the '-e' switch, I see errors in the following manner:

Throwable #1: java.lang.UnsupportedClassVersionError: fr/pilato/elasticsearch/river/fs/unit/FsIncludesExcludesTest : Unsupported major.minor version 51.0

I'm very alien to Java but, I think this is a compatibility error.

My Java version is as follows:

java version "1.6.0_29"
Java(TM) SE Runtime Environment (build 1.6.0_29-b11)
Java HotSpot(TM) 64-Bit Server VM (build 20.4-b02, mixed mode)

**Comment by ilkermutlu** [comment]
Also tried with 1.7.0_72

    java version "1.7.0_72"
    Java(TM) SE Runtime Environment (build 1.7.0_72-b14)
    Java HotSpot(TM) 64-Bit Server VM (build 24.72-b04, mixed mode)

I'm not getting the "Unsupported major.minor version 51.0" error but now I get more errors.

First one of many is:

    > Throwable #1: java.lang.NoSuchFieldError: LUCENE_4_10_1
   > 	at org.elasticsearch.Version.<clinit>(Version.java:206)
   > 	at org.elasticsearch.common.io.stream.StreamOutput.<init>(StreamOutput.java:42)
   > 	at org.elasticsearch.common.io.stream.BytesStreamOutput.<init>(BytesStreamOutput.java:58)
   > 	at org.elasticsearch.common.io.stream.BytesStreamOutput.<init>(BytesStreamOutput.java:55)
   > 	at org.elasticsearch.common.io.stream.BytesStreamOutput.<init>(BytesStreamOutput.java:45)
   > 	at org.elasticsearch.common.xcontent.XContentBuilder.builder(XContentBuilder.java:77)
   > 	at org.elasticsearch.common.xcontent.json.JsonXContent.contentBuilder(JsonXContent.java:38)
   > 	at org.elasticsearch.common.xcontent.XContentFactory.contentBuilder(XContentFactory.java:122)
   > 	at org.elasticsearch.common.xcontent.XContentFactory.jsonBuilder(XContentFactory.java:49)
   > 	at     fr.pilato.elasticsearch.river.fs.unit.FsIncludesExcludesTest.extract_from_array_and_remove_duplicates(FsIncludesExcludesTest.java:39)

**Comment by rlanore** [comment]
same error for me.
complete surefire reports at: http://pastebin.com/ndMJUEnc

**Comment by rlanore** [comment]
success to build. but not tested with this diff to pom.xml

 git diff
diff --git a/pom.xml b/pom.xml
index 0f66504..61638e0 100644
--- a/pom.xml
+++ b/pom.xml
@@ -39,7 +39,7 @@
         <elasticsearch.version>1.4.0</elasticsearch.version>
         <tika.version>1.5</tika.version>
         <poi.version>3.10.1</poi.version>
-        <lucene.version>4.10.0</lucene.version>
+        <lucene.version>4.10.2</lucene.version>
         <tests.output>onerror</tests.output>
         <tests.shuffle>true</tests.shuffle>
         <tests.output>onerror</tests.output>
@@ -286,6 +286,14 @@
             <artifactId>lucene-test-framework</artifactId>
             <version>${lucene.version}</version>
             <scope>test</scope>
+            <exclusions>
+              <exclusion>
+                <artifactId>randomizedtesting-runner</artifactId>
+                <groupId>
+                    com.carrotsearch.randomizedtesting
+                </groupId>
+               </exclusion>
+            </exclusions>
         </dependency>
         <dependency>
             <groupId>org.elasticsearch</groupId>
@@ -350,6 +358,12 @@
             <type>test-jar</type>
             <scope>test</scope>
         </dependency>
+        <dependency>
+          <groupId>com.carrotsearch.randomizedtesting</groupId>
+          <artifactId>randomizedtesting-runner</artifactId>
+          <version>2.1.10</version>
+          <scope>test</scope>
+        </dependency>
 
     </dependencies>

**Comment by jbwl** [comment]
I was not able to build 1.4.0-SNAPSHOT with rlanore's changes to the pom.xml file - maven stalls at FsRiverAllParametersTest.test_multiple_rivers

**Comment by dadoonet** [comment]
The project has been rewritten completely and I hope this is fixing your issues.
Closing but feel free to reopen if you still can't compile the project.
