### ISSUE TITLE
Running FSCrawler without arguments does not give the list of existing jobs.

### ISSUE THREAD

**Issue by SevyRetymsed** [dadoonet/fscrawler#995]
**Running FSCrawler without arguments does not give the list of existing jobs.**

As stated on [https://fscrawler.readthedocs.io/en/latest/user/getting_started.html](url) : 
> You can also run FSCrawler without arguments. It will give you the list of existing jobs and will allow you to choose one

Contrary to this statement, I get no list : 
```
[root@kibana fscrawler-es7-2.7-SNAPSHOT]# bin/fscrawler 
18:19:45,369 INFO  [f.p.e.c.f.c.BootstrapChecks] Memory [Free/Total=Percent]: HEAP [58.9mb/841mb=7.01%], RAM [1.5gb/3.6gb=41.31%], Swap [1.4gb/1.4gb=99.72%].
18:19:45,372 INFO  [f.p.e.c.f.c.FsCrawlerCli] No job specified. Here is the list of existing jobs:
18:19:45,374 INFO  [f.p.e.c.f.c.FsCrawlerCli] No job exists in [/root/.fscrawler].
18:19:45,374 INFO  [f.p.e.c.f.c.FsCrawlerCli] To create your first job, run 'fscrawler job_name' with 'job_name' you want
```

Three different jobs do exist on the right location : 
```
[root@kibana .fscrawler]# pwd
/root/.fscrawler
[root@kibana .fscrawler]# ll
total 0
drwxr-xr-x. 4 root root 24 Aug  9 10:10 _default
drwxr-xr-x. 2 root root 48 Aug  9 10:18 hell
drwxr-xr-x. 2 root root 48 Aug  9 17:03 minihell
drwxr-xr-x. 2 root root 48 Aug  9 11:16 purgatory
```
I can call all three of these jobs using their name as argument and they do work.

**Comment by dadoonet** [comment]
Looks like a bug indeed. Thanks for reporting.

**Comment by janhoy** [comment]
I just discovered the same.
Related: Would it be possible to have fscrawler run multiple jobs in one instance, or do I have to start one fscrawler for each job. I will have 3-4 jobs in my project.
